### ISSUE TITLE
A question for style module

### ISSUE THREAD

**Issue by Censwin** [snabbdom/snabbdom#1000]
Hi，I see the following description on the readme:
> Note that the style module does not remove style attributes if they
are removed as properties from the style object. To remove a style,
you should instead set it to the empty string.   

and I tried to remove the properties from the style object, like this:
```js
const container = document.getElementById("app");
const patch = init([styleModule, attributesModule]);
const vnode1 = h("section", [
  h("span", { style: { color: "red" }, attrs: { id: "span_1" } }, "Hello")
]);
patch(container, vnode1);

const vnode3 = h("section", [
  h("span", { style: {},attrs: { id: "span_1" } }, "Hello")
]);
patch(vnode1, vnode3);
```
It is working.
Could somebody provide an incorrect example?

**Comment by jvanbruegge** [comment]
Looking at the code, this is outdated documentation. Could you open a PR to fix it?

**Comment by Censwin** [comment]
> Looking at the code, this is outdated documentation. Could you open a PR to fix it?
This code commits at 6 years ago, maybe it is really outdated. Can I delete this code?

**Comment by Censwin** [comment]
> Looking at the code, this is outdated documentation. Could you open a PR to fix it?

This code commits at 6 years ago, maybe it is really outdated. Can I delete this code?
