### ISSUE TITLE
Patch fragment VNode Faild

### ISSUE THREAD

**Issue by cqh963852** [snabbdom/snabbdom#1007]
https://codesandbox.io/s/focused-dan-g6xck2?file=/src/index.ts

![image](https://user-images.githubusercontent.com/17702287/159131174-2b06704a-74c7-44b0-929c-65b8f040c9d1.png)

While patch a fragment node. It will show a common error. 

Can I patch a subtree that not from root? 
It seems work if node created by h function.

**Comment by cqh963852** [comment]
https://codesandbox.io/s/naughty-gauss-ocj5cf?file=/src/index.ts

a demo from https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment

the fragment node's parentNode is null

**Comment by cqh963852** [comment]
While add a new element to fragment. 
![image](https://user-images.githubusercontent.com/17702287/159171185-9a621f33-1f6f-45f9-af2f-83179c36188c.png)
The parentEl is fragment. and before is null.
So ,the new node can't be added.

**Comment by cqh963852** [comment]
![image](https://user-images.githubusercontent.com/17702287/159172164-ed5d6428-4c66-487c-aebe-786f26b28ac9.png)
While referenceNode is not null,It can work.
But if adding a node to fragment's 0 index. the referenceNode will be null.

**Comment by jvanbruegge** [comment]
Thanks for the investigation. Can you open a PR with your solution and add a test to catch the error?
Also cc @ryota-ka because you wrote the fragment support :)

**Comment by rosostolato** [comment]
@cqh963852 any luck on this?

**Comment by rosostolato** [comment]
I found a solution for this and added a commit for the [PR](https://github.com/snabbdom/snabbdom/pull/1015) of the other [issue](https://github.com/snabbdom/snabbdom/issues/1014) I opened yesterday.

**Comment by cqh963852** [comment]
> @cqh963852 any luck on this?

Going to closing this issue. Because the maintainer has no response to my PR

**Comment by kuraga** [comment]
@cqh963852, I understand your feelings. But I think @jvanbruegge will find a time for this in early May.

@cqh963852, I understand your feelings. But let's reopen this and #1009...

Thanks!
