### ISSUE TITLE
Suggestions for adjusting folder structure

### ISSUE THREAD

**Issue by cqh963852** [snabbdom/snabbdom#1010]
- Set a index.ts file at root of package.
Other project can easy link package without build. It will be much easier for debugger.

- Use yarn workspaces.
It can make a mono repo. 
Such as DOMAPI can be put into a single package. Each modules can has it own package.

Here is a template for reference https://github.com/idealjs/mono-template

**Comment by jvanbruegge** [comment]
this does not make much sense
