### ISSUE TITLE
Why the first parameter of Listener is VNode？

### ISSUE THREAD

**Issue by zhtzhtx** [snabbdom/snabbdom#1032]
Hi，Snabbdom is a nice project. It helped me a lot to learn Virtual DOM.
When I read the code in **modules/eventlisteners.ts**:
```js
type Listener<T> = (this: VNode, ev: T, vnode: VNode) => void;
```
I think the first parameter should be removed：
```js
type Listener<T> = (ev: T, vnode: VNode) => void;
```
We call the function through **Function.call** ，not call itself:
```js
handler.call(vnode, event, vnode);
```
So **this:VNode** should be the parameter of  **Function.call**, not the parameter of **Listener**.
If there is something wrong with what I say，please tell me know.
Thanks.

**Comment by paldepind** [comment]
This seems right to me. `Function#call` sets the `this` argument to `vnode` and the first argument in `Listener` is named `this` which in TypeScript corresponds to the type of `this` for the function.
