### ISSUE TITLE
Release 3.5.1 drops IE11 support

### ISSUE THREAD

**Issue by edmorrish** [snabbdom/snabbdom#1047]
Looks like one of the changes introduced in version 3.5.1 added a use of `Array.from`: https://github.com/snabbdom/snabbdom/commit/230aa23a694726921c405c4b353e8cb6968483bb#diff-b06da8b5eaf15ddfe5341deaeef13cb9c94546db8b0bd927dd358142aa4fc3c7R122

which is not supported on IE11 according to caniuse (https://caniuse.com/mdn-javascript_builtins_array_from).

I don't think there's any published documentation on what browsers are supported by snabbdom, but I'm fairly sure that until this change snabbdom worked out of the box on IE11. If the intention is not to support older browsers in future that's fine, and I can look into polyfilling it for our use case, but it would be good to know if this was an intentional choice or an oversight.

**Comment by jvanbruegge** [comment]
It was not an international choice, but IE11 is EOL, so I do not want to support it either. So for all intents and purposes, no IE is not supported any more

**Comment by edmorrish** [comment]
Okay, thanks for your reply!
