### ISSUE TITLE
consider version-bumping and refreshing this project

### ISSUE THREAD

**Issue by iambumblehead** [snabbdom/snabbdom#1051]
Politely, it would be great if snabbdom would get a little bit of a maintenance refresh.

Snabbdom seems dormant but is still currently the best virtual-dom implementation. It is a powerful tool for real people building things outside of corporate and enterprise influence. Great things about snabbdom,
 * snabbdom is stable and not a constantly-moving target,
 * snabbdom does not require a transpiler,
 * snabbdom is small and fast,
 * snabbdom does not have useless, stupid, distracting features
 * snabbdom is readable and not over-engineered or over-optimized,
 * snabbdom is not controlled by corporate or non-corporate entity/foundation

I would submit PRs myself but there are many ignored PRs and issues. Probably, new PRs and issues would be ignored as well.

Snabbdom is already amazing and keeping it fresh would be of great value.

**Comment by jvanbruegge** [comment]
I've updated the dev dependencies now, but as snabbdom has no dependencies and there haven't been any changes to the code there is no reason to version bump

**Comment by iambumblehead** [comment]
Thanks. Version bumps signal the project is still recently maintained and there are a few other things that would be nice to have with a version bump,
 * passing unit-test pipeline and badge,
 * snabbdom's packaged size could be much smaller. Currently it is about ~420kB https://packagephobia.com/result?p=snabbdom but is probably less 60kB if published to npm with a "files" directive, probably `files: ["dist/"]` would be sufficient (the readme and license don't need to be specified),
 * responses to some ignored issues and PRs. As a lurker, some of the issues seem important, for example these https://github.com/snabbdom/snabbdom/issues/1049 https://github.com/snabbdom/snabbdom/pull/957
 * some of the language in the README might be a little stale, for example the reference to object spread syntax at the bottom of the README is a little dated-sounding, now that object spread syntax is ubiquitous

**Comment by iambumblehead** [comment]
also as mentioned here https://github.com/snabbdom/snabbdom/issues/1050  it would be great if snabbdom's main module file would be named with an .mjs extension, so that it could be imported directly with module type packages,
```diff
  "main": "build/snabbdom.cjs.js",
- "module": "build/index.js",
+ "module": "build/index.mjs",
+ "files": ["dist"],
```

**Comment by paldepind** [comment]
Thank you for raising these concerns @iambumblehead, for showing interest in Snabbdom, and for the list of positives 😄 

I see what you mean and your feedback is definitely valuable. Especially pointing out specific things that we can address. If you can think of more in addition to what you've already mentioned then feel free to do so.

I'll have some more free time in a couple of weeks and might be able to look at some of these.

>I would submit PRs myself but there are many ignored PRs and issues. Probably, new PRs and issues would be ignored as well.

I understand that an open list of ignored PRs can be discouraging, but if you submit any PRs I'll try and take a look at them within a reasonable timeframe.

**Comment by iambumblehead** [comment]
Thanks for the kind response. I don't want to be a nuisance. These are a few small things I thought of since yesterday and they may not be important to you feel free to ignore...
 * Reduce the size of the README by moving some parts to another document. This would reduce snabbdom's overall install-size, if the full documentation were not published in the README,
 * Change the primary branch from "master" to "main". This would reduce context-shift when going back and forth between projects created with default main and master branch. Using the primary branch name input in https://github.com/snabbdom/snabbdom/settings would take care many things at once and then updating github ci specs to reference 'main' rather than 'master' would maybe take care of the rest. 

I wonder if snabbdom could be modified to flatten child node lists. Inferno does do this (I believe react does do this also) and its not super necessary or important but slightly improves ergonomics in some situations. It would be great if it could be supported with a one or two-line change. Here is an example demonstrating what I mean,
```javascript
  h('nav', [
    h('ul', (
      [ 'item1', 'item2' ].map(i => (
        h('li', i)))
      ))
    ])
// <nav>
//   <ul>
//     <li>item1</li>
//     <li>item2</li>
//   </ul>
// </nav>

  h('nav', [
    h('ul', [ // <- nesting array
      [ 'item1', '.item2' ].map(i => (
        h('li', i)))
      ])
    ])
// <nav>
//   <ul>undefined</ul>
// </nav>
```
Possibly soon I will update a large inferno app and if snabbdom is added there I could share any interesting differences that pop out. Note, I don't believe snabbdom should be inferno, but there could be interesting differences.

The feature I would like most is reported here https://github.com/snabbdom/snabbdom/issues/1050 however I believe it would be challenging to support and could be too much effort; snabbdom patching that uses configurable dom instances. This would allow concurrent tests to run each with their own local dom instance,
```javascript
const dom = new JSDOM(
  '<!DOCTYPE html><body><div id="container"></div></body>')
snabbdom.init([], dom.window)
```
Among other things, innerHTML from dom instances can be beautified and diffed for snapshot and unit-tests.

**Comment by iambumblehead** [comment]
my first PR to snabbdom https://github.com/snabbdom/snabbdom/pull/1056

feel free to leave any criticism or concerns or anything at all

**Comment by iambumblehead** [comment]
If the primary branch is renamed from "master" to "main", it is recommended to first accept or close currently outstanding PRs that use "master" destination branch

**Comment by iambumblehead** [comment]
If snabbdom were updated to use an externally configured dom, performance could be measured using node's runtime and CI steps could auto-compare performance differences associated with PR changes.
