### ISSUE TITLE
the styleModule has problems handling style updates with attribute values of 0

### ISSUE THREAD

**Issue by chuifengji** [snabbdom/snabbdom#1093]
**the styleModule has problems handling style updates with attribute values of 0**

``` typescript
for (name in oldStyle) {
    if (!style[name]) { // here's the mistake
      if (name[0] === "-" && name[1] === "-") {
        (elm as any).style.removeProperty(name);
      } else {
        (elm as any).style[name] = "";
      }
    }
  }
```
The above code should be changed to：
``` typescript
for (name in oldStyle) {
    if (!(name in style)) { // how to fix it
      if (name[0] === "-" && name[1] === "-") {
        (elm as any).style.removeProperty(name);
      } else {
        (elm as any).style[name] = "";
      }
    }
  }
```

**Comment by paldepind** [comment]
Thank you for reporting this @chuifengji. I'll take a look at this.

In the meantime, I think you should be able to work around the problem by using `"0"` instead of just `0` as your flex-shrink value.

**Comment by paldepind** [comment]
Can you describe exactly what problem you are experiencing? I can see that the line you highlight is not ideal, but it's not clear how this results in a bug (except for the property being set to `""` and then re-set correctly when the new properties are handled).

**Comment by paldepind** [comment]
@chuifengji Please see #1094 which should fix your problem.

**Comment by chuifengji** [comment]
thanks!
