### ISSUE TITLE
Any Break Change in 3.6.0?

### ISSUE THREAD

**Issue by Vikingama** [snabbdom/snabbdom#1100]
After release of 3.6.0,the application breaks down.
![Microsoft Remote Desktop-2024-01-23-06 34 18](https://github.com/snabbdom/snabbdom/assets/26019582/3a1dc8fd-c67f-4499-a720-fc8ea628adc4)

**Comment by paldepind** [comment]
Which version of TypeScript are you using?

**Comment by Vikingama** [comment]
> Which version of TypeScript are you using?

4.0.8, After update to 4.1.6, problem resolved.
Thank you

**Comment by paldepind** [comment]
Glad it solved your problem. I've updated the changelog and GitHub release with this information.

I hope this doesn't affect too many people given that 4.1 is about 3 years old.
