### ISSUE TITLE
3.6.0 './h' failed to resolve only because it was resolved as fully specified

### ISSUE THREAD

**Issue by ForsakenE** [snabbdom/snabbdom#1102]
build/jsx.js  use './h' to import js file ，bug in package.json，use type:'module'

**Comment by paldepind** [comment]
Hello @ForsakenE. This bug report is a little bit hard to read. Is this the same issue as #1087? If not, please provide a bit more information 🙂

**Comment by ForsakenE** [comment]
yes, i use webpack to build my project,but found this error&nbsp;&nbsp;'./h' failed to resolve only because it was resolved as fully specified ,the reason same as you provide number #1087




怪咖-&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "snabbdom/snabbdom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月27日(星期六) 凌晨0:20
***@***.***&gt;;
抄送:&nbsp;"怪咖- ***@***.******@***.***&gt;;
主题:&nbsp;Re: [snabbdom/snabbdom] 3.6.0 './h' failed to resolve only because it was resolved as fully specified (Issue #1102)





 
Hello @ForsakenE. This bug report is a little bit hard to read. Is this the same issue as #1087? If not, please provide a bit more information 🙂

**Comment by ryota-ka** [comment]
I also ran into this issue after updating to v3.6.0.
I've submitted #1104 to fix this problem.

**Comment by jvanbruegge** [comment]
This should be fixed in `3.6.1`
