### ISSUE TITLE
Why can't the file be found after updating 3.5.1 to 3.6.0?

### ISSUE THREAD

**Issue by royWoody** [snabbdom/snabbdom#1103]
![image](https://github.com/snabbdom/snabbdom/assets/8044025/b98e6eb2-bae6-412d-abc6-5de8495f39e9)

**Comment by royWoody** [comment]
If the modification is not backward compatible, can the version be upgraded to 4.0.0?

**Comment by jvanbruegge** [comment]
This should be fixed in `3.6.1`, please let me know if it is not
