### ISSUE TITLE
Explanation about how to build

### ISSUE THREAD

**Issue by grimalschi** [snabbdom/snabbdom#113]
Hello!

I like snabbdom, but at first i did not understand how to build it for using in browser. After this i found what is browserufy and i found that i can build application using this tool. I found it in this README: https://github.com/paldepind/snabbdom/tree/master/examples/carousel-svg

I think it can be much easier to start work with snabbdom if there will be prepared builds or instruction for building or using of building system (gulp, grunt).

Sorry for bad english. Hello from Ukraine!

**Comment by grimalschi** [comment]
Close because of #119

**Comment by paldepind** [comment]
Are you sure? Shouldn't we add something to the readme to explain how to do builds and how to use the browser-friendly files?

**Comment by grimalschi** [comment]
Yeah, you are right.

**Comment by heronils** [comment]
There was an attempt.
