### ISSUE TITLE
Support custom elements

### ISSUE THREAD

**Issue by edoardocavazza** [snabbdom/snabbdom#141]
Hi, do you have plans for custom elements support?

I gave a look at the code and should be a painless implementation (just handle the `is` attribute and add an argument to the `createElement` functions).

If you glad, I can submit a PR.
Thanks

**Comment by paldepind** [comment]
I actually didn't know of that feature.

If I understand correctly we should just handle an `is` property on the data object and pass it along to `createElement`. The code should be changed around [here](https://github.com/paldepind/snabbdom/blob/1bfb2834db6fc030aaf6505bacfa97cdc5fabee6/snabbdom.js#L70).

Does that sound right to you? I'd love a PR :smile:

**Comment by mightyiam** [comment]
I didn't try to do this, because master doesn't seem to compile:
```
➜  snabbdom git:(master) npm-run tsc
src/helpers/attachto.ts(19,16): error TS2531: Object is possibly 'null'.
src/htmldomapi.ts(39,10): error TS2322: Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
  Type 'null' is not assignable to type 'HTMLElement'.
src/htmldomapi.ts(43,10): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
  Type 'null' is not assignable to type 'Node'.
```

**Comment by kristianmandrup** [comment]
What is the status on custom elements v1 support!? 
Super important now that all major browser vendors are finally onboard!!

**Comment by caridy** [comment]
This is tricky, but doable. The thing is that the `is` attribute is very especial, and can only be set once, that's why you should pass it when `createElement()` is invoked. You cannot change that value after the fact according to the Spec (IIRC), and the reason for that is because the registered component declaration it already in controlled of the element.

In other words, at the minute we start taking `is` attribute for the construction, we will have to also use it in `sameVnode()`, because we can't patch `<div is="x-foo">` against `<div is="x-bar">`, that will be probably wrong.

Give me a couple of days to investigate more about this.

**Comment by kristianmandrup** [comment]
So far I experimented with the following:

```js
// snabbdom.ts
function createElm(vnode: VNode, insertedVnodeQueue: VNodeQueue): Node {
      // ...
   else if (sel !== undefined) {
      // Parse selector
      // ...
      // extract special is attribute for custom elements support
      const attrs = vnode.data ? vnode.data.attrs : undefined
      const isElem = attrs ? { is: attrs.is } : {}
      // console.log('isElem', attrs, isElem)

      // supports custom elements via isElem
      const elm = vnode.elm = isDef(data) && isDef(i = (data as VNodeData).ns) ? api.createElementNS(i, tag)
        : api.createElement(tag, isElem);

```
```js
// htmldomapi.ts

export interface DOMAPI {
  // add attrs to support special is attribute ie. for custom element
  createElement: (tagName: any, attrs?: Object) => HTMLElement;
  // ...
}

  // add attrs to support special is attribute ie. for custom element
function createElement(tagName: any, attrs?: Object): HTMLElement {
  return document.createElement(tagName, attrs);
}

```

And then in `sameVnode` I'd guess sth like this?

```js
function sameVnodeTag(vnode1: VNode, vnode2: VNode): boolean {
  return vnode1.key === vnode2.key && vnode1.sel === vnode2.sel;
}

function sameVnodeCustomElem(vnode1: VNode, vnode2: VNode): boolean {
  let data1 = vnode1.data, data2 = vnode2.data
  if (!data1 && !data2) return false;
  return (data1.attrs && data2.attrs ? data1.attrs['is'] === data2.attrs['is'] : false;
}

function sameVnode(vnode1: VNode, vnode2: VNode): boolean {
  return sameVnodeTag(vnode1, vnode2) && sameVnodeCustomElem(vnode1, vnode2);
}
```

However when I try to write a test case...

```js
import htmlDomApi, {
  DOMAPI
} from './htmldomapi';
const api = domApi !== undefined ? domApi : htmlDomApi;

class MyElem extends HTMLElement {
  constructor() {
    // If you define a ctor, always call super() first!
    // This is specific to CE and required by the spec.
    super();
    console.log('created MyElem custom element')
  }
}
api.customElements.define('my-elem', MyElem);
```

There is no `customElements.define` on the API yet, so that needs to be added as well ;)

```js
describe('snabbdom', function () {
  var elm, vnode0;
  beforeEach(function () {
    elm = document.createElement('div');
    vnode0 = elm;
  });

  describe('custom element', function () {
    it('has custom tag', function () {
      elm = patch(vnode0, h('div', {
        is: 'my-elem'
      })).elm;
      assert.equal(elm.tagName, 'MY-ELEM');
    });
  });
```

But getting close I reckon!

**Comment by kristianmandrup** [comment]
WIP branch: [custom-elements-v1](https://github.com/kristianmandrup/snabbdom/tree/custom-elements-v1)

Needs to be tested in a sample app ;)

**Comment by kristianmandrup** [comment]
Looks like it might require some "fixes" in cycle/dom as well?
Hardcoded to call `h_1.h("" + tagName.toLowerCase() + selId + selClass, {}, children);` which is the `h` method of snabbdom, always with an empty set of attributes?

```js
    VNodeWrapper.prototype.wrap = function (children) {
        var _a = this.rootElement, tagName = _a.tagName, id = _a.id, className = _a.className;
        var selId = id ? "#" + id : '';
        var selClass = className ?
            "." + className.split(" ").join(".") : '';
        return h_1.h("" + tagName.toLowerCase() + selId + selClass, {}, children);
    };
```

**Comment by kristianmandrup** [comment]
Please, let's get it working!! So close :) Then all these [web components](https://www.webcomponents.org/) are ripe for the taking!

**Comment by kristianmandrup** [comment]
Somehow my sample app is not using my modified snabbdom (branch). Anyhow, when I try:
`h('my-elem')` I get

```
'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at HTMLElement.MyElem (bundle.js:19490)
    at wrappedConstructor (polydev/src/document-context/measure-custom-elements.js:87)
    at Object.createElement (bundle.js:12182)
    at createElm (bundle.js:11947)
``` 

Caused by:

```
	"use strict";
	function createElement(tagName) {
	    return document.createElement(tagName);
	}
```

**Comment by kristianmandrup** [comment]
Apparently, this is also an option:

```js
const BiggerImage = customElements.get('bigger-img');
const image = new BiggerImage(15, 20); // pass ctor values like so.
```

**Comment by kristianmandrup** [comment]
Is THIS essentially what I'm trying to achieve?

```
bundle.js:19490 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at HTMLElement.MyElem
```

```js
  const MyElem = customElements.get('my-elem')
  console.log('myElem', MyElem,  new MyElem())

  const vtree$ = xs.of(
    div('My Awesome Cycle.js app'),
  )
```

**Comment by kristianmandrup** [comment]
Maybe it would help to include a [webcomponents polyfill](https://github.com/webcomponents/webcomponentsjs)

**Comment by kristianmandrup** [comment]
I found the [cycle-custom-elementify](https://github.com/staltz/cycle-custom-elementify/issues/1) but it only support custom elements v0. Also references this [path PR to snabbdom](https://github.com/snabbdom/snabbdom/pull/159)

**Comment by kristianmandrup** [comment]
A better Polyfill? [document-register-element](https://github.com/WebReflection/document-register-element)

**Comment by kristianmandrup** [comment]
I since realized that my troubles above were due to cycle.js loading its own version of `snabbdom` (peer dependency) instead of using my modified one, linked using `npm link` but ignored.
The trick was simply to load `h`  directly from `snabbdom` and use it... My changes work! 

As an example, the new [Google chrome cast API](https://www.youtube.com/watch?v=pvyfddIFsVA) comes with a special `chrome cast` button where you need to extend it using `{is: 'chrome-cast-button'}`, exactly the patch I made! 

So Custom Elements are really here in 2017. Time to update the libs and frameworks to support it :)

**Comment by the-dr-lazy** [comment]
Is anyone actively working on this?

**Comment by mightyiam** [comment]
No one is working on this.

**Comment by the-dr-lazy** [comment]
Thank you @mightyiam. I'll submit a PR.

**Comment by mreinstein** [comment]
Since we're changing the public snabbdom API I think this is technically a breaking change. Adding it to the `v3` milestone.

**Comment by paldepind** [comment]
@mreinstein 

> Since we're changing the public snabbdom API I think this is technically a breaking change. Adding it to the v3 milestone.

Yes I agree, technically it's a breaking change since Snabbdom now uses the `is` attribute on vnodes which users could have used themselves with a custom module etc. But, on the flip-side it that is very unlikely to happen so in reality I'm guessing that the breaking change won't actually break anything 😄. We should make that clear in the release notes.

**Comment by kuraga** [comment]
V1 -> V2 had a small breaking change, too. It's a common practice.
