### ISSUE TITLE
Proposal: Port to TypeScript

### ISSUE THREAD

**Issue by TylorS** [snabbdom/snabbdom#150]
Hello @paldepind, as I know you're aware, we are making use of this fantastic library in Cycle.js and Motorcycle.js has been using it since about November or December. We've been more and more embracing TypeScript and find that the only thing that is difficult is libraries which we are dependent on, not having or having out-of-date typings, which is why I had sent a PR for type definitions previously. However maintaining type-definitions is tedious, painfully error-prone, and now I have many spread across multiple projects that I try my best to keep up-to-date, but has been difficult.

I've been working on reviving some neglected parts of Motorcycle, porting to TypeScript, and I've been doing my best to ensure that all packages are tree-shaking compatible providing ES2015 builds alongside the commonjs builds. This is where I've ran into issues.

Compiling a TypeScript library/application to ES2015 does not allow for commonjs `module.exports` (Technically `exports.prop` will not work either, but there _are_ workarounds). For type definitions to be correct, they use the following syntax

``` typescript
declare namespace "snabbdom/h" {
  export = // ...
}
```

Which restricts TypeScript to using `import h = require('snabbdom/h')` but this disallows compiling to ES2015, and thus disallows tree-shaking compatibility.

So I propose moving the current codebase, starting with a 1:1 port, to TypeScript. Type Definitions will be consistent 100% of the time for users, and are properly versioned with snabbdom itself. Other benefits include ES2015 builds for tree shaking and standards compliance. Another benefit, if tests are written in TypeScript, typings can also be tested.

I would more than happily do this work myself and submit it as a PR, if this is desired.

**Comment by TylorS** [comment]
Sooo, I went ahead and did this work as I mentioned I would, but for the moment its in a separate repo. All of the same tests are passing, and performance within the vdom-benchmark (100 iterations) are not too far from the current codebase, which is better than I expected to be honest. I had much less faith in the compiled output. I tested the commonjs builds of course, there could be a difference in the ES2015 output since there is less difference between TS and ES6.

![snabbom-ts](https://cloud.githubusercontent.com/assets/6282473/17762009/14153494-64da-11e6-9ace-a8093ec2a2a5.png)

https://github.com/TylorS/snabbdom-ts
https://travis-ci.org/TylorS/snabbdom-ts

**Comment by paldepind** [comment]
I like TypeScript so I think a port is a splendid idea! :+1: 

I think we should just change the API of `thunk` as discussed in #143. Making it compatible with TypeScript is yet another benefit.

If you're interested I can create a branch for the TypeScript port and give you commit access?

Btw, one thing I'd like to get done before porting is merging @katyo's rewrite of the event listeners module. I just need to properly review the PR.

**Comment by TylorS** [comment]
> I think we should just change the API of thunk as discussed in #143. 

Absolutely agree, I would prefer that as well.

> If you're interested I can create a branch for the TypeScript port and give you commit access?

Absolutely! I think that we should discuss the build and release system a bit too when you have a chance to take a look at what I've done in that repo. I took a lot of liberty with it.

> Btw, one thing I'd like to get done before porting is merging @katyo's rewrite of the event listeners module.

Not a problem, I'm not really in a rush, but wanted to use spare time as I could.

**Comment by acstll** [comment]
Awesome initiative @TylorS 

Do you think this could be a good chance to use https://github.com/acstll/parse-sel ? Remember I wanted to make this a separate module? I did that a while ago and use it in `snabbdom-to-html` (of which I just cut a 3.0 beta release, btw).

However, it's plain old commonjs and it depends on this: https://github.com/juliangruber/browser-split . I could try a PR against your repo if that makes sense to you.

:-)

**Comment by AlexGalays** [comment]
Cool work ! Our company won't use javascript again, it's just completely obsolete now that typescript 2.0 is there.
By the way and sorry for the off-topic but what's the deal with maquette insane performances? That doesn't even seem possible (70ms to diff and do 2500 removals ?) Could it remain async somewhere?

**Comment by TylorS** [comment]
@AlexGalays The benchmarks you're probably referring to (from twitter?) are totally false. Maquette gets great performance by failing to do any of the work inside of the vdom-benchmarks. Use [this](https://vdom-benchmark.github.io/vdom-benchmark-maquette/?type=window&id=4&test) link and open up your console. It adds `&test` to the url which enables test mode.

**Comment by AlexGalays** [comment]
While in the process of modifying thunks, why not get rid of `sel` ? (the first thunk argument)
Isn't it always redundant with the `sel` of the thunk child ? The first thunk copying occurs within an `init` hook so the HTMLElement would not have been created yet, so we can still copy the `sel` at this point.

Another thing, isn't the current documentation lying anyway? The last argument of thunk must be an Array, not a rest params ? (`args` is a single function parameter and is then used like that: `cur.fn.apply(undefined, cur.args)`)

After playing with thunks again recently, I agree it's awkward having to use require() just for snabbdom extras (and for styles!). That said, they could be typed as regular ES6 modules even in their current JS form, by writing a collocated d.ts of the same name for each of these (h, thunk, etc) (typescript would then use node module resolution style). Maybe a solution worth thinking about if you want to keep a tight grip on performances?

**Comment by masaeedu** [comment]
While this is still underway, are there any type definition files out there for people using snabbdom from TypeScript code?

**Comment by mightyiam** [comment]
I think this can be closed.
