### ISSUE TITLE
Hero animations break slightly after scrolling

### ISSUE THREAD

**Issue by Widdershin** [snabbdom/snabbdom#152]
Hi! I've been using hero animations recently, and they're fantastic, but I noticed a bug. If you scroll the page, the hero animation isn't quite right.

[Click for higher quality: ![image](https://thumbs.gfycat.com/PalatableThinAndalusianhorse-size_restricted.gif)](https://gfycat.com/PalatableThinAndalusianhorse).

And here is the [Webpackbin I used to produce the above GIF.](http://www.webpackbin.com/EyBNWCbqb)

All I did was take the hero example, add a margin to the top of the container, and then scroll down.

I was able to fix this like so:

``` diff
function post() {
  ...

- oldStyle.top = oldRect.top + 'px'; //start at existing position
+ oldStyle.top = oldRect.top + window.scrollY + 'px'; //start at existing position
  oldStyle.left = oldRect.left + 'px';
  oldStyle.width = oldRect.width + 'px'; //Needed for elements who were sized relative to their parents
  oldStyle.height = oldRect.height + 'px'; //Needed for elements who were sized relative to their parents
}

```

However that solution feels overly naive to me, and I'm unsure if it really fixes the problem or just masks it.

**Comment by paldepind** [comment]
Hello @Widdershin. Thank you very much for reporting this issue and proposing a solution.

How did the fix work for you?

I'm wondering what would happen if the `oldRect` is created when the page is scrolled, and the page is then scrolled to a different location. If that makes sense.

**Comment by jvanbruegge** [comment]
The hero module was removed in v3

**Comment by kuraga** [comment]
> The hero module was removed in v3

But it has been moved to examples.
