### ISSUE TITLE
Create element without patching

### ISSUE THREAD

**Issue by codeclown** [snabbdom/snabbdom#156]
Is there an exposed method to create an element from a virtual node definition, without "patching", i.e. not mounting it to DOM? I know creating a temporary element would probably work but it feels cumbersome since all I want is the generated element.

Desired:

```js
const node = h('div', 'Foobar');
const element = patch.createElement(node);
// element instanceof DOMElement
```

What probably works right now (haven't tested but should):

```js
const node = h('div', 'Foobar');
const temporary = document.createElement('div');
patch(temporary, node);
const element = temporary.childNodes[0];
temporary.removeChild(element);
// element instanceof DOMElement
```

**Comment by acstll** [comment]
I believe there's no such method, but as you suggest, this works:

```js
var vnode = patch(document.createElement('div'), h('div', 'Foobar'))
vnode.elm // <-- there's the DOM element you want
```

With that in mind you could maybe create a helper to do that

```js
function createElement (vnode) {
  return patch(document.createElement('div'), vnode).elm
}
```
