### ISSUE TITLE
is.primitive should check for all primitive values

### ISSUE THREAD

**Issue by Hypnosphi** [snabbdom/snabbdom#162]
Now it checks for string and number only, which leads to unnecessary errors when null value is passed. Alternatively, one might check b for being an object, and set data to b only in that case
https://github.com/paldepind/snabbdom/blob/master/h.js#L22

**Comment by kuraga** [comment]
Still buggy?

**Comment by mightyiam** [comment]
It seems that this is fixed in https://github.com/snabbdom/snabbdom/commit/7ff8d13b4e5a037ac3a43519e746db26dc2c0173#diff-fecfa4a97c0ff7750b8c1e1549f7f3faR70-R75.
