### ISSUE TITLE
What's the difference between props and attributes?

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#169]
Is it dom concept I'm not aware of?

**Comment by Hypnosphi** [comment]
Attribute is something you can see in html, like href in `<a href="/"></a>`. Property is something you can access only via DOM API, like
```js
const a = document.querySelector(a);
const property = a.href; // full url of your site
```

Some properties are linked to corresponding attributes. For example, if you do `a.href = '/'`, it will change the link's href property. Or if you do `input.checked = false` on an input of type "check", it will uncheck it and remove the 'checked' attribute. Note that if you set 'checked' attribute to false instead (`input.setAttribute('checked', false)`), it will not do any unchecking, input will just have 'checked="false"' attribute. Generally, props have more predictable behaviour, so I prefer using them.

**Comment by amirouche** [comment]
Thanks!
