### ISSUE TITLE
Build output for code sharing with online playground sites.

### ISSUE THREAD

**Issue by ismail-codar** [snabbdom/snabbdom#17]
Sometimes we want to code sharing with community on the online playground sites ( http://codepen.io/, http://jsbin.com/, http://jsfiddle.net/ etc ) Sorry npm and browserify suported http://requirebin.com/ is buggy.

Github does not allow driectly reference script files on the online playground sites but rawgit.com  possible with the help.

For example I can use virtual-dom release output https://github.com/Matt-Esch/virtual-dom/blob/master/dist/virtual-dom.js  as https://rawgit.com/Matt-Esch/virtual-dom/master/dist/virtual-dom.js

So we can use snabbdom browserify outputs  with helping rawgit.com on the online playground sites referencing similiar to https://github.com/paldepind/snabbdom/blob/master/build/snabbdom.with.all.modules.js.

**Comment by ismail-codar** [comment]
I made my own solution on my fork. dist/snappdom.js generated by browserify and working with following trick.
```javascript
         $.get("https://rawgit.com/ismail-codar/snabbdom/master/dist/snappdom.js", function (code) {
                snabbdom = eval(code)(2);
                patch = snabbdom.patch;
                h = snabbdom.h;
                vnode = patch(document.getElementById('container'), view());
                render();
            });
```

Example: http://plnkr.co/edit/qeRGxWDy5uyo1Us7HGYl?p=preview

**Comment by paldepind** [comment]
What doesn't work with requirebin?

**Comment by ismail-codar** [comment]
Much too.. You can test here: http://requirebin.com/?gist=0eabd9cd894610cd8311 css and js files not working on the head tab and code changes / run code action does not affect but sometimes affect :) 
Did I wonder if I'm using it wrong?
