### ISSUE TITLE
Snabbdom logo

### ISSUE THREAD

**Issue by grimalschi** [snabbdom/snabbdom#172]
Hi!

What do you think about this logo?

![logo](https://cloud.githubusercontent.com/assets/9027592/19021339/70fd9706-88bf-11e6-9f43-ce352db9d35d.png)

You can read "S" and "<>".

**Comment by paldepind** [comment]
I think it looks very cool and stylish. I like how sleek and simple it looks. Definitely something I'd have no problem in adopting as a logo!

The idea with an "S"  and "<>"  is very clever :smile: Maybe it whould be even better if it was easiers to see the brackets? I can't think of how, but I wouldn't have realized that they where there had I not known.

Very good job!

**Comment by grimalschi** [comment]
I found something very interesting!

I tries to play with "S" and brackets and i got this:

![logo 2](https://cloud.githubusercontent.com/assets/9027592/19024161/e93b3316-88fd-11e6-97a1-0484e6921c49.png)

We can try different fonts and colors.

![logos](https://cloud.githubusercontent.com/assets/9027592/19024191/8c2e76b4-88fe-11e6-9a84-43d4e2c73b35.png)

There is "s", brackets, brilliant and event superman logo!

**Comment by Hypnosphi** [comment]
Why angle brackets? JSX?

**Comment by grimalschi** [comment]
<html>

**Comment by Hypnosphi** [comment]
But snabbdom doesn't use html, it works with dom api

**Comment by grimalschi** [comment]
Thats true, but dom has no symbol to use it.

**Comment by grimalschi** [comment]
One more:

![logo 3](https://cloud.githubusercontent.com/assets/9027592/19030544/dfb42e8c-894e-11e6-955f-75bbf594e1dc.png)

**Comment by grimalschi** [comment]
![logo 3_1](https://cloud.githubusercontent.com/assets/9027592/19033390/67e669fa-895e-11e6-9871-eeee565aca09.png)

Perfect, no?

**Comment by amirouche** [comment]
I prefer the first logo.

**Comment by acstll** [comment]
I got something in the works, please wait a couple of days before you make a choice! 😀

**Comment by acstll** [comment]
So, here it is! (sorry for taking so long).

The idea was this: to have a rounded shape being cut by a diagonal resemble an `S`.

The goals were: to be very simple (no complicated, or too many elements, etc.) and to speak for the library's own goals: simplicity, modularity… I think the two resulting shapes can evoke modularity (two pieces that fit together) and also a cycle (a virtual DOM feeding a real DOM and viceversa, for example).

I like it in (almost) black:

![Black](http://acstll.musca.uberspace.de/ruleta/snabbdom/snabbdom-logo-black.png)

Purple is also an option (but other colors are possible):

![Purple](http://acstll.musca.uberspace.de/ruleta/snabbdom/snabbdom-logo-purple.png)

Here's a screenshot of the first straight version with guides (a friend of mine, who happens to be also a great graphic designer, suggested to have two edges more rounded so the `S` was clearer).

![Guides](http://acstll.musca.uberspace.de/ruleta/snabbdom/snabbdom-logo-purple-screenshot.png)

And here's a possible aplication with text (not final, just testing):

![snabbdom](http://acstll.musca.uberspace.de/ruleta/snabbdom/snabbdom-logo-text.png)

What do you think?

**Comment by grimalschi** [comment]
Some new ideas
![new logo](https://cloud.githubusercontent.com/assets/9027592/19354839/71ca5e10-9168-11e6-8de3-327d5c872273.png)

Also combined "S" and "<>"

**Comment by grimalschi** [comment]
With colors and text.

![new logo 2](https://cloud.githubusercontent.com/assets/9027592/19355130/87a80ef2-9169-11e6-8d24-ffa3a122141b.png)

**Comment by grimalschi** [comment]
Here you can see flow controlled by brackets.

![flow](https://cloud.githubusercontent.com/assets/9027592/19358757/689e2f4c-9177-11e6-8def-464d41a12003.png)

**Comment by grimalschi** [comment]
And one more, for fun.
![pix](https://cloud.githubusercontent.com/assets/9027592/19359741/cb62f258-917b-11e6-8926-01a03ce98199.png)

**Comment by grimalschi** [comment]
I also like this idea.
![new](https://cloud.githubusercontent.com/assets/9027592/19410743/c36bed6a-92f3-11e6-9009-4b0746bb6966.png)

Here you can see again brackets and white "S" between them.

**Comment by trbrc** [comment]
There are some important questions missing from this thread:

What is the philosophy of Snabbdom? How does Snabbdom want to be seen? What sets Snabbdom apart from other virtual DOM implementations? Who is a typical Snabbdom user, and how would they recognize that Snabbdom is for them? Does Snabbdom come with a set of ideas about "the right way" to use it, or does it want to be a flexible thing that you can use in a many different ways? Is it a simple thing that tries to avoid complexity, or is it a sophisticated solution to a very difficult problem? What are Snabbdom's long term goals - does it want to be a big player in the frontend ecosystem that a lot of people rely on and have opinions about, or does it want to move fast and be nimble and break things? Is it enterprise, professional, hipster, hacker, or mostly an experiment?

There is no way to come up with appropriate branding without considering these questions. I think some answers are fairly obvious, but so far only @acstll has presented a design accompanied with a rationale for how it might support those answers.

Then there are additional considerations for the design of the mark itself:

Does Snabbdom even need a logo, or are there other ways to recognize it? Should it be a wordmark or a symbol? How should the logo be used, in what context does it need to be recognizable? What does having a logo say about the library? What does having a poorly chosen logo say?

**Comment by donaldpipowitch** [comment]
I really like this one: https://cloud.githubusercontent.com/assets/9027592/19033390/67e669fa-895e-11e6-9871-eeee565aca09.png

Good job.

**Comment by julienetie** [comment]
Snabb means fast right? Most of the proposed logos are a stone throw away from being a thunderbolt. If someone could make it a thunderbolt style S, it may be boring but it would be relative.

**Comment by paldepind** [comment]
Good points @trbrc. A _great_ logo is not just a neat looking thing—it also has meaning.

I think the S-shape by @acstll is really sleek. It's very simple yet unique. I find is mesmerizing how it looks like an S without really being and S.

I also think the diamond shaped logo stands out as a great idea. The brackets representing HTML/DOM makes a lot of sense and the shape achieved by putting them together with the S is cool.

To me the most important aspect of Snabbdom is simplicity. It is from simplicity that is gets both its performance and its flexibility.

**Comment by marcusnielsen** [comment]
I liked the first one, even though it looks a bit like visual studio code's logo.

**Comment by grimalschi** [comment]
One new idea

![v1](https://cloud.githubusercontent.com/assets/9027592/20488648/7c8e6320-b010-11e6-8543-b39afacda7ae.png)

**Comment by grimalschi** [comment]
And more futuristic variants

![v2](https://cloud.githubusercontent.com/assets/9027592/20488701/ad168888-b010-11e6-87df-d5a9cc92ada7.png)

**Comment by grimalschi** [comment]
And one more for today
![v3](https://cloud.githubusercontent.com/assets/9027592/20499181/fa75bb44-b038-11e6-885e-f6cba57600d0.png)

**Comment by avesus** [comment]
@grimalschi please consider the similarity to the TopTal logo. I'm not sure that that's a great idea. It should be something fast flying, and super small and clear.

**Comment by grimalschi** [comment]
Any ideas?

**Comment by mightyiam** [comment]
Is this Swedish word the origin of snabbdom?
https://en.wiktionary.org/wiki/snabb

**Comment by julienetie** [comment]
@grimalschi IMO the horizontal one is pleasing on the eye and is the least cliché.

**Comment by grimalschi** [comment]
Violet power

![image](https://cloud.githubusercontent.com/assets/9027592/26009723/bc8d285c-3752-11e7-81db-02c07a443c02.png)

**Comment by paldepind** [comment]
Ok, I've been procrastinating on this decision for far too long.

I think I will create a new issue with a poll similar to how [this poll](https://github.com/ramda/ramda/issues/1958) was done.

I think the poll should include the following options

* https://github.com/snabbdom/snabbdom/issues/172#issuecomment-301139616
* https://github.com/snabbdom/snabbdom/issues/172#issuecomment-262055725
* https://github.com/snabbdom/snabbdom/issues/172#issue-180515642
* https://github.com/snabbdom/snabbdom/issues/172#issuecomment-253574297
* https://github.com/snabbdom/snabbdom/issues/172#issuecomment-252510988

Different variants of the same concept will be one option.

@acstll The links to your logo is dead. Would it be possible for you to reupload your logo?

**Comment by mightyiam** [comment]
How about an answer to my question above regarding the origin of the word?

**Comment by acstll** [comment]
@paldepind fixed. Thank you for pinging me…

**Comment by paldepind** [comment]
@mightyiam 

Sorry. Yes, you are right. The "snabb" in Snabbdom is the Swedish word. I'm a dane a not a swede. But I do like the Swedish language. I think "snabb" is a funny word. It's pronounced similarly to the English word "snap" and has a meaning that is somewhat related. The swedes have a lot of words like that. They sound similar to something from English or Danish but their meaning is slightly different. I choose the name Snabbdom due to the swedish meaning and since I thought the name sounded good and was unique.

**Comment by grimalschi** [comment]
So lets vote?

**Comment by amirouche** [comment]
+1 for @grimalschi

**Comment by acstll** [comment]
@amirouche haha, there's 4 logos made by @grimalschi 

Why don't you pick only 1, and then we can do a final poll between that one and mine?

That way simple heart and +1 reactions could work for polling, [just like they did in the link](https://github.com/ramda/ramda/issues/1958) provided by @paldepind

**Comment by grimalschi** [comment]
I think we can use only one my logo - violet. This one is the best.

So we can choose between one my logo and one @acstll logo.

**Comment by acstll** [comment]
Found this today: https://github.com/tj/gh-polls

**Comment by mightyiam** [comment]
Closed in #433.
