### ISSUE TITLE
How to do drag'n'drop?

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#177]
Anything special is required to do drag'n'drop? An example would be helpful.

**Comment by amirouche** [comment]
I followed [mozilla doc about drag'n'drop](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_operations) and drag'n'drop doesn't work with my scheme bindings at least...

**Comment by SuperManitu** [comment]
You can look at my cyclejs library, as cycle uses snabbdom for rendering https://github.com/cyclejs-community/cyclejs-sortable
Might help you.

**Comment by amirouche** [comment]
@SuperManitu Thanks for the pointer, it's seems like you do no use the HTML5 drag'n'drop API is that correct?

**Comment by SuperManitu** [comment]
@amirouche
that was a personal decision as I want to be able to style my ghost element and restrict its movement, which is not possible with html5 DnD

In a prior version I tried native dnd which worked just as good.
You just have to use proper event listener overriding the necessairy events

**Comment by amirouche** [comment]
Personal backlog clean-up.
