### ISSUE TITLE
Clarify Differences Between Hooks

### ISSUE THREAD

**Issue by humeeastmain** [snabbdom/snabbdom#181]
I'm confused about the distinction between prepatch, update, postpatch, and post. Could someone please clarify exactly when each of these are triggered? Also, I would suggest adding a practical example (either a code sample or an example scenario that makes it clear why that particular hook should be used) for each of the hooks in the docs.

**Comment by mightyiam** [comment]
Hooks are documented in the readme. It doesn't go as far as examples and when-to-use but I'll still close this issue, if you don't mind.

**Comment by mightyiam** [comment]
And if you @humeeastmain or anyone else is unsure, please let us know here or in a new issue.
