### ISSUE TITLE
Errors in Hooks

### ISSUE THREAD

**Issue by WorldMaker** [snabbdom/snabbdom#183]
An error thrown in a `postpatch` hook was causing snabbdom patch to stop working altogether but wasn't emitting an error to the console and this took some debugging effort to narrow it down to the specific hook that was erroring. More resiliency when errors are thrown in hooks, or at least logging such errors to the console would be appreciated.

**Comment by kuraga** [comment]
:+1:

**Comment by mightyiam** [comment]
I'm confused. [I don't see a single try-catch](https://github.com/snabbdom/snabbdom/blob/0881343e01911416c8e39a5dae665089643e1357/src/snabbdom.ts).

So there's no way errors are caught and swallowed, right?

I'm closing this for cleanup, but if you feel I'm wrong on this, please comment.

**Comment by WorldMaker** [comment]
My problem was that there weren’t try/catch around hooks and I thought there should be. Things felt swallowed because of the outer framework I was using at the time, but that wasn’t an exact way to put that. The more important problem was that it would crash the rest of a patch.

I moved away from snabbdom in my projects, so it’s not a problem I have today, though.

Sent from my wireless telegraph. Full stop.
________________________________

**Comment by mightyiam** [comment]
Thank you for the clarification, @WorldMaker.

For the record of this issue, I feel that snabbdom should be kept simple in expecting hooks to not throw. If anyone disagrees, here would be a good place to comment.
