### ISSUE TITLE
[Question] selector=svg check is weird

### ISSUE THREAD

**Issue by bogas04** [snabbdom/snabbdom#192]
https://github.com/snabbdom/snabbdom/blob/master/h.js#L30

```javascript
  if (sel[0] === 's' && sel[1] === 'v' && sel[2] === 'g') {
    addNS(data, children, sel);
}
```

Why would you do that ? Perf benefits?

**Comment by paldepind** [comment]
How would you do it? :smile: 

I wrote this reply in [another thread](https://github.com/snabbdom/snabbdom/pull/213):

> I don't think it matters. But I like the current code. It's simple, takes constant time and bails out early. `indexOf` would always scan the entire selector looking for `"svg"` and therefore take time proportional to the length of the selector string.

**Comment by mightyiam** [comment]
```js
if (sel.slice(0, 3) === 'svg') {
}
```

**Comment by Hypnosphi** [comment]
if (/^svg/.match(sel))

**Comment by Hypnosphi** [comment]
direct char comparison is faster anyway (https://jsperf.com/string-startswith), but it would be nice to abstract it into a helper function to make this part of code cleaner

**Comment by bogas04** [comment]
How about using [startsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) ?

**Comment by paldepind** [comment]
Using `String#slice` has the disadvantage that it creates a new string. A regex is slightly more complex IMO. `startsWith` is nice but it is not supported in all the browsers that Snabbdom otherwise work in.

**Comment by staltz** [comment]
In general, it's ok for a library like snabbdom which focuses on size and speed to hurt code readability here and there. I'm 👍  for the char comparisons.

**Comment by nunocastromartins** [comment]
The only issue I see with the current solution is that there can't exist another tag that starts with `svg` without the element getting the SVG namespace. This means that I cannot create a custom element named `svgx`; and that, in the unlikely future where a new tag with such a name is introduced in HTML, this will be broken.

I'd maybe go with something like:
```js
if (sel[0] === 's' && sel[1] === 'v' && sel[2] === 'g' &&
    (sel.length === 3 || sel[3] === '#' || sel[3] === '.')) {
    addNS(data, children, sel);
}
```

**Comment by paldepind** [comment]
@nunocastromartins That has been fixed by #213 and is included in the latest release.

**Comment by nunocastromartins** [comment]
You're right, I didn't see it, sorry! :-)

**Comment by 865881900** [comment]
I read this and had a similar question until I found the answer! The author is great

**Comment by 865881900** [comment]
I would like to ask if the single string in JS does not need to be created, but is always there?
