### ISSUE TITLE
Ideas for a future release

### ISSUE THREAD

**Issue by acstll** [snabbdom/snabbdom#194]
Now that https://github.com/snabbdom/snabbdom/pull/193 is happeing, I'd like to share some ideas I've had for some time. Ideally we will need separate issues opened for any of this points (in case you found any interesting or worth discussing):

- bump 1.0 and follow semver
- add a default `patch` function to the main export https://github.com/snabbdom/snabbdom/pull/193#issuecomment-260356995
- extract `modules/hero`,  `modules/dataset` and `helpers/attachto` to its own packages (or somewhere visibly "extra")
- move `htmldomapi.ts` to `api/dom.ts` (`html` is redundant and an api/ folder will make it cleaner to add other APIs)
- rename built-in modules ~`eventlisteners`~ to `events` (clearer and more readable) and ~`class`~ to `classList` of `classNames` (to avoid problems with the reserved `class` keyword) (this is purely aesthetics)

**Comment by TylorS** [comment]
> bump 1.0 and follow semver

I'm definitely all for this

> add a default patch function to the main export #193 (comment)

I don't really have an opinion on this, as long as we provide es2015 builds for tree-shaking it away :)

> extract ... in its own packages

I don't have issue with this really, but another possible solution is to export them all. One clean way would be to namespace it.

```js
// index.ts
import * as props from './modules/props'
import * as attrs from './modules/attrs'
export const modules = { props, attrs, ... }

// usage
import { init, modules } from 'snabbdom'

const patch = init([
  modules.props,
  modules.attrs,
])
```

> move htmldomapi.ts to api/dom.ts

:+1: 

> rename built-in modules 

:+1: I never use the events module, but I'm definitely in favor of renaming the class module. I've used `classList` and `classes` in the past with some of my experiments.

**Comment by staltz** [comment]
> bump 1.0 and follow semver

Yes please. And if we do that, let's do it `1.0.0-rc.1` first, to iron out the transition smoothly.

**Comment by grimalschi** [comment]
> rename built-in modules eventlisteners to events (clearer and more readable) and class to classList of classNames (to avoid problems with the reserved class keyword) (this is purely aesthetics)

In my project I have 2 different modules - class_list and class_bool.

So I can use it like this:

```
                class_list: [
                    'valign-' + data.settings.vals.valign,
                    'paddings-' + data.settings.vals.paddings + 'px',
                ],
                class_bool: {
                    'xs-wrap': data.settings.vals.wrap,
                },
```

It is very useful sometimes.

In snabbdom we can at least make "class" module be able to work with objects and arrays.

This is my proposition.

**Comment by grimalschi** [comment]
We can use classes name for class module.

**Comment by dmitriz** [comment]
Folks,

From user's perspective I'd like to request 
to be very careful with any breaking changes. 
If there are few lines of code to preserve the old functionality,
that would really benefit regular users and they will thank you for that.

When I naively copied and tried simple looking readme example,
it took me 30 min to understand the useless cryptic errors:
https://github.com/snabbdom/snabbdom/issues/199

People seeing their builds suddenly breaking and generating errors
will not always have time to complain, ask for help, write issues.
Or trying some old tutorial and getting unreasonable errors,
they will abandon it right away.

They may just regard it is broken piece of software,
of which the web is full sadly, 
and move on to the next package,
or maybe even investing their time in creating their own, 
inferior but more reliable solution for what they need.
And possibly regret that decision later, 
loosing even more time, keeping everyone at loss ;(

**Comment by dmitriz** [comment]
I have decided to remove my comment as it may come across too negative which was not intended as I have great respect for your work.

**Comment by krainboltgreene** [comment]
It's been quite a while, can we get this done? https://github.com/snabbdom/snabbdom/issues/194#issuecomment-261267630

**Comment by mightyiam** [comment]
> - bump 1.0 and follow semver

https://github.com/snabbdom/snabbdom/milestone/1

> - add a default `patch` function to the main export https://github.com/snabbdom/snabbdom/pull/193#issuecomment-260356995

#518 

> - extract `modules/hero`,  `modules/dataset` and `helpers/attachto` to its own packages (or somewhere visibly "extra")

#517, #519.

Regarding other modules: while they could use better naming and/or documentation (for example, the style module could be named inline-style), I feel they are simple and non-opinionated enough for inclusion in snabbdom proper. So, I'm going to leave it at that and if anyone disagrees — and if you feel strongly about it please do — open a new issue.

> - move `htmldomapi.ts` to `api/dom.ts` (`html` is redundant and an api/ folder will make it cleaner to add other APIs)

Since this is private API, let's get to it when we actually get to it.

> - rename built-in modules ~`eventlisteners`~ to `events` (clearer and more readable) and ~`class`~ to `classList` of `classNames` (to avoid problems with the reserved `class` keyword) (this is purely aesthetics)

#520, #521.

---

Closing in favor of individual resolutions or issues.
