### ISSUE TITLE
BUG: Unable to create plain text nodes

### ISSUE THREAD

**Issue by anthonybennett** [snabbdom/snabbdom#198]
If I pass in an undefined "sel", this line blows up, even though everything after that seems to work fine.

https://github.com/snabbdom/snabbdom/blob/master/src/h.ts#L35

**Comment by mightyiam** [comment]
According to issue creation date, you were looking at
https://github.com/snabbdom/snabbdom/blob/091dc5f96154ebde238bfecd7adcd8d6809cae0d/src/h.ts#L35-L37

And it seems like to this day an undefined first argument to `h` is not supported:
https://github.com/snabbdom/snabbdom/blob/aac0233b1ff616ffbb47d06c39505fad0ec50476/src/h.ts#L20-L49

So I'm going to close this as unsupported. Text nodes can be created as children of elements using `h` or using `vnode` in this way:
https://github.com/snabbdom/snabbdom/blob/aac0233b1ff616ffbb47d06c39505fad0ec50476/src/h.ts#L37-L41

Or manually:
https://github.com/snabbdom/snabbdom/blob/aac0233b1ff616ffbb47d06c39505fad0ec50476/src/vnode.ts#L13-L20

Seems like it's something like `{ text: 'foo' }` and that's it.
