### ISSUE TITLE
`var h = require('snabbdom/h').default` generates error

### ISSUE THREAD

**Issue by dmitriz** [snabbdom/snabbdom#199]
It seems that 
`var h = require('snabbdom/h').default` 
does not work with current version.
I got it working by removing `.default`.
Perhaps the Readme and examples need to be updated?

**Comment by TylorS** [comment]
Currently the documentation reflects the source code that resides in `master`, but does not reflect the latest release to NPM, this is an error on our end in updating the documentation too soon. 

Thanks for pointing this out!

**Comment by dmitriz** [comment]
So the new syntax is with `.default`? 
Will the older lighter syntax remain supported?

Imo, it should be mentioned explicitly in the Readme that older versions did not use `default`, otherwise people will get a lot of headaches tracking the errors they never previously had.

Also having 4 requires inside `init` is where I saw the error first and had no clue where it came from.

Would it perhaps be possible to have a simpler single module init?

**Comment by TylorS** [comment]
> So the new syntax is with .default?

Yes, this is correct.

> Will the older lighter syntax remain supported?

This still remains to be seen, you can follow the conversation on this in #194, your feedback and experiences would be very welcomed.

> Would it perhaps be possible to have a simpler single module init?

Also being decided in #194 :smile:

**Comment by paldepind** [comment]
After the latest release the documentation and code on npm should again be in sync.
