### ISSUE TITLE
Add jsnext:main and module to package.json

### ISSUE THREAD

**Issue by Rembane** [snabbdom/snabbdom#200]
With a jsnext:main and module in package.json, snabbdom works much better together with packaging tools such as Rollup and Webpack. And you get glorious tree shaking as a bonus.

More info: https://github.com/rollup/rollup/wiki/jsnext:main

EDIT: The most important part! I can add a jsnext:main and modules to package.json and make a pull request.

**Comment by mightyiam** [comment]
Closing in favor of #516.
