### ISSUE TITLE
Version and publish the TS rewrite

### ISSUE THREAD

**Issue by AlexGalays** [snabbdom/snabbdom#204]
The last version of snabbdom was published 2 months ago.

It would be good to have the current master published to npm so that we can do things like `import vnode from 'snabbdom/vnode'` for instance. The package.json probably need updating (main)

**Comment by mightyiam** [comment]
Also be nice if it compiled for everyone.
https://gitter.im/paldepind/snabbdom?at=5850495e7a58ca60554a9c93
I would like to [contribute](https://github.com/snabbdom/snabbdom/issues/141#issuecomment-266839928).

**Comment by AlexGalays** [comment]
Fixing the tsc compilation error is easy; but I think only @paldepind  can publish?

**Comment by staltz** [comment]
@paldepind Could you add `cycle` here? https://www.npmjs.com/package/snabbdom/access

**Comment by AlexGalays** [comment]
I wouldn't mind contributor rights too

**Comment by paldepind** [comment]
I've added "cycle" as a contributor to npm. What is your username on npm AlexGalays?

#212 fixes the compile issues.

Are there anything else we should get fixed before doing a release?

**Comment by AlexGalays** [comment]
My username is "boubiyeah".

**Comment by paldepind** [comment]
I've added you :smile:

**Comment by staltz** [comment]
Issue seems done. Thanks !
