### ISSUE TITLE
for attribute not working

### ISSUE THREAD

**Issue by julienetie** [snabbdom/snabbdom#206]
I can't seem to get: 
```javascript
h('label', {
            attrs: {
                for: 'test'
            }
        },
['test']);
```
to work. I've tried using _props_ as well. 
The text node is rendered but not the for attribute.

**Comment by acstll** [comment]
Is everything else working as expected?

Are you including all the needed modules in the `init` call?

```js
var patch = snabbdom.init([
  require('snabbdom/modules/attributes'),
  require('snabbdom/modules/props')
])
```

I just tested your code (in requirebin.com) and it works ok.

If you're using `props`, remember you need to use the `htmlFor` key:

```js
props: {
  htmlFor: 'test'
}
```

https://developer.mozilla.org/en/docs/Web/API/HTMLLabelElement

**Comment by julienetie** [comment]
htmlFor is just what I needed, thanks for that ;)
