### ISSUE TITLE
Undefined properties on vnodes

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#207]
In tests, I often have deep equality assertions between `actual` and `expected` outputs of `h()`. Failed assertions often mean that I manually look for the differences between the trees. With this in mind, I would suggest a policy where there SHOULD be no undefined properties.

As we can see [here](https://github.com/snabbdom/snabbdom/blob/f552b0e8eda30a84e59f212e98651463ec71a53f/src/vnode.ts#L39-L40), all of the possible properties are declared, even if undefined (last 2 lines of the function):

```js
export function vnode(sel: string,
               data: any | undefined,
               children: Array<VNode | string> | undefined,
               text: string | undefined,
               elm: Element | Text | undefined): VNode {
  let key = data === undefined ? undefined : data.key;
  return {sel: sel, data: data, children: children,
          text: text, elm: elm, key: key};
}
```

1. Is it the way it currently is for performance reasons?
1. Would it be ok to change it to not declare undefined properties?
1. Would other parts of the code accept the non-existence of those properties?

**Comment by developit** [comment]
Declaring the properties means objects remain a consistent shape, allowing monomorphism. Removing them would make any function that accepts the object as an argument polymorphic.

**Comment by mightyiam** [comment]
@developit so we'd be better off improving our inspection tooling, like [this right here](https://github.com/avajs/ava/issues/1155)?

I really don't know what this means in practical terms. I can imagine that a bit more conditional code would be required here are there, but I don't know what the performance impact of it will be. Perhaps ecosystem impact or this is all internal?

When it comes to humans vs. robots, I tend to be on the human's side.

**Comment by developit** [comment]
Most assertion libraries use something close to [this deep equality algorithm](https://github.com/substack/node-deep-equal/blob/master/index.js), originally from Node's `assert` module.  As you can see [here](https://github.com/substack/node-deep-equal/blob/master/index.js#L69-L86), it considers two objects with differing keys to be inequal.  This is brittle, and I've never found it to be of any utility on its own, but that is how most of these libraries work.

Personally I prefer this implementation, though I've only ever used it for shallow equality:

```js
function deepEqual(a, b) {
  // *snip* types other than Object
  for (let i in a) if (b[i]===undefined) return false;
  for (let i in b) if (!deepEqual(a[i], b[i])) return false;
  return true;
}
```

**Comment by mightyiam** [comment]
@developit isn't your implementation more like `isSupersetOf` than `isDeepEqual`?

Anyway, why did you bring this up?

**Comment by developit** [comment]
No, it fails if there are extra properties on either object that are not `undefined`. It's just a standard deep equality check that treats `undefined` the same as a missing key.  Deep equality was the subject of this issue, the AVA PR you linked to, and the cause of the assertion error you described running into in your tests, so I figured it would be relevant to illustrate why the issue occurs and a way around it.

Regarding the implementation question, I'm fairly certain snabbdom declares all possible properties of VNode for the same reason every other performance-minded library does, which is to produce objects of a uniform shape so that functions operating on those objects can be monomorphic.  I thought that seemed like a fairly definitive answer to the question you asked.

**Comment by mightyiam** [comment]
I don't have experience with performance-minded libraries and your explanation sounds credible. Thank you. I'm going to have to invest in good diffing-for-humans tools in the assertions. It looks like AVA will have this covered soon.
