### ISSUE TITLE
Provide default patch function with all modules.

### ISSUE THREAD

**Issue by jbucaran** [snabbdom/snabbdom#209]
If am not mistaken, currently I have to do like so

```js
const patch = snabbdom.init([
    require("snabbdom/modules/class"),
    require("snabbdom/modules/props"),
    require("snabbdom/modules/style"),
    require("snabbdom/modules/attributes"),
    require("snabbdom/modules/eventlisteners")
])
```

in order to get the patch function with all the modules. 

This is rather verbose. What if init just required all modules by default when no arguments are given?

```js
const patch = snabbdom.init()
```

**Comment by mightyiam** [comment]
Or `initWithAll()`...

**Comment by paldepind** [comment]
The reason why it is this way is so people can include the modules they need and create a build with Browserify og Webpack that only includes the relevant modules.

I really like the suggestion from @acstll [here](https://github.com/snabbdom/snabbdom/pull/193#issuecomment-260356995) as it preserves that as well as adding a more convenient option as well.

**Comment by jbucaran** [comment]
@paldepind Okay, I think I agree with acstll too. Do you want to track this somewhere or close?
