### ISSUE TITLE
Creating SVG charts 

### ISSUE THREAD

**Issue by eskhool** [snabbdom/snabbdom#214]
The idea of using snabbdom to create SVG sounds great but to actually create charts a lot of repetitive work should be in a library. Is there one out there using snabbdom that i have missed? If not any suggestions on what to look for if I am looking at forking an existing library (like chartist.js?)

**Comment by aronallen** [comment]
With d3 version 4 you can use most of the math, scale, tick functions, and easily pipe these to functions that return Array<VNode>

I recently build up some primitives in vDOMSON (a vDOM exchange format i am working on) it works pretty well.

**Comment by caesarsol** [comment]
Hello, I'm interested in this topic because I'm thinking about a bridge library between d3 and snabbdom, much more comfortful than the d3.selwct method.

What I did so far supports attribute transitions and d3 scales, it's very pleasant to work with and quite performant, and leads to greater usability.

I'm going to publish it sooner or later, let me know if you're interested!

**Comment by eskhool** [comment]
Definitely interested ..the idea of a bridge library sounds great.

**Comment by jvanbruegge** [comment]
you dont need a bridge, i use cyclejs (built on top of snabbdom) together with d3.js, and it works very good.
Check out my [blog post](https://dev.to/supermanitu/using-cyclejs-to-view-real-time-satellite-test-data) about this topiv

**Comment by caesarsol** [comment]
Yeah, I did not mean an actual bridge, just a snabbdom plugin and a couple of helpers 😃

**Comment by eskhool** [comment]
Actually the bridge that is required is a C3js like front which does all the calculations for drawing various types of charts and then uses snabbdom to generate/manage the virtual dom

**Comment by mightyiam** [comment]
Thank you for the tips. Since I feel this conversation is out-of-scope for this project, I'll close this issue.
