### ISSUE TITLE
Published package (0.6.0) excludes built files

### ISSUE THREAD

**Issue by tdumitrescu** [snabbdom/snabbdom#218]
Since there's no `.npmignore`, NPM defaults to `.gitignore` to decide which files to exclude from the published package. Which right now means that [all the compiled files get excluded](https://github.com/snabbdom/snabbdom/blob/0483640fa3249d21a2f9b644c542374d38714baf/.gitignore#L32-L60).

Can you republish with a separate `.npmignore` like [this one](https://github.com/tdumitrescu/snabbdom/blob/dcecdd9cee16bf91320705ddf05380a3beb4a92c/.npmignore)?

**Comment by paldepind** [comment]
Thanks for letting me know and for the `.npmignore` file. `0.6.1` is out now and actually includes the code :smile:

**Comment by TylorS** [comment]
@paldepind It'd probably good to deprecate 0.6.0 on NPM, to warn users that we messed up. Should be `npm deprecate snabbdom@0.6.0 'Please upgrade to >=0.6.1 as there was a publishing issue.'`, where you can change the message of course.

**Comment by tdumitrescu** [comment]
Thanks for the quick fix! Looks like it's working now. I'll leave this open so you can close after doing the deprecation step.

**Comment by paldepind** [comment]
That's a good idea @TylorS. I've done so.
