### ISSUE TITLE
Vnode equality for testing

### ISSUE THREAD

**Issue by Swizz** [snabbdom/snabbdom#223]
Hi there,

I am on the way to write test about expected Vnode tree. 
So, I want to test equality between the actual Vnode and the expected one.

To be brief : is this code result to true or false ?
```js 
h('div', [h('div', [h('span', 'Hello')])]) === h('div', [h('div', [h('span', 'Hello')])])
```

Am I on the right way to do my test like this ?
```js
test(t => {
  const actual = somethingWhichReturnVnode()

  t.is(actual, h('div', {}, []) )
});
```

Thank you for all your answers.

Cheers,

**Comment by mightyiam** [comment]
That is how I do it.

**Comment by Swizz** [comment]
I noticed it works for simple vnode, but is this true for testing with hooks and events properties ?

**Comment by mightyiam** [comment]
Hooks are just functions on properties. So yes. I'm guessing event properties are the same.

**Comment by Swizz** [comment]
Well !

Thank you for your time :)
