### ISSUE TITLE
Don't manipulate the arguments passed to the h function

### ISSUE THREAD

**Issue by nunocastromartins** [snabbdom/snabbdom#227]
Raised in #226, consider:
```js
let children = [0, 1, 2];
let node = h('div', children);
console.log(children[1]); // What should this print?
```
and:
```js
let data = {};
let svgNode = h('svg', data); // This adds the SVG namespace to `data`
let divNode = h('div', data); // This will have the SVG namespace
```
- In the first example, the `children` array is manipulated and each element of the array is turned into a `VNode`. I don't think the given argument should ever change.
- The second example will add the SVG namespace to the `div` since the `h` function changes the `data` object. Once again, I don't think this should happen.

The problem with the children should be fixed by iterating over them with `.map`; to fix the data problem I'd use `Object.assign` to create a shallow copy of the object.

Is this an actual issue or just something developers should be careful with?

**Comment by acstll** [comment]
This reminded me of that famous bug in Backbone where update events didn't fire because the model object was already being mutated…

Though I've never have any problems with this, I can agree. The only concern I can think of is performance being affected by creating new objects everytime.

**Comment by staltz** [comment]
> Is this an actual issue or just something developers should be careful with?

Something developers should be careful with. I believe snabbdom is meant to be used in particular functional style where this wouldn't be a concern. Avoiding cloning helps with performance, and so far I haven't seen this issue happen in user code.

**Comment by nunocastromartins** [comment]
From the README:
> Snabbdom is a low-level virtual DOM library. It is unopinionated with regards to how you should structure your application.

But still, let's say that you're meant to use it in a functional style, doesn't that mean that passed arguments shouldn't be mutated? At least I'd expect them not to be.

I do get what you mean, though. But I'd say that you're forcing Snabbdom to be used in a particular way, which doesn't seem to be the point of the library.

**Comment by mightyiam** [comment]
I would think the API implies that I shouldn't count on the safety of what I pass to it. But that's just me.

**Comment by staltz** [comment]
> But I'd say that you're forcing Snabbdom

Not forcing, just giving my perspective.

**Comment by paldepind** [comment]
> Something developers should be careful with. I believe snabbdom is meant to be used in particular functional style where this wouldn't be a concern. Avoiding cloning helps with performance, and so far I haven't seen this issue happen in user code.

Yes. I very much agree with this.

If this is a problem maybe using a custom `h` function that clones it's arguments would be a solution? Potentially one could use both the normal `h` and a custom cloning `h` when cloning is desired.

**Comment by nunocastromartins** [comment]
Since most agree that this is intended, I'll close the issue. :-)
Please reopen it if it comes up again.

**Comment by paldepind** [comment]
@nunocastromartins Is using a wrapper around `h` that clones good enough for you?

**Comment by nunocastromartins** [comment]
In my own project I'm already using my own custom `h` for various reasons which really shouldn't bother Snabbdom; so, in my case, I really don't need this to be implemented.

I just brought it up since I'd like to hear your opinion on it: as you might have considered it a bug instead of expected behaviour.

To be fair, I think Snabbdom is already too bloated; I'd benefit from splitting this repository in two, one containing **only** the core patching algorithm (and the `vnode` structure it requires), another with the rest (`h` functions, modules, etc.). If this was implemented I'd consider using the core algorithm repository directly, instead of forking my own. :-)

Do you think this is worth discussing? I can open up a new issue if you do.

**Comment by acstll** [comment]
> …benefit from splitting this repository in two, one containing only the core patching algorithm (and the vnode structure it requires), another with the rest (h functions, modules, etc.).

I can agree with this a lot. I think we could at least discuss it and know what everyone else thinks about this.

I'm not forking but I'm working on a library (maybe I won't even make it public) that uses Snabbdom's core only. It basically is a group of modules (the way I like them, haha) bundled together and exporting a `patch` function.

I think tests would also benefit from the split.

My 2 cents :-)

**Comment by nunocastromartins** [comment]
@acstll Just created an issue to discuss this, maybe copy your input to there? 😃
