### ISSUE TITLE
Split the repository in two

### ISSUE THREAD

**Issue by nunocastromartins** [snabbdom/snabbdom#236]
Brought up in #227, this issue raises the possibility of splitting this repository in two.

In my opinion, Snabbdom is too bloated: my use case requires a custom `h` function; custom modules; and I have no use for thunks. The core patching algorithm (together with the `vnode` representation) is the only part of Snabbdom that I _try_ to keep untouched in my own fork (I made some simplifications).

With this, I would like to propose the splitting of this repository in two repositories: something like `snabbdom-core`, which would mainly contain the core algorithm, possibly with `vnode` (I'd be okay with removing `vnode` from it too); and some other repository, say `snabbdom-utils` or even simply `snabbdom`, containing the `h` function, modules, thunks, DOM API, and anything else that might be useful for the "common" users of the library.

What do you guys think?

**Comment by acstll** [comment]
I like this idea, see my comment here: https://github.com/snabbdom/snabbdom/issues/227#issuecomment-275416178

Thinking of it a bit more, your proposal to me sounds more like "extracting" core than splitting. We could create `snabbdom-core` and then this same `snabbdom` package could consume it. This way one could now use `snabbdom-core` —like in your case—, and everyone else using `snabbdom` could continue to do so as of now.

I'd like to hear what people think would be the benefits of this change, apart from us being able to do `import { init } from 'snabbdom-core'`…

**Comment by TylorS** [comment]
I'd propose using [npm scoped packages](https://docs.npmjs.com/getting-started/scoped-packages) if this is decided upon. Then the name of this "core" could be `@snabbdom/core`. It's a good way to differentiate what are "official" snabbdom packages and which are 3rd party `snabbdom-foo`.

**Comment by acstll** [comment]
> I'd propose using npm scoped packages if this is decided upon. Then the name of this "core" could be `@snabbdom/core`.

Brilliant 💯

**Comment by whmountains** [comment]
If you put the core in a separate package, could you also take the opportunity to have `diff` and `patch` be two separate functions?  It seems like a nice way to make it more "low-level"

I'm not acquainted with the snabbdom core so there are probably some considerations that I'm not aware of.

**Comment by nunocastromartins** [comment]
@whmountains I'm not sure of the impacts of splitting `diff` and `patch`; it seems to me like it would be a whole different algorithm, since right now Snabbdom patches the DOM as it diffs it (only iterating through the structure once). In any case, I believe that that could be done at a later time. On another note: you could also then create a whole new `snabbdom-diff-patch-core`, although that might be over-modularising. 😄

**Comment by TylorS** [comment]
> I'm not sure of the impacts of splitting diff and patch; it seems to me like it would be a whole different algorithm

I'm pretty sure that splitting the diffing and patching in snabbdom is going to lead to more downsides than upsides. Combining the 2 processes, to my best knowledge, has a *lot* to do with the performance that snabbdom achieves. A lot of the hook/module behavior is dependent on knowing a lot of information about the process as a whole, and my own investigation to split the 2 usually lead to trade-offs around the types of vNode/module hooks that are achievable. One thing I've always loved about snabbdom is its modules and the ability to create very cool things using modules. So personally, I'd be very unexcited to see that behavior change.

**Comment by whmountains** [comment]
@nunocastromartins @TylorS Okay that's fine.  Point well taken.  I had actually edited my comment to take out that part but it looks like you all got it via email anyway.

**Comment by staltz** [comment]
I don't understand this proposal. In practice snabbdom is already split. `snabbdom.js` has only `init` and `vnode` (vnode is just 2 or 3 lines of code). `h` is already a separate thing. So are the modules and thunk.

**Comment by nunocastromartins** [comment]
@staltz But when I do `npm install snabbdom` it comes bundled with everything - when I only want the core algorithm. The core algorithm itself is, in my opinion, the selling point of this library: it is a generic approach to updating the DOM where _nothing_ is assumed, not the API to interact with the DOM; not how to update the properties/attributes of an element. Everything else in this repository: the `h` function; the modules; exist to simplify the interaction with the core algorithm but, ultimately, they're nice _defaults_ to interact with the algorithm. I'm not saying they shouldn't exist, just that they should exist in a separate repository: with separate tests and with different concerns.

**Expanding on what I mean by different concerns:**
I believe that the core algorithm should strive to be absolutely generic (so long as performance doesn't suffer), no assumptions made on how the user will use the library; whilst the repository containing the default `h` functions, modules, etc. may make some assumptions that people here already seem to make, e.g. quoting you in regards to a different concern, with which @paldepind agreed:
> I believe snabbdom is meant to be used in particular functional style where this wouldn't be a concern.

**Comment by paldepind** [comment]
I understand where you're coming from @nunocastromartins. The core is definitely more general purpose than some of the modules. But what are the benefits to doing this? `npm install snabbdom-core` will take a bit less disk space than `npm install snabbdom`?

**Comment by acstll** [comment]
Like I said previously I like the idea, but if there are no benefits (other than less disk space since bundle size should be the same) I pretty much agree with @staltz and @paldepind.

**Comment by nunocastromartins** [comment]
I understand your reasoning; simply wanted to bring this up in any case.
It's just that I tend to like to keep things small and focused: when I find that there is extra bloat, I just feel the need to remove it 😄. It's not so much about the disk space but the fact that I'm "importing" to my project things that I know I won't ever need.

Another thing I can't understand when installing this package is the future of the project. Will this project grow? Will more modules be added? Will I get even more files that I have no use for when I update the package in the future? These are the kind of questions I raise before installing a package, and this is why I believe the project would benefit from splitting concerns. Keep the project focused: the core in being as lean, generic, and efficient as possible; the rest in providing a set of tools tailored to be used in a specific style (say, for functional programming). Note that these are two distinct concerns, reason why I believe they should be split into two repositories.

Again, I know that in the end I'm just saving a whole meaningless bytes; but I suppose that my concern is a bit more philosophical. 😀

**Comment by jbucaran** [comment]
@staltz is right, Snabbdom is already split in practice because you can cherry pick what modules you want to include. Don't like thunks? Don't include them in your bundle and you'll be as lean as if they never were in the first place.

I used Snabbdom early sketches to learn how this _virtual dom_ theory works in practice, so I am very grateful to @paldepind for that ❤️

But you (@nunocastromartins) are not the only one who thinks Snabbdom has become bloated. I also think so too, even if it's just from a philosophical point of view.

**Comment by nunocastromartins** [comment]
Correct me if I'm wrong but, if I'm interested in using Snabbdom not as an end-user, i.e. someone who actually builds UIs, but as a package developer who wants to use Snabbdom's core algorithm behind the scenes and someone `npm install`s my package, won't all the Snabbdom files that I have no need for be downloaded by that user (since I have `snabbdom` as a dependency)?

I'm not certain of this (maybe I should only upload a bundle of my project anyway?), but should this be the case, then I'd feel bad for all the extra bloat I just put on anyone using my package. 😄

**Comment by jbucaran** [comment]
@nunocastromartins 

> won't all the Snabbdom files that I have no need for be downloaded by that user (since I have snabbdom as a dependency)?

Yes, but **only** during development. Your users will be likely using a tool such as Browserify to generate a bundle that contains only the parts of Snabbdom you've actually included in your package.

**Comment by staltz** [comment]
Is this really about a few kB of disk space in node_modules of your project? That's not bloat, it's micro-bloat, or nano-bloat. The majority of npm packages have things like these. Inspect other libraries, maybe other libraries may have serious bloat (I recall installing a small library and downloading >500 MB). Not this library. 

I would close this issue and go forward because we're not seeming to get consensus.

**Comment by nunocastromartins** [comment]
> Yes, but only during development.

I'm aware. I understand what all of you have been saying.

> I would close this issue and go forward because we're not seeming to get consensus.

I agree. I'll just close this; reopen it if you feel the need to.

**Comment by jbucaran** [comment]
@nunocastromartins I don't have a strong opinion on this issue. I was trying to help out with your query. That is, while there may be nano-bloat or not in this library, you don't have to worry about users of your package downloading the whole of Snabbdom, since it's just a development time dependency.

I actually feel closing this issue was a bit premature. It's been opened only for two days.

**Comment by kuraga** [comment]
That's not about Kbs... It's about approaches...
