### ISSUE TITLE
Hyperx to Snabbdom

### ISSUE THREAD

**Issue by JorgeBucaran** [snabbdom/snabbdom#243]
I created [hyperx-to-snabbdom](https://www.npmjs.com/package/hyperx-to-snabbdom) a few months ago as an approach to solving substack/hyperx/issues/36 in a non-opinionated manner that could satisfy as many library authors as possible. 

It works for my use case, but I'd be curious to hear your feedback about it.

Cheers and thanks for the awesome work you're doing here.

**Comment by graforlock** [comment]
Have a look at [my fork of your solution](https://github.com/graforlock/hyperx-snabbdom) (i did it like this as you only have a gist) , the original adds space everywhere, and it should probably just in text nodes

**Comment by JorgeBucaran** [comment]
Thanks! @graforlock I'll update my gist and publish a new minor.

**Comment by graforlock** [comment]
It may have more cases like these and needs some testing I believe

**Comment by JorgeBucaran** [comment]
@graforlock I am not really using this anymore, having moved to Hyperapp, but I should really make a repo for this and add tests proper. 😅

**Comment by JorgeBucaran** [comment]
@graforlock [Published 1.1.0](https://gist.github.com/JorgeBucaran/2e3d376d7910ff8ab78185ddfb6744bc). 🎉
