### ISSUE TITLE
Promote derivative works

### ISSUE THREAD

**Issue by Swizz** [snabbdom/snabbdom#248]
Hi there !

A month ago, I worked on a projet called [snabbdom-pragma](https://github.com/Swizz/snabbdom-pragma) for the need to continue the using of snabbdom with jsx despite of my new trip on [Bublé](https://buble.surge.sh/guide).
Because Bublé was transpiling JSX into [`React.createElement`](https://facebook.github.io/react/docs/react-api.html#createelement) by default. I started a work on a sugar which handle the `NotRect.createElement`  api for working with Snabbdom. (like it does by [Inferno](https://github.com/infernojs/inferno/tree/master/packages/inferno-create-element) for example)

I tested my work against multiple snabbdom features (not all of them I guess, but I want to). And I moved from the Bublé target to Babel and Traceur too.

Snabbdom-pragma is a sweet and smart alternative to [Snabbdom-jsx](https://github.com/yelouafi/snabbdom-jsx), handling a lot of its thoughts.

**So, is there  a way to officially promoted derivative works for/of Snabbdom ?**

Cheers,

**Comment by amirouche** [comment]
Look at the end of the README there is [section dedicated to derivative work](https://github.com/snabbdom/snabbdom#structuring-applications)

**Comment by Swizz** [comment]
I am more talking about "Plugins that allows the use of JSX" for example.
Called `Features in modules` in the README.

**Comment by paldepind** [comment]
I think we could split the [Features](https://github.com/snabbdom/snabbdom#features) list into three parts. "Core features", "Module features" and "Third party features". Then both snabbdom-jsx and snabbdom-pragma could be mentioned in the "Third party features" sub-list?
