### ISSUE TITLE
How to force DOM updates from a desynchronized vTree representation?

### ISSUE THREAD

**Issue by brucou** [snabbdom/snabbdom#250]
I encountered a use case where the `vTree`/`vNodes` are desynchronized from the actual DOM. This plays badly with the diffing/update mechanism, as from the `snabbdom` point of view, nothing has changed, while the DOM indeed changed. In this case (which I can detect), I would like to force the DOM to update to reflect the `vTree`, that is unplug the diffing algorithm for that specific `vTree`.

Is there an easy way to do this? 

I tried using `key` as in 

```
    ? {
      key : latestTeamIndex,
      props: {
        value: fieldValue,
        type: 'text',
        required: false,
      }
    }
```

thinking that would be enough for the library to understand that that `vNode` is different from another `vNode` with the same data (hence it should update the DOM instead of doing nothing) but that seems to fail.

**Comment by nunocastromartins** [comment]
Would you please explain in more detail **how** the virtual nodes are getting out of sync with the underlying DOM? Why is that happening? Why are changes to the DOM occurring? I simply want to ascertain that you're using Snabbdom in a _correct_ way.

In any case, it seems to me that you need to force Snabbdom to create a new DOM node to replace the old one; to that end, your new virtual node should have a different key than the previous one, this will effectively tell Snabbdom that the two virtual nodes are indeed different, forcing the previous one to be deleted whilst the new one would be created from scratch.

**Comment by brucou** [comment]
I have a `vTree` which represent a two-step form rendering a model which is initially empty. In the first step, the user fill in the only one input field (that is the DOM modification), then click `Next`, and should see the field for the second step, which is empty. BUT that second-step field is shown with the same input value than previously filled in (in the first step).

This happens because 
- first step displays `vTree1 = f(model, step1)`
- every key press event from the user updates the DOM but not the corresponding `vTree`. That means that in the DOM the first-step field is no longer empty, but in `vTree1` it still is
- the click event leads to displaying a `vTree2 = f(model, step2)`
- in `vTree2` the input field is empty, just as in `vTree1`, hence the diffing leads to no update of the input value, hence the input value on the screen (i.e. in the DOM) does not change

A work-around is to
- listen on key press event and update the `vTree` so it remains in sync with the DOM, hence essentially mirroring DOM state in the vTree at all times

For miscellaneous reasons, I want to avoid that and force the rendering library to update the DOM with `vTree2` as it is.

**Comment by nunocastromartins** [comment]
Okay, I think I understand what you mean. This is expected, it's a side-effect from the way the patching algorithm works.

There is no need to listen to a key press event. If you define the input in `vTree1` with a different key from the input in `vTree2` what you describe shouldn't happen, since the algorithm will know that they are supposed to be two different elements. Would you give it a try?
```js
let inputA = h('input', {key: 'a'})
let inputB = h('input', {key: 'b'})
patch(inputA, inputB) // The input value should be gone in input B
```
It should also work by using different classes or ids to distinguish both inputs (if defined in the `sel` of the virtual node).
```js
let inputA = h('input.a')
let inputB = h('input.b')
patch(inputA, inputB) // The input value should be gone in input B
```

**Comment by brucou** [comment]
Thanks Nuno for the help, that indeed works in isolation. I am closing this.
