### ISSUE TITLE
Blank rendering when sel is empty string ''

### ISSUE THREAD

**Issue by staltz** [snabbdom/snabbdom#251]
See this issue https://github.com/cyclejs/cyclejs/issues/531 for more details

**Comment by jvanbruegge** [comment]
Not only when empty, but also if it's just the tag name

**Comment by staltz** [comment]
Sorry, this actually is only related to Cycle's hyperscript-helpers, not with snabbdom's hyperscript. When using `h('div', {}, [...])`, snabbdom works just fine.
