### ISSUE TITLE
ToVNode incorrectly handles text nodes

### ISSUE THREAD

**Issue by Steelfish** [snabbdom/snabbdom#252]
Currently ToVNode creates text nodes for an element by returning a vnode with undefined for everything with text. This causes the following type error to be thrown when snabbdom tries to update the DOM by removing the nodes. 

```
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
 at Object.removeChild (htmldomapi.js:18)
 at removeVnodes (snabbdom.js:153) 
 at updateChildren (snabbdom.js:233) 
 at patchVnode (snabbdom.js:256) 
 at patch (snabbdom.js:28)
```

This is the cause for https://github.com/cyclejs/cyclejs/issues/531

Creating the vnode with (undefined, undefined, undefined, text, node) ensures that snabbdom is properly able to remove the nodes.

**Comment by staltz** [comment]
Fix will be released in v0.6.5
