### ISSUE TITLE
Boolean attributes should not have a value

### ISSUE THREAD

**Issue by PerWiklander** [snabbdom/snabbdom#254]
The current boolean attribute handling feels only half done. The attributes are added and removed in a correct way (depending on if the value is truthy or not), but they shouldn't have values set.

I suggest that values set on [boolean attributes](https://github.com/snabbdom/snabbdom/blob/master/src/modules/attributes.ts#L8) should only be used to determine if the attribute is rendered or not and not added as value of the attribute.

According to http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes

"A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute’s canonical name, with no leading or trailing white space.

NOTE
The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether."

**Comment by mightyiam** [comment]
Sounds correct. Similar to the class module, isn't it?

**Comment by mightyiam** [comment]
But the API isn't clear to me. Example?

**Comment by PerWiklander** [comment]
The suggested new API would given `hidden = true` output only `hidden`. Given `hidden = false` it would remove a previous attribute with the name `hidden` (this works today).

Today, from what I can see, a value of `hidden = "whatever"` would output `hidden = "whatever"` in the dom.

**Comment by caridy** [comment]
I favor this request as well. Setting the value to empty string for boolean attributes should be enough, we can effectively ignore the provided value. More details here: https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attributes

**Comment by PerWiklander** [comment]
Yeah, that is the same spec as I referred to above.

**Comment by paldepind** [comment]
Thank you for reporting this issue @PerWiklander :smile: Please take a look at #255. It should fix the problem. If it looks good to you I will merge and do a patch release.

**Comment by PerWiklander** [comment]
The implementation looks good to me, except the fact that having a `const booleanAttrs` is not very future proof.

**Comment by PerWiklander** [comment]
It looks like it is missing `buffered` and `contenteditable` already.
Wouldn't it work if it checks if the attribute value is strictly `true` or `false`? Attributes that might look like they are boolean, like `aria-atomic` should actually have the `string` value `"true"` or `"false"`, so they would (correctly) not be affected.

**Comment by paldepind** [comment]
That may be a good idea. But, wouldn't it be annoying if users had to convert `true` to `"true"` when setting `aria-atomic`, etc? But if these are uncommon it would probably be worth it as it would make the boolean attributes implementation both simpler and faster.

**Comment by fix-fix** [comment]
@PerWiklander 
> Wouldn't it work if it checks if the attribute value is strictly true or false? 

1. That behaviour will require explicit boolean conversion with `!!` or `Boolean`
2. Because anything can be passed as an attribute, now there are three outcomes, because you have to handle values that are neither `true` nor `false`, and it's not obvious which is the default one

**Comment by paldepind** [comment]
@fix-fix 

Instead of using `!!` or `Boolean` we could just check `cur === true` and `cur === false`.

**Comment by PerWiklander** [comment]
Aria is a little particular in the way it does not work like the normal boolean attributes. One example is that is it has both what looks like normal boolean values (with the string values "true" and "false") but also a tristate. ` aria-checked` for example has the possible values of "false" (default), "true" and "mixed". Setting `aria-checked` to `Boolean true` would not give need output anyway. Unless a `Boolean true` is converted to `String "true"` .

**Comment by PerWiklander** [comment]
Checking for `cur === true` and `cur === false` was exactly what I was looking for. Someone setting an attribute to one of those two should know what they are doing. Any other value, be it int, string or whatever, should just end up in the dom.

**Comment by fix-fix** [comment]
@paldepind I was saying about usage of boolean attrs, so in that case it would require the following:

instead of:
```
h('button', {attrs: {disabled: errorsAmount || someCheckPending}}, 'Continue')
```

**Comment by fix-fix** [comment]
@PerWiklander these aria-* attributes are not defined as boolean attributes, so it doesn't make sense to add special logic for them.

Perhaps it's better suited for some other library that validates possible string values for attributes against the spec.

**Comment by PerWiklander** [comment]
My argument was to not treat those with special logic. I was arguing that they are strict string attributes, and it would never be normal behaviour to set them as `aria-checked = true` anyway. So we can have `selected = true` reserved for actual Boolean attributes.

**Comment by PerWiklander** [comment]
Regarding problems at the call site:

In the above example, if the logic demands that the thing is disabled when there are errors OR the check is pending, it would be better expressed as:

(given that `errorsAmount` is an int and `someCheckPending` is a boolean)

`h('button', {attrs: {disabled: errorsAmount > 0 || someCheckPending}}, 'Continue')`

Being lazy about type coercion is often not the most clear way to express the logic anyway.

**Comment by PerWiklander** [comment]
So I vote for a "reopen" at the moment and some more consideration. Otherwise there will at least be issues of "missing boolean arguments" reported from time to time. Starting with `buffered` and `contenteditable`.

**Comment by paldepind** [comment]
I really like your idea @PerWiklander. It would also make the optimizations we're discussing in #230 unnecessary. Not having to maintain a list of boolean attributes and check them at runtime is a huge benefit. All in all the code would both be significantly simpler and faster.

My only concern is the problem that @fix-fix describes. For me personally, it is a non-issue as I always try to avoid coercion and only use `&&` and `||` on values that are actually booleans. But nevertheless doing this would be a breaking change as we're currently "coercion-friendly".

I'd like to hear more opinions before we do anything.

**Comment by yelouafi** [comment]
Hi @paldepind. Jumping here as I was the original author of the attributes module. When I added the list of  boolean attributes the issue of future maintenance crossed my mind but couldn't think of an alternative solution at the time.

I like the idea suggested by @PerWiklander and I think it's the correct way to handle this. regarding your concern, you could let the attribute list for a release or 2 and issue a warning when a non boolean value is assigned to a boolean attribute (You could also keep those checks only in development mode)

**Comment by mightyiam** [comment]
Why not collaborate on the list of boolean attributes with other projects and share the maintenance weight?
https://www.npmjs.com/package/is-boolean-attribute or so?

**Comment by paldepind** [comment]
> Hi @paldepind. Jumping here as I was the original author of the attributes module.

It's good to see you :smile: 

> I like the idea suggested by @PerWiklander and I think it's the correct way to handle this. regarding your concern, you could let the attribute list for a release or 2 and issue a warning when a non boolean value is assigned to a boolean attribute (You could also keep those checks only in development mode)

Doing that crossed my mind as well and I think I'd be a nice solution. Having them only in developer mode would definitely be good. But I don't know if there is a reliable way of doing that that works across bundlers, etc.?

@mightyiam That is a nice option if we choose to keep the list.

**Comment by PerWiklander** [comment]
It's good to see a healthy discussion about this :-) Meanwhile I was trying out the `0.6.6` release to see if the first fix did what I needed. It looks like the dist directory of the repo is not updated though. That makes the web jar for Snabbdom, that I use, have the older version (looks like `0.6.4`) of the code. See: http://cdn.jsdelivr.net/webjars/org.webjars.npm/snabbdom/0.6.6/dist/snabbdom-attributes.js

**Comment by paldepind** [comment]
@PerWiklander Yes. I forgot to update the bundles. `0.6.7` should fix that.

I've been thinking about how much breakage doing this would really be. And I actually don't think it matters.

Before, we incorrectly set boolean attributes to `"true"`. That was incorrect according to the spec but wasn't _that_ bad in the real world. If we handle boolean attributes as per @PerWiklander suggests then the only change for people who are currently relying on coercion is that their boolean attributes will be set to some odd values.

For instance, in @fix-fix's example

```js
h('button', {attrs: {disabled: !!(errorsAmount || someCheckPending)}}, 'Continue')
```

The worst case is that `disabled` ends up being set to `"12"` or another number coerced to a string. And while that is incorrect it is no worse than the `"true"` value it would have been previously.

So as far as I can tell it would actually be a minor breaking change.

> It looks like it is missing `buffered` and `contenteditable` already.

I've looked it up and `contenteditable` is actually not a boolean attribute. It's an enumerated attribute and it's valid values are the empty string, `"true"` and `"false"`. This means that `0.6.6` was actually a breaking change in a very minor way. Previously `h("div", {attrs: {contenteditable: false}})` would set `contenteditable` to `""`. But now it will remove the attribute altogether. And when the attribute isn't present the element will inherits it's parents `contenteditable` state instead of always being `false`.

**Comment by caridy** [comment]
The more I think about this, the more I agree with the direction. Snabbdom role is not to normalize, it is to act fast, being the lower level API. Abstractions can guarantee that attributes set to true/false are boolean attributes before they are handled by snabbdom. I think this principle can be also applied to other areas.
