### ISSUE TITLE
Unnecessary re-exports

### ISSUE THREAD

**Issue by katyo** [snabbdom/snabbdom#261]
I found dependency from `h` and `thunk` here:
https://github.com/snabbdom/snabbdom/blob/master/src/snabbdom.ts#L45-L46
Since this modules isn't used anywhere in context below, so I think that re-exports is redundant.

In my project I need patch function only, so I want a proper way to avoid including unnecessary modules into bundle. In case If this cannot be simply deleted according compatibility reasons, than I think that patch code can be moved to module snabbdom/patch for example.

**Comment by caridy** [comment]
probably related to https://github.com/snabbdom/snabbdom/issues/225, and the work we are doing to reorg the exports.

**Comment by mightyiam** [comment]
Closing in favor of #522.
