### ISSUE TITLE
Please document how to run examples locally

### ISSUE THREAD

**Issue by kristianmandrup** [snabbdom/snabbdom#263]
I'd like to experiment with a Custom elements example. Perhaps you could help me ;)
Trying with cycle.js "on top" is causing too many problems...
Thanks.

**Comment by paldepind** [comment]
There is documentation for building the [carousel example](https://github.com/snabbdom/snabbdom/tree/master/examples/carousel-svg).

The other examples are built by running

```
browserify script.js --outfile build.js
```

And then opening `index.html` in a browser.

**Comment by kristianmandrup** [comment]
Thanks :) Btw, regarding custom elements, I think I figured it out... [hello world example](https://github.com/kristianmandrup/ce-hw) which should be easy to adapt for use with snabbdom etc. Now there is a working baseline!

**Comment by paldepind** [comment]
You're welcome. I'll look at the custom element stuff very soon :smile:

**Comment by mightyiam** [comment]
Depends on #525 .
