### ISSUE TITLE
'create' hook doesn't trigger

### ISSUE THREAD

**Issue by pmros** [snabbdom/snabbdom#268]
A very simple example that doesn't work:

```js
import snabbdom from 'snabbdom'
import eventlisteners from 'snabbdom/modules/eventlisteners'
import props from 'snabbdom/modules/props'
import h from 'snabbdom/h'

const patch = snabbdom.init([eventlisteners, props])

let el = document.createElement('div')
document.body.appendChild(el)

let vdom = h('div', 
  {hook: { create: () => console.log('created!')}
  },
  'content'
)
  
patch(el, vdom)
```

A 'created!' message is exapected but console log doesn't show it. 

It's weird, if you change `let vdom = h('div',` by `let vdom = h('div.x',`, then it works!
Of course if you use a DOM element defined into your HTML file (instead of creating dinamically with `createElement`), it works too. I don't know why.

You can try live: https://www.webpackbin.com/bins/-KgAmKnwo58OZVBsh7ic

Thank you for snabbdom.

**Comment by TylorS** [comment]
Hello @pmros, it is correct behavior not to be seeing this hook being called in this example.
The reason being, you are only patching a `div` element with an "updated" `div` element. If you were to change the `h('div', ...)` to something like `h('h1', ...)` you will see the create hook fired.

**Comment by pmros** [comment]
Thank you, TylorS! You are right. Now I understand. I've replaced `create` hook by ` update` hook and it works OK.
I close this isse. Thank you for your quick help.
