### ISSUE TITLE
New event handlers each time the DOM is patched

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#274]
I using snabbdom in my framework (via a scheme interpreter). For various reasons event handlers are returned by a function [1] without memoization. Can this be an issue? What problem can it lead to? 

Can memoization solve the problem? 

[1] the function does inject the store variable from the framework closure basically every handler looks like the following

```javascript

var buttonClicked = function(store) {
    return async function(event) {
       return model + 1;
   }
}
```

**Comment by caridy** [comment]
@amirouche if you provide the same function every time, it will not add it to the DOM listener everytime. Snabbdom does not do any memoization, the upper layer is responsible for that, providing the same value (same memoized function) via `vnode.data.on.click` if needed.

**Comment by amirouche** [comment]
I have a clicker app slowing down and I am wondering where it the stack is the bug.

**Comment by caridy** [comment]
If you're creating a new function everytime, or binding the same function every time, it is possible that it slows things out, but not really because snabbdom, you could memoize on your end.
