### ISSUE TITLE
Is module hook call predictable ?

### ISSUE THREAD

**Issue by Swizz** [snabbdom/snabbdom#277]
Hi there,

Working on the refactoring of [Snabbdom-pragma](https://github.com/Swizz/snabbdom-pragma), I had some ideas who request some answer of yours.

Is the modules array order in the init function have any incidence ?

Given : 
```js
var patch = snabbdom.init([
  require('snabbdom/modules/class').default,
  require('snabbdom/modules/props').default,
  require('snabbdom/modules/style').default,
  require('snabbdom/modules/eventlisteners').default,
]);

patch(container, vnode);
```
This will always result to the following call stack ?

```
class.update -> props.update -> style.update -> eventlisteners.update
```
Or each hook are called concurrently ?

If the answer goes to the side of the predictable call stack, this can result to make [Snabbdom-pragma](https://github.com/Swizz/snabbdom-pragma) stillborn in favor of a more lightweight way with the help of Snabbdom modules to make dirrectly `h` usable as JSX pragma for transpilers.

Cheers,

**Comment by caridy** [comment]
@Swizz 

yes, the order is deterministic based on the order on insertion of the module.

yes, that's the order in which those for updates will be called.

no, they are not called in stack, they are called one by one.

no, JS has no concurrency, those methods are called in the order they appear after the previously returns, they are all sync.

I'm not sure I understand the rest of the question. But yes, you can implement your own h(), and yes, modules can mutate or alter the vnode produced by h(), but you have to be careful when doing so.

**Comment by Swizz** [comment]
ATM, Snabbdom-pragma aim to handle the same api as `React.createElement`.
I based my specs tests on the [React.createElement documentation](https://facebook.github.io/react/docs/react-api.html#createelement) and some [React derivated projects](https://github.com/infernojs/inferno/tree/master/packages/inferno-create-element).

I took this choice, because most used transpilers (Bublé, Babel, Traceur) are able to transplie JSX to React.createElement out of the box. So we do not need to create our own transpiling rules but just a straightforward mapping to `h`.

So, the brand new idea could be to create a Snabbdom module who mutate the vnode according to the createElement specs to the Snabbdom ones. (Like Snabbdom-pragma do but with the power of Snabbdom modules).

For example : 
```jsx

var patch = snabbdom.init([
  // the jsx module called before all official snabbdom modules
  require('snabbdom-xxxxx/modules/jsx').default,

  require('snabbdom/modules/props').default
  require('snabbdom/modules/style').default
]);

const vnode = <input type="text" style-color="red" />;

patch(container, vnode);
```

With the following Bublé settings : 
```js
buble.transform(input, {
  jsx: 'h'
})
```

It will transpile it to : 
```js
const vnode = h('input', { type: "text", 'style-color': "red" });
```
We can imagine right now the jsx module will mutate the vnode from
```js
{
   sel: 'input',
   data: {
      type: 'text',
      'style-color': 'red'
   },
   children: undefined,
   text: undefined,
   elm: Element,
   key: undefined,
 }
```
to
```js
{
   sel: 'input',
   data: {
      props: {
         type: 'text',
      },
      style: {
         color: 'red'
      }
   },
   children: undefined,
   text: undefined,
   elm: Element,
   key: undefined,
 }
```

And the following `props` and `style` module will do the rest.

So, it will result to the same job as Snabbdom-pragma is now doing but internaly with vnode instead of virtual parameters wich result to the call of `h`.

Like this example : 
```jsx
/* written */
const vnode = <input type="text"/>

/* Once Transpiled */
const vnode = Snabbdom.createElement('input', { type: 'text' })

/* Once Executed */
const vnode = h('input', { props: { type: 'text' } }, [])
```

I am sorry about this huge text. I aimed to be as clear as possible.

**Comment by caridy** [comment]
Ok, no, don't do that. That will be too complicated and potentially problematic because the diffing holds certain values in memory that you will mutate. Instead, why don't you use `jsx: v' in the config, where v produces the right vnode. You don't really have to use h(), you can produce a vnode as a plain object :)

**Comment by Swizz** [comment]
Ow this is a pretty cool idea  ! We can gain some simplicity.

But isnt `h` doing more than just return a plain object ?
I dont really want to rewrite the wheel if calling `h` is more easy.

I thank you for all your answers, this help me alot !

**Comment by caridy** [comment]
It does return just an object, and yes, `h()` does more, it has a great deal of flexibility in the order of the arguments, and it supports compound `sel` value, but neither of those are things that you care about because they can't be express in JSX, so, for you it will be the same. I also recommend creating a custom `h()` for projects that are mores restrictive, and expect better perf by removing all that logic that we have in `h()`. I'm closing this one, but feel free to reopen if needed.
