### ISSUE TITLE
How to create isomorphic app?

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#281]
I am wondering how to create isomorphic apps using snabbdom. Is it just a matter of rendering the same content server side? or there is something more to do?

**Comment by staltz** [comment]
Hi :)
You use the package `snabbdom-to-html`
Check this example https://github.com/cyclejs/cyclejs/tree/cda6a8e525b8062c6765027db4683afb21242e8a/examples/isomorphic
