### ISSUE TITLE
Add a shorthand wrapper to simplify the usage?

### ISSUE THREAD

**Issue by dmitriz** [snabbdom/snabbdom#282]
Just wonder if there is interest to include a simple wrapper to replace

```js
var snabbdom = require('snabbdom');
var patch = snabbdom.init([
  require('snabbdom/modules/class').default,
  require('snabbdom/modules/hero').default,
  require('snabbdom/modules/style').default,
  require('snabbdom/modules/eventlisteners').default,
]);
var h = require('snabbdom/h').default;
```

with something like

```js
var { h, patch } = require('snabbdom/short')['class', 'hero', 'style', 'eventlisteners'] 
```

It'd would make code look cleaner, what do you think?

**Comment by caesarsol** [comment]
That's not possible, require calls are parsed at build time... And to include all of them just to use some is wasteful.

Any experienced user may want to add their modules, so that's actually a very powerful way to leverage snabbdom plugin system and not hide it! :)

**Comment by caridy** [comment]
snabbdom is a very low level api, people can create abstractions on top of it, not need to support all kind of initialization routines, just provide the bits.

**Comment by dmitriz** [comment]
@caesarsol @caridy Thank you for explaining, yes, I totally agree.
