### ISSUE TITLE
Pass single node in place of children?

### ISSUE THREAD

**Issue by dmitriz** [snabbdom/snabbdom#284]
Right now this seems illegal:

```js
    // works
    h('div', {className: 'new-style'}, [node])

    // does not work!
    h('div', {className: 'new-style'}, node)
```

because of

```js
export function h(sel: string, children: Array<VNode | undefined | null>): VNode;
```
(https://github.com/snabbdom/snabbdom/blob/master/src/h.ts#L19)

The latter seems to be cleaner and less cluttered though. 
Would it be possible to support?

Here is some further motivation with examples:

https://github.com/queckezz/preact-hyperscript/issues/7

**Comment by staltz** [comment]
I think this is probably confusing for both library code and programmers, because given `h(tag, obj)`, what does obj represent? A `data` object or a child vnode?

**Comment by dmitriz** [comment]
@staltz I see, good point. 

I would imagine, the node object could be marked distinguishable from other objects with something verbose like 
```js
obj.type = 'snabbdom_node'
```
It would seem unlikely the user would ever do that on purpose without expecting to face the consequences.

Or maybe there is some other better way to mark it?

Would that make sense?

**Comment by caesarsol** [comment]
I think it's actually permitted in JS, only TypeScript is preventing it! It's based on the `sel` vnode property.

**Comment by dmitriz** [comment]
@caesarsol Could you please elaborate? 
Do you mean to use `sel` prop to distinguish the vnode?

The way it is right now, you can use the `sel` prop for your own purposes:
```js
h('div', {sel: 'My private selector!'}, 'I am hiding something')
```

Which may not be the best practice, given that it overlaps with the vnode prop, 
but it will work as expected without the user having to worry about it, which is good.
But this also means, you cannot rely on it to distinguish the vnode.

On the other hand, @staltz raised the good point in https://github.com/ohanhi/hyperscript-/issues/43#issuecomment-297459497 that enforcing the array syntax makes the prop/children separation very clear and expressive, so it might be worth the trouble to put the extra brackets, so I am happy to take it back.

**Comment by caesarsol** [comment]
I'm using snabbdom in JS and the single child syntax works!

Take a look at https://github.com/snabbdom/snabbdom/blob/master/src/h.ts#L32 in which the second and third arguments are checked for presence of `.sel` (to identify a vnode) and assigned to children as single-element array.

I'm guessing it's only forbidden by TS signature.

(Or am I missing something?)

**Comment by dmitriz** [comment]
@caesarsol You are right, it does work indeed here, lol ;) 

It didn't work with Preact-hyperscript, so I must have mixed things up.

I guess I should perhaps close this issue then.
