### ISSUE TITLE
Would the maintainer accept a new stream-based example?

### ISSUE THREAD

**Issue by dmitriz** [snabbdom/snabbdom#285]
Inspired by the `CycleJS`, I have created a simple stream counter based on the `flyd` stream library treating streams elegantly as getter-setter functions.

The main feature distinguishing it from other examples here is that there is no manually re-rendering the vnodes needed. Instead the view is subscribed to the data stream that is piped into a re-rendering function storing the last vnode in its closure.

It takes the idea from `CycleJS` to make the state into a stream and in this (massively simple) case let the view subscribe to the state stream. I imagine, it can be extended to more interesting examples where the view stream is a less trivial transformation of the state stream.

Still I've thought that example is dead simple and so might be of interest to other users and wonder if the maintainers would accept it as a PR?

The complete code is below.

```js
var snabbdom = require('snabbdom');
var patch = snabbdom.init([
  require('snabbdom/modules/eventlisteners').default,
]);
var h = require('snabbdom/h').default;
var flyd = require('flyd')

var x = flyd.stream(0)

var view = counter => 
	h('div', [
		h('div', `You clicked 2 x ${counter} times!`),
		h('button', {on: {
		      click: () => x(x() + .5) 
		}}, 'Click me!')
	])

// closure storing the old node
var patcher = container => {
	var old_node = container;
	return node => old_node = patch(old_node, node)
}

window.addEventListener('DOMContentLoaded', () => {
  var container = document.getElementById('container');
  p = patcher(container)
  // piping stream x into the view
  x.map(v => p(view(v)))
});
```

**Comment by paldepind** [comment]
I think the examples in the example directory should be for demonstrating features of Snabbdom. But we have a list in the readme that links to examples of how Snabbdom is used. You're very welcome to submit a link to that list 👍  :smile:
