### ISSUE TITLE
Small problems in running the testing framework

### ISSUE THREAD

**Issue by caesarsol** [snabbdom/snabbdom#288]
(Continues from https://github.com/snabbdom/snabbdom/pull/273#issuecomment-299168776 with @staltz)

In short: I ran the tests in making a PR and encountered some small problems:

- The tests aren't performed on all browsers present on my machine
- Every failing test has a double output (maybe every test is performed two times?)
- The failing tests are difficult to identify due to compiled line number (example: `browserified.js:3985:5`)
- Most importantly, the code is not automatically recompiled and browserified before every test run in watch mode! apparently only the bundle is watched.

I'd like to volunteer in smoothing out these, to make future contributions even easier, if the  
@snabbdom maintainers agree.

In addition I propose to leverage a free CI server to further automate and check PRs, which could lead to faster merging cycle 😉

**Comment by paldepind** [comment]
Snabbdom now uses Karma to run the tests and we have CI thanks to the work done by @jvanbruegge.

I think that fixes most of the issues mentioned here.
