### ISSUE TITLE
Uncaught TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by fernandocanizo** [snabbdom/snabbdom#294]
I don't know if this is related with #225.

![2017-05-18-152801_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1643948/26219959/dd7ae000-3bde-11e7-94da-5a04bec90673.png)

I got an error happening with **v0.6.8** which wasn't happening on **v0.6.7**, the line in question has to do with the way of importing the module:

- Current exploding code does:

```
import snabbdom from 'snabbdom';                                                                  
import snabbdomClass from 'snabbdom/modules/class';
import snabbdomProps from 'snabbdom/modules/props';
import snabbdomStyle from 'snabbdom/modules/style';
import snabbdomEventListeners from 'snabbdom/modules/eventlisteners';
 
const patch = snabbdom.init([ // <-- this is the "undefined 'init' property
  snabbdomClass,
  snabbdomProps,
  snabbdomStyle,
  snabbdomEventListeners,
]);
```

If I replace the import with:
```
const snabbdom = require('snabbdom');
```

Everything runs fine.

We're using Babel to transpile our code. I'll be happy to provide more information, but at this stage I'm not sure what else to show and I don't want to pollute the report with unnecessary info.

**Comment by FeliciousX** [comment]
yeah we had the same problem and it broke.

since you're using babel, you hv to change this to work.

```javascript
import { init } from 'snabbdom';

const patch = init([ /* ... */ ]);
```

**Comment by fernandocanizo** [comment]
Thanks @FeliciousX , that solved it.
