### ISSUE TITLE
[Question] Differences between the props and the attributes module

### ISSUE THREAD

**Issue by thiamsantos** [snabbdom/snabbdom#297]
What are the main differences between the props and the attributes module? When should I use onde instead of other? Can someone help me?

**Comment by caridy** [comment]
it depends on how strict is the creation of vnodes, but my recommendation is very simple, stick to attributes for anything that is a well defined HTML Global Attribute or HTML Attribute for each different type of element that you're creating. Anything else (which could be a lot if you use custom elements), can be props. This is obviously very different to what we see in the examples here, and many users of snabbdom, but it is the most accurate way to match the HTML semantics IMO.

**Comment by thiamsantos** [comment]
Thanks @caridy!!! That really helped me.
