### ISSUE TITLE
Key events not propagated correctly?

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#298]
I've built a full stack web framework in scheme language using snabb for render the frontend. It works mostly fine.

I implemented a modal widgets but I can't use escape key to close the modal.

I am stuck. I don't know how to debug.

Can you develop a modal widget using snabbdom somehow that implement the above escape key behavior?

**Comment by FeliciousX** [comment]
could you show some code example of how it doesn't work? @amirouche

**Comment by amirouche** [comment]
@FeliciousX Thanks for showing up!

I created a very small pure frontend example app that [shows the issue](https://github.com/amirouche/forward.scm/blob/07679a47660da4b453e88667cddc30fb368a8b5a/main.scm#L23). You can git clone the project and checkout the `bug-1` branch with the following command:

```
git clone git@github.com:amirouche/forward.scm.git -b bug-1
```

You must then run the app using `make` (it requires python3).

Basically what I do, is add a `keypress` to a DOM node that is not an `input` and no events are propagated. It works fine with `input` nodes.

**Comment by FeliciousX** [comment]
could u reproduce it on https://esnextb.in/ or https://www.webpackbin.com/ or jsbin or somewhere online where we can test it out and tweak it easier?

**Comment by amirouche** [comment]
That I can do but you should have said that from the start. Do you have a ready to use boilerplate with snabbdom included?

**Comment by FeliciousX** [comment]
I don't really understand the code but here I tried this out

> Basically what I do, is add a keypress to a DOM node that is not an input and no events are propagated. It works fine with input nodes.

https://www.webpackbin.com/bins/-KkfODLKSUmuGHcnRF0R

It works fine. the events propogate up.. but only if you are focused on the input @amirouche

**Comment by FeliciousX** [comment]
basically it only works if an element is focus-ed IIRC . you could `hack` it by adding a `tabIndex` property on the `div` to make it `focus-able` .. but yeah that depends on your use case

**Comment by amirouche** [comment]
@FeliciousX I reproduced what you say in esnextbin indeed it requires tabIndex.

Here are links for future references:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
- http://stackoverflow.com/questions/32911355/whats-the-tabindex-1-in-bootstrap-for#32912224

**Comment by amirouche** [comment]
@FeliciousX I reproduced what you say in esnextbin indeed it requires tabIndex.

Here are links for future references:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
- http://stackoverflow.com/questions/32911355/whats-the-tabindex-1-in-bootstrap-for#32912224
