### ISSUE TITLE
Using Snabbdom without a module system

### ISSUE THREAD

**Issue by jbe** [snabbdom/snabbdom#300]
I am working on a project that is not using webpack, babel or even npm. I write everything in plain old JS, use a C-style preprocessor and a global namespace, filled with long, scoped function names, as if i were programming in C. There are some benefits to creating JS this way, compared to using a fancier toolchain (instant builds, smaller bundles, less time spent on tools, easier to optimize). Actually, it is beginning to seem better in almost every way, and the only things i miss are some webpack plugins, and some modern syntax, but i digress.

I'm using Snabbdom, and in order to get it into my project, i need to get a lot of stuff that i would not need otherwise; nodejs, npm, webpack+plugins, all to build a file that holds Snabbdom, and takes its exports and puts them on the window object.

It would be nice if there was a single-file bundle somewhere that i could just download and use, as if today was ten years ago. Or is there already? Anyone else interested in something like this?

**Comment by fix-fix** [comment]
Main [snabbdom.js](https://github.com/snabbdom/snabbdom/blob/a5b93a7137cf18b51696c385525672e09a3db22b/dist/snabbdom.js) dist file is already packaged as a UMD module with identifier `snabbdom`, i.e. it will be registered as global variable `snabbdom` if you are not using any bundler or packaging system.

You can copy its content right in your browser console and see for yourself.

**Comment by jbe** [comment]
Indeed that seems to do exactly what I want. I'm not that familiar with UMD or it's relatives so i never would have guessed from the dist files themselves. Thanks for the quick reply!

**Comment by jbe** [comment]
This is what i did to make it work:
- Downloaded dist/snabbdom.js, as well as all the modules
- Removed the embedded sourcemaps at the bottom of each file
- Found out that...
  - `h` is available as `snabbdom.h`
  - modules available as global variables are snake_cased, like `snabbdom_eventlisteners`, etc.

Works great.
