### ISSUE TITLE
dataset module removes blank string data attributes

### ISSUE THREAD

**Issue by johanalkstal** [snabbdom/snabbdom#303]
It's a usual case to want to have an empty data attribute as a JS hook, like `data-hook`.
There are two ways to add such an attribute, with the `snabbdom/modules/attributes` or `snabbdom/modules/dataset`
```
var snabbdom = require('snabbdom')
var patch = snabbdom.init([
  require('snabbdom/modules/attributes').default,
  require('snabbdom/modules/dataset').default
]);
var h = require('snabbdom/h').default

var container = document.getElementById('container');

var vnode = h('div', [
  h('p', { attrs: { 'data-hook': ''} }, 'Has data-hook by attribute'),
  h('p', { dataset: { hook: '' } }, 'Has data-hook by dataset')
])

patch(container, vnode)
```
```
<div>
  <p data-hook="">Has data-hook by attribute</p>
  <p data-hook="">Has data-hook by dataset</p>
</div>
```

Now let's update the vdom elements with new content.

```
var updatedVnode = h('div', [
  h('p', { attrs: { 'data-hook': ''} }, 'Still has data-hook by attribute'),
  h('p', { dataset: { hook: '' } }, 'Has lost its data-hook by dataset')
])

patch(vnode, updatedVnode)
```
```
<div>
  <p data-hook="">Still has data-hook by attribute</p>
  <p>Has lost its data-hook by dataset</p>
</div>
```

The element updated with `snabbdom/modules/dataset` has lost its data attribute.

This only happens with an empty value.

This forces you to use `snabbdom/modules/attributes` for these cases.

**Comment by caridy** [comment]
we should probably update https://github.com/snabbdom/snabbdom/blob/master/src/modules/dataset.ts#L21, using `in` might be better here... but then we have the issue of `null` and `undefined` as values that will be stringify, which is the behavior of the browser anyways. e.g.: `elm.setAttribute("hook", undefined)` it produces `data-hook="undefined"`.

**Comment by kuraga** [comment]
Still buggy?

**Comment by wanghaida** [comment]
It also has a problem, when it's `data-hook: 0`,  you should use `if (oldDataset === undefined && dataset === undefined) return` in https://github.com/snabbdom/snabbdom/blob/master/src/modules/dataset.ts#L14
