### ISSUE TITLE
Mix in a DOM Element inside a vnode tree?

### ISSUE THREAD

**Issue by wbern** [snabbdom/snabbdom#304]
Hey.

I'd like to know if it's possible to get a dom element into a vnode, and keep it between patches without side effects to input focus and other things.

I'm part of a larger project that is going to migrate to Snabbdom, but we need to get a migration plan put in place, which involves keeping our existing code that works with DOM elements.

I noticed that the hooks only seem to pass vnodes in the parameters, so I turn to creating an issue to ask for more help. Thanks in advance!

**Comment by adz5a** [comment]
Hello,

I am not completely sure to understand what you want to do but I think there are two approaches : use vnodes all the way and / or use hooks ( or custom modules as you mentionned ). 

You can use the tovnode module which will recursively convert DOM elements to vnode.
You can use it like this : 

```
import tovnode from "snabbdom/tovnode";
const elem = document.querySelector("#someId");
const vnodeTree = tovnode(elem);
```

Then you can use a function to manipulate the vnode as data. 

If what you meant is reusing code that uses stuff like `addEventListener` and native methods then you are looking for is modules. There is an `elm` on each vnode that you can use as a ref to the current DOM representation of a vnode that you can use inside your module / hook. 
You can then create a custom module to pass to the init function to enable code reuse from your existing codebase.

You should probably look for the existing modules that provides access to the DOM APIs and see if you can port some of your code to these modules. If you have an example maybe I can try to help you with a little more details.

**Comment by wbern** [comment]
Hi.

I realized that "manually" created DOM elements can be tied to a DOM element generated by Snabbdom, and persist between renders, as long as the element remains.

Thanks for the help!
