### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by nunocastromartins** [snabbdom/snabbdom#305]
Just noticed the license hasn't been updated.

Maybe change it to something like: `Copyright (c) 2015-present Simon Friis Vindum`.
React seems to do this. :-)

Otherwise: `Copyright (c) 2015-2017 Simon Friis Vindum` would be enough for now.

**Comment by eriknstr** [comment]
Literally writting "2015-present" is lazy and bad form. "2015-2017" might be fine. The completely correct thing to do is to comma-separate each year where one or more changes was made. "2015, 2016, 2017" in this case.

**Comment by nunocastromartins** [comment]
I personally like the lazy solution (no need for more edits in the future).
It's not up to me, though.

I'm fine with any of those. :-)

**Comment by caridy** [comment]
From the legal point of view, folks usually recommend to just have the date or year of the creation of the file... the rest is not really relevant from that point of view, and that piece should never change. So, I guess what we have is just fine, I will argue that we can eliminate the lazy part of it and just have the year of the creation of the file.

**Comment by nunocastromartins** [comment]
I didn't know that; many projects seem to update the file each year, I just assumed that was the norm.

If what you're saying is true, please feel free to close the issue!

**Comment by paldepind** [comment]
I'm closing this based on what @caridy wrote above.
