### ISSUE TITLE
Adding the AMP boolean attributes to the attributes module

### ISSUE THREAD

**Issue by zkochan** [snabbdom/snabbdom#306]
I am trying to render an [AMP HTML](https://www.ampproject.org/) page using snabbdom. AMP has some custom boolean attributes: amp, ⚡, amp-boilerplate (might be more, I don't know yet).

Would it be fine to add those attributes to the list of boolean attributes [here](https://github.com/snabbdom/snabbdom/blob/master/src/modules/attributes.ts#L6)

Note: currently snabbdom renders those as `amp="true"` and that does not pass the AMP validator.

* * *

I can work on a fork and try to make all the necessary changes that need to be done for snabbdom to be able to render AMP-compliant pages

**Comment by zkochan** [comment]
This might be an issue with [snabbdom-to-html](https://github.com/snabbdom/snabbdom-to-html). I am not sure yet.

**Comment by fix-fix** [comment]
I think the only clear way (without exposing attributes module internals) of making this possible is to define a separate module for custom handling of VNode's attributes from AMP.

However, the main problem is that AMP is non-compliant with HTML standard and those attributes are not valid at all, and it's should be avoided.

**Comment by zkochan** [comment]
So a separate module has to be created and used instead of the core attributes module, right?

**Comment by fix-fix** [comment]
Yes, but I don't think that module should replace attributes module, but instead there should be a special way for providing AMP (and maybe some other non-standard) attributes to VNodes (not in the `data` property), that can be used alongside default attributes module.

**Comment by caridy** [comment]
There is an issue somewhere to remove the list of booleans, and instead rely on the value to determine if the attribute is a boolean or not and act accordingly. It will be a mostly backward compatible solution, but there are cases in which it will break some folks. We need this for custom elements as well, and I suspect we are just waiting for someone to send a PR :)

**Comment by paldepind** [comment]
Thank you for reporting this issue @zkochan. The latest release now handles custom boolean attributes seamlessly.

`h("div", { attrs: { amp: true} }` results in `<div amp>`.

**Comment by zkochan** [comment]
Awesome! Thanks!
