### ISSUE TITLE
deleting a dataset property that doesn't exist throws an error

### ISSUE THREAD

**Issue by FeliciousX** [snabbdom/snabbdom#309]
Found out that Safari automatically deletes the dataset property when you do `use strict;`

So when [this line of code](
https://github.com/snabbdom/snabbdom/blob/7b45afea49a32e2f4b0c5f12ca7df0040fd1dcf7/src/modules/dataset.ts#L23) run, it may error. So maybe an extra checking? `if (d && d[key]) {`

I have a PR ready

**Comment by adz5a** [comment]
Hello, are you referring to this issue : [https://stackoverflow.com/questions/28973603/unable-to-delete-property-on-safari-when-trying-to-delete-dataset-attribute-in](url) ?

If the issue is that the property is not configurable then a good check would be with  `Object.getOwnPropertyDescriptor` on the targeted property to ensure that `delete` can be used safely.

**Comment by FeliciousX** [comment]
yes that exactly..

when we use the `dataset` module, the chances of the `delete` to run is high when you remove a property etc..

Now we are using [patch-package](https://github.com/ds300/patch-package) (Thanks @staltz , because of your tweets I then know about this) to patch it first temporarily

```diff
diff --git a/node_modules/snabbdom/modules/dataset.js b/node_modules/snabbdom/modules/dataset.js
index cbce31a..a67fa81 100644
--- a/node_modules/snabbdom/modules/dataset.js
+++ b/node_modules/snabbdom/modules/dataset.js
@@ -12,7 +12,7 @@ function updateDataset(oldVnode, vnode) {
     var d = elm.dataset;
     for (key in oldDataset) {
         if (!dataset[key]) {
-            if (d) {
+            if (d && d[key]) {
                 delete d[key];
             }
             else {
@@ -33,4 +33,4 @@ function updateDataset(oldVnode, vnode) {
 }
 exports.datasetModule = { create: updateDataset, update: updateDataset };
 exports.default = exports.datasetModule;
-//# sourceMappingURL=dataset.js.map
\ No newline at end of file
+//# sourceMappingURL=dataset.js.map
```

But if we are going with the `Object.getOwnPropertyDescriptor` way, im not sure about the performance impact. might need to check with the maintainers
