### ISSUE TITLE
Main module exposes h, init, thunk (but not a default)

### ISSUE THREAD

**Issue by mariuslundgard** [snabbdom/snabbdom#312]
The main module exposes the `h` and `thunk` helpers. What if I don’t need those, and simply want to import the `init` function?

Currently:

```js
import * as snabbdom from 'snabbdom'

console.log(Object.keys(snabbdom)) // ["h", "thunk", "init"]
```

IMO this would be the desired API for cherry-picking modules:

```js
import h from 'snabbdom/h'
import snabbdomClass from 'snabbdom/modules/class'
import snabbdomInit from 'snabbdom/init'

const patch = snabbdomInit([
  snabbdomClass
])

// use `h` somewhere in this module
h(...)
```

And in case I want to use it all:

```js
import snabbdom, {h, thunk} from 'snabbdom'
import snabbdomClass from 'snabbdom/modules/class'

const patch = snabbdom.init([
  snabbdomClass
])

// use `h` and `thunk` somewhere in this module
h(...) // or snabbdom.h(...)
thunk(...) // or snabbdom.thunk(...)
```

Is there something about the current API that I‘m not getting?

**Comment by mariuslundgard** [comment]
By the way, I love `snabbdom` and use it a lot! I’m just wondering if refining the API a little would make things even smoother :)

**Comment by caridy** [comment]
related to https://github.com/snabbdom/snabbdom/issues/225

**Comment by mightyiam** [comment]
The plan is to have only named exports. Closing in favor of #522.
