### ISSUE TITLE
Multiple eventlistners can't get the event.

### ISSUE THREAD

**Issue by zhihuahuang** [snabbdom/snabbdom#316]
I want to add multiple event listener to an vnode, So I write code like this.
```javascript

function fn1 (event) {
    console.log(event);
    // ...
}

function fn2 (event) {
    // ...
}

h('button', {
    on: {
        click: [
            [fn1],
            [fn2]
    }
});
```

But I get the event is undefined, so i checked the source code and find in `src/modules/eventlisteners.ts` 29 line

```javascript
// call multiple handlers
for (var i = 0; i < handler.length; i++) {
    invokeHandler(handler[i]);
}
```
Should not it be the following?

```javascript
// call multiple handlers
for (var i = 0; i < handler.length; i++) {
    invokeHandler(handler[i], vnode, event);
}
```
Is this a bug or how can i use multiple eventlistener?

**Comment by acstll** [comment]
Looks like a bug. Tests are checking the handler is being called, but not that the `event` is being passed… https://github.com/snabbdom/snabbdom/blob/master/test/eventlisteners.js#L108-L114
