### ISSUE TITLE
Let's choose a logo

### ISSUE THREAD

**Issue by paldepind** [snabbdom/snabbdom#317]
Snabbdom is very fortunate that several potential logos have [been designed and proposed](https://github.com/snabbdom/snabbdom/issues/172). The goal of this thread is to figure out which logo the community prefers through a vote.

__How to vote__

If you prefer the _first logo_ please react to this post with a ❤️ 

If you prefer the _second logo_ please react with a 🎉 

If you like both logos feel free to vote for both of them.

**The first logo** was designed by @grimalschi. The shape contains an "S" surrounded by two brackets. The brackets aptly symbolize HTML/DOM which Snabbdom manipulates. The overall shape looks like a diamond that slightly resembles a Superman-like shield in a very cool way. The logo is flat but has a subtle gradient that adds a bit of depth.

![bc8d285c-3752-11e7-81db-02c07a443c02](https://user-images.githubusercontent.com/521604/28008230-f71be9a4-6556-11e7-8a56-305d59cf0ae5.png)

**The second logo** is by @acstll. Through a combination of soft curves and a few hard edges an "S" is formed in a mesmerising way. The two pieces of the logo may represent the two structures that Snabbdom works on in the patch process: an old vnode tree and a new vnode tree. The circulair shape can be seen as symbolising the iterative process of virtual DOM library where one patch is continously applied on top of an earlier patch.

![snabbdom](http://acstll.musca.uberspace.de/ruleta/snabbdom/snabbdom-logo--text.png)

I think both logos are really nice and have some great qualities. A huge thank to both @grimalschi and @acstll for contributing their designs 👍 .

**Comment by paldepind** [comment]
Note that both logos as presented above are not of a resolution optimal for HiDPI screens. Once a logo is chosen we will use high-resolution

**Comment by grimalschi** [comment]
It looks like I have a majority (17 vs 5).

So I continue to work with logo.

I offer to use Quicksand font. It's a beautiful modern font with Open Font License.
https://fonts.google.com/specimen/Quicksand?selection.family=Quicksand

Here is all geometry, colors and proportions:

![image](https://user-images.githubusercontent.com/9027592/28045810-bb0983de-65df-11e7-8a76-f4bfaab33b94.png)

**Comment by grimalschi** [comment]
Hight resolution:


![image](https://user-images.githubusercontent.com/9027592/28045843-f4ddb724-65df-11e7-8f6e-4588fbd8417a.png)

Sketch file:
[logo.sketch.zip](https://github.com/snabbdom/snabbdom/files/1137414/logo.sketch.zip)

SVG:
https://gist.github.com/grimalschi/cabe7e3c506aa08ec66fdac0d53b0974

**Comment by acstll** [comment]
I would have waited a bit to get a major total number of votes, but the majority is very clear anyways, so congrats, great work :^)

**Comment by grimalschi** [comment]
@acstll thank you!

Correct SVG: (curves isntead of text):
https://gist.github.com/grimalschi/51f989c7a5103f25bea0cebfdadf9e45

**Comment by grimalschi** [comment]
Or we can use logo without shape.

![image](https://user-images.githubusercontent.com/9027592/28176166-b1066960-67f6-11e7-9b07-f2b3395097d2.png)

This is another choice we should make :)

Thoughts?

**Comment by grimalschi** [comment]
Last one looks more clear and more pleasant for me.

**Comment by acstll** [comment]
I prefer the original https://github.com/snabbdom/snabbdom/issues/317#issuecomment-314288259

On this last one, the "squared" purple S is more clear and visible so the contrast with the all rounded black S right next to it is too heavy, almost disturbing IMHO.

**Comment by grimalschi** [comment]
It looks like we have two variants again ;D

I think @paldepind can choose one, as an creator of snabbdom.

**Comment by wbern** [comment]
:heart:, the smaller variant.

**Comment by danr** [comment]
I like https://github.com/snabbdom/snabbdom/issues/317#issuecomment-315126754 it looks fab!

**Comment by grimalschi** [comment]
So what we do?

**Comment by grimalschi** [comment]
Let's choose a logo before 2018 will come!

**Comment by paldepind** [comment]
I think we should go with the one without the shape around.

Really good work on the logo @grimalschi. Now we need to figure out where to use it!

* In the GitHub repo image (obviously)
* Centered in the top of the readme?

**Comment by danr** [comment]
Could be nice to have it it some of the examples in this repo somehow.

For example, the `react-create-app` makes a dummy webpage with a spinning react logo.

**Comment by mightyiam** [comment]
Closed in #433 .
