### ISSUE TITLE
Many Thoughts and Question

### ISSUE THREAD

**Issue by ccorcos** [snabbdom/snabbdom#32]
This looks really nice. I can tell you put a lot of thought into it. I've [been investigating the elm architecture](https://github.com/ccorcos/elmish) which has led me here because this snabbdom uses pure functions unlike React! :+1: Anyways, here are some questions, thoughts, and ideas... Answer at your leisure. 

1) Whats difference between props and attributes? I didnt really understand the difference in the README.

2) When you set a delayed animation on remove, it looks like [it listens for the transitionend event](https://github.com/paldepind/snabbdom/blob/master/modules/style.js#L53) which [is notoriously inconsistent](https://github.com/facebook/react/issues/1326). With inline styles, it seems like it would be pretty easy to parse the duration of the transition and use a setTimeout like the latest version of React. Sound like a good idea? 

3) I don't really understand the styles module works very well, but it would be really sweet if it the styles were prefixed automatically. I'm also curious how to prefix flexbox since the display key in the object would have to be repeated...

``` css
.page-wrap {
  display: -webkit-box;      /* OLD - iOS 6-, Safari 3.1-6 */
  display: -moz-box;         /* OLD - Firefox 19- (buggy but mostly works) */
  display: -ms-flexbox;      /* TWEENER - IE 10 */
  display: -webkit-flex;     /* NEW - Chrome */
  display: flex;             /* NEW, Spec - Opera 12.1, Firefox 20+ */
 }
```

4) Interesting how [you're using requestAnimationFrame](https://github.com/paldepind/snabbdom/blob/master/modules/style.js#L19) for the rendering cycle. Whats the reasoning behind that rather than just setting the value immediately?

5) It would be really sweet if there was a simple way to purify events [like they do in React](https://facebook.github.io/react/docs/events.html). Its such a hassle working with keyboard events and all the quirks between different browsers and operating system...

6) I like how you allow click handlers to be passed an array. Thus you can do a shallow equals on the elements of the array. If you were to use Function.prototype.bind, then the reference will always change and thats not good for re-rendering. But sometimes you want to bind a value, and capture the value from the event. `toChildAction` is a good example of this [here](https://github.com/ccorcos/elmish/blob/master/listOf.coffee#L47). I've been thinking about this issue a lot lately in regards to react and ramda as well. It would be sweet if there was a standard in fantasyland where objects have a .equals method to use instead of referential equality if it exists. We could create a bind function that keeps track of the original arguments and function so we can call .equals and it will tell us if two functions are effectively the same (same original function and same bound arguments). This would be an awesome addition to Ramda and could be a more generalizable solution for snabbdom. I mentioned this [here](https://github.com/facebook/react/issues/5197) with some ugly looking code.

7) I'm curious how you are using this library. Do you have any large examples that I can browse and learn from? Specifically, I'm interested in how to architect the app with components and different views with http and websocket side-effects. It seems like I could just use a patch to subscribe and unsubscribe to data over websockets with the view lifecycle. Still trying to figure this out though. This was the limit I ran into with my elmish example. It abstracts very powerfully, but I couldnt figure out how to deal with sub/unsub....

8) What are your thoughts on React Native? Would it be possible to write a shim somehow to use this library with React Native? It would be awesome to leverage all the resource facebook is pouring into React.

9) Have you seen some of the cool Redux Dev Tools? It would be pretty sweet to implement some of these. 
- https://github.com/lapanoid/redux-devtools-gentest-plugin
- https://github.com/calesce/redux-slider-monitor
- https://github.com/gaearon/redux-devtools

10) Have you checked out Relay and GraphQL? The most interesting thing to me about it is how Relay accumulates resource requests through the view heirarchy to send one giant request as opposed to many smaller requests. I'm trying to figure out how that would work within an Elm-like architecture.

Anyways, thats enough for now. This is a sweet library and so is flyd. Keep up the great work. I'd love to help!

**Comment by ericgj** [comment]
Answering what I can...  you may also try asking on the [gitter channel](https://gitter.im/paldepind/snabbdom)

1)  The props module sets element properties directly. Attributes module does `elm.setAttribute` . Most of the time props is what you want, attributes was added mainly for SVG support I believe.

6) 
> I like how you allow click handlers to be passed an array. Thus you can do a shallow equals on the elements of the array. If you were to use Function.prototype.bind, then the reference will always change and thats not good for re-rendering. 

Actually the eventlisteners module does not rely on checking equality at all, by reference or otherwise. The event listeners are bound to the DOM only the first time. Any changes to the handlers (either as array or function) are made on the virtual nodes only, by [mutating a variable that's captured inside the handler function](https://github.com/paldepind/snabbdom/blob/master/modules/eventlisteners.js#L29-L37). It's a bit tricky, but it means zero DOM changes when the handler changes.

Re. value equality, Ramda does have `equals`.

7) I wrote some examples, not very large but "realistic", in https://github.com/paldepind/functional-frontend-architecture/ . See the file-uploader and autocomplete there. There's also a sample Todo app there (which doesn't deal with effects however).  I think it would be great to add an example using websockets.  Have you seen [this tutorial](http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html) ?  Quite long but it does give an example of using websockets with redux (which is of course similar).

**Comment by ccorcos** [comment]
> Actually the eventlisteners module does not rely on checking equality at all, by reference or otherwise. The event listeners are bound to the DOM only the first time. Any changes to the handlers (either as array or function) are made on the virtual nodes only, by mutating a variable that's captured inside the handler invoke function. It's a bit tricky, but it means zero DOM changes when the handler changes.

Oh interesting. Thats clever. But this is the issue I have with the current elm architecture is that the views are going to be entirely recomputed on every mutation. Whats performant in React (my understanding at least) is that it does a referential comparison of the props to memoize the render function, so the render function never gets called if the props didn't change. How does this work in snabbdom?

> Have you seen this tutorial ? Quite long but it does give an example of using websockets with redux (which is of course similar).

Interesting -- they just send the entire state over to the server. Thats a very interesting way of dealing with websockets. Simply listen to the model stream, filter out only the state you need and entirely sync it with the server. Not necessarily the most efficient use of network resources, but interesting none-the-less. I suppose you could just build some stateful code here to manage it all. But this doesn't exactly abstract well. My litmus test for good UI programming is being able to create multiples of any component or the entire app without changing any existing code and adding only a minimal amount of new code... It seems to me like with snabbdom, we'd want to hook into the lifecycle methods to subscribe and unsubscribe to certain chatrooms. But this isnt nearly as pure... What do you think?

I'll hop on gitter when I get some free time. I'll be at the [elm meetup](http://www.meetup.com/Elm-user-group-SF/events/224714603/) tonight though. Let me know if you'll be there of if you want me to ask those wizards any questions. :)

**Comment by ericgj** [comment]
> Whats performant in React (my understanding at least) is that it does a referential comparison of the props to memoize the render function, so the render function never gets called if the props didn't change. How does this work in snabbdom?

Thunks: https://github.com/paldepind/snabbdom/blob/master/thunk.js  . See [description in readme](https://github.com/paldepind/snabbdom#helpers) for how to use them. But in practice, re-rendering your views is almost never a performance issue.

> It seems to me like with snabbdom, we'd want to hook into the lifecycle methods to subscribe and unsubscribe to certain chatrooms. But this isnt nearly as pure... What do you think?

I haven't really thought about it, but I'd assume your subscribe and unsub actions would be in response to user input so would not be processed differently than any other effect, would not need to mess around at the virtual dom level at all?  I would look at the Elm websocket stuff first.

**Comment by ccorcos** [comment]
The autocomplete example looks really nice. Its very interesting how we ended up in almost the same place. But it looks like you're using Futures instead of Promises so you can fork them at the top level. Interesting. I've never played with futures. [Looks like you can map over them though?](https://github.com/paldepind/functional-frontend-architecture/blob/master/examples/autocomplete/js/app.js#L168) Seems like that's  more in line with Tasks and the elm architecture as opposed to piping the effects stream all the way down.

**Comment by ericgj** [comment]
Yeah, map and chain (which promises kind of combine together as `then`, depending on return value), super useful. That `bimap` is handy for routing error vs success responses. https://github.com/ramda/ramda-fantasy  has one implementation, https://github.com/folktale/data.task  has another.

**Comment by ccorcos** [comment]
Thanks for all the help @ericgj. I really appreciate it.

Thunks are what I'm looking for. And it looks like bound functions will fail [this test](https://github.com/paldepind/snabbdom/blob/master/thunk.js#L17) every time... Perhaps it isn't the end of the world. But in my current app, I end up with a huge list of items and the rendering takes an entire second sometimes. I should probably be doing some infinite scrolling anyways...

>  I'd assume your subscribe and unsub actions would be in response to user input so would not be processed differently than any other effect.

The only real difference is unsubscribing. Suppose I have a chatroom that I initialize with a roomId. It returns with a side-effect that subscribes to messages from that chatroom. Messages come through a stream in the inputs array to your start app function and end up back at the chatroom. But no consider a listOf chatrooms. Now the websocket effect is going to be some kind of construct that allows you to filter only the messages specific to that chatroom and maps over them to route the messages back to the appropriate chatroom. I'm not sure what this functor thing would be but we could create it. The tricky part now is when you remove the item from the list. Without the list knowing about what the children are doing, you'd need to use a lifecycle hook in the children to unsubscribe from the chatroom when its removed. Does that sound reasonable? The only problem with this is the entire view is becoming quite impure.

**Comment by ccorcos** [comment]
ramda-fantasy looks awesome btw. Thanks!

**Comment by ericgj** [comment]
PS. I found this tutorial for using futures very helpful:  https://github.com/ramda/ramda/wiki/Cookbook#use-ramda-fantasy-future-to-wrap-ajax

**Comment by ccorcos** [comment]
Awesome! Thanks -- if theres anything else, please sent it my way. I will read anything you send me :+1:

**Comment by paldepind** [comment]
> 2) When you set a delayed animation on remove, it looks like it listens for the transitionend event which is notoriously inconsistent. With inline styles, it seems like it would be pretty easy to parse the duration of the transition and use a setTimeout like the latest version of React. Sound like a good idea?

I choose the current implementation because it seemed like the best approach and resulted in the simplest code. I was however not aware that `transitionend` is unreliable. In that case I think a `setTimeout` based implementation would be a great idea.

**Comment by ulrikaugustsson** [comment]
https://github.com/elm-native-ui/elm-native-ui

They create JSON from the generated vtree and then let react render that. That might be a solution to get snabbdom working with react native.

**Comment by jbucaran** [comment]
@ccorcos Hi!

With regards to

> 4. Interesting how you're using requestAnimationFrame for the rendering cycle. Whats the reasoning behind that rather than just setting the value immediately?


I would presume for the same reason this module exists. The gist of it is:

> Normally you would re-create the virtual tree every time your state changes. Using requestAnimationFrame you can batch calls to render (patch in Snabbdom) so you only update the virtual tree at most once per request animation frame.


@paldepind Correct me if I am totally wrong.
