### ISSUE TITLE
Setup Travis/Circle/other ci

### ISSUE THREAD

**Issue by erikvold** [snabbdom/snabbdom#322]
I'm curious why there is no ci setup?

**Comment by caridy** [comment]
We are waiting for a brave soul to send a nice PR :)

Related to https://github.com/snabbdom/snabbdom/issues/286

**Comment by mightyiam** [comment]
Give me necessary access to the accounts (Travis-CI and Browserstack) and I'll do it.

**Comment by paldepind** [comment]
We now have CI thanks to the work done by @jvanbruegge.

**Comment by mightyiam** [comment]
Thank you so much, @jvanbruegge and @paldepind! :medal_sports: :trophy: :heart:
