### ISSUE TITLE
IE, svg, class plugin: Unable to get property 'add' of undefined or null reference

### ISSUE THREAD

**Issue by whitecolor** [snabbdom/snabbdom#323]
In IE11 this code:

```js
var snabbdom = require('snabbdom');
var patch = snabbdom.init([ 
  require('snabbdom/modules/class').default
]);
var h = require('snabbdom/h').default;

window.addEventListener('DOMContentLoaded', () => {
  var container = document.getElementById('container')
  var vnode = h('svg', [    
    h('path', {
      class: {
        some: true 
      }
    })
  ]);
  patch(container, vnode);
})
```

gives an error `Unable to get property 'add' of undefined or null reference`

![image](https://user-images.githubusercontent.com/736697/28499701-4d507dd4-6fd5-11e7-93f6-b3218fdb4125.png)

This happens when nested element in `svg` is trying to use `class` plugin.

**Comment by mightyiam** [comment]
@whitecolor thank you for using snabbdom and reporting this issue (two years ago).

[IE does not have `SVGElement.classList`](https://caniuse.com/#search=classList).

I use [this polyfill](https://www.npmjs.com/package/svg-classlist-polyfill).
