### ISSUE TITLE
Add ES6 module build

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#338]
Snabbdom cannot be scope hoisted because it only has a commonjs build.
The package.json file allows for a second entry `module` near `main` that can be used to additionally provide an ES6 build.

The problem is that snabbdom has many `snabbdom/XX` modules, that makes this harder to solve (ie impossible without restructuring or splitting in multiple packages)

**Comment by caridy** [comment]
It is certainly doable. We can start by generating the output in ES6 module format into a folder, and update pkg.json with the `module` configuration. The good news here is that we can use this opportunity to readjust a little bit the API when using it via ES6 modules (this does not have to be backward compatible). There is a very old PR https://github.com/snabbdom/snabbdom/pull/247 that we should probably attempt to revamp for this.

**Comment by JSteunou** [comment]
I think this is solved by now. Last release as `es` folder

**Comment by mightyiam** [comment]
Thank you for using snabbdom.

An ES modules build is provided since fc47e2c9b1bd1dfdaeea7b86227c7b75be14a071.

**Comment by kuraga** [comment]
@mightyiam yes but we would be very pleased about more attention on https://github.com/snabbdom/snabbdom/pull/247#issuecomment-422414530 (and while #247, #225 and issues pointed in that comment) :smile: Thanks!
