### ISSUE TITLE
Benchmark setup to measure vnode creation performance 

### ISSUE THREAD

**Issue by blikblum** [snabbdom/snabbdom#349]
Regarding performance of `h`, being discussed [here](https://github.com/snabbdom/snabbdom/pull/337#issuecomment-349014050), i'm looking to improve performance of jsx pragma. 

Does anybody have a benchmark setup to measure specifically vnode creation? 

The [benchmark](https://github.com/snabbdom/snabbdom/pull/337#issuecomment-349014050) in this repo measures the patch performance

**Comment by caridy** [comment]
@blikblum my team was suppose to provide the infrastructure for benchmarking snabbdom per pull request (@pmdartus is still working on getting that ready), no ETA that I know of. But if you want to go ahead and try to create something, I will be supportive.

**Comment by mightyiam** [comment]
Closing in favor of #286. Which is more general but until progress is made there's no point in breaking this down into smaller tasks that I don't know yet.
