### ISSUE TITLE
duplicated eventlistener is attached after patching

### ISSUE THREAD

**Issue by doofin** [snabbdom/snabbdom#352]
```javascript
var patch = snabbdom.init([
    snabbdom_attributes.default,
    snabbdom_class.default, 
    snabbdom_eventlisteners.default,
    snabbdom_eventlisteners.default,
]);
var h = snabbdom.h; 
      
var container = document.getElementById('maindiv');
var vnode = h('div#container.two.classes', {on: { click: ()=> alert("first")}}, "first patch");
patch(container, vnode);
var newVnode = h('div#container.two.classes', {on: {click: ()=>alert("second")}}, h("div",{},"2nd patch"));
patch(vnode, newVnode);

```

Click the div would alert twice,and chrome dev tools shows that there are two eventlisteners attached ,this seems not the expected behavior...

**Comment by caridy** [comment]
Oh, you have `snabbdom_eventlisteners.default` module used twice in your initialization, not sure why, but I'm sure that's the reason why you will see two listeners added to the element.

**Comment by doofin** [comment]
Thanks for pointing out the culprit! Removing it solves the issue,please close this.
