### ISSUE TITLE
attrs module not working

### ISSUE THREAD

**Issue by katestaneva** [snabbdom/snabbdom#357]
Hello,

the attributes module doesn't seem to work with me. The basic example:
h('a', {attrs: {href: '/foo'}}, 'Go to Foo');

outputs:
<a>Go to Foo</a>

**Comment by mightyiam** [comment]
Could you please provide a minimal example?

**Comment by paldepind** [comment]
The attribute module works for myself and many others. Without a concrete example, it's hard to say why it didn't work for you.
