### ISSUE TITLE
remove hook is not called on child-node if parent node is removed

### ISSUE THREAD

**Issue by kay999** [snabbdom/snabbdom#366]
This makes remove animations which should animate both parent and child elements impossible. "destroy" is called recursively, but that's not enough for most kinds of animations.

I've looked at the vue-fork of snabbdom and they seem to have changed it to "remove" to be called recursively.

**Comment by blikblum** [comment]
I think an example showing the desired animation and the snabbdom setup would make easier to find a solution

**Comment by kay999** [comment]
Look at https://jsfiddle.net/8kpa5dLd/22/

Both text-divs slide out on remove, but only if you remove them directly (as the second element). If the parent element of those elements is removed, only the parent-remove transition is played, because the remove-hook isn't triggered for the child elements anymore.

**Comment by caridy** [comment]
In general, there are two hooks that are complementary, `remove` and `destroy` (both available as global hooks and in `vnode.data.hook` as well). `remove` is invoked only on the element that is being removed from the DOM intentionally and has an async mechanism in case if you need more control, while `destroy` is invoked on the entire subtree (recursively).

As for the style module shipped with snabbdom, it provides mechanism to tap into `remove` and `destroy` hooks. In your example (jsfiddle), you're only doing the `remove`, but not the `destroy`. Maybe we should update the documentation to highlight that.

**Comment by blikblum** [comment]
I tried to use the style module destroy hook, and no animation at all

**Comment by kay999** [comment]
The destroy hook is called directly before the element is removed from the DOM, so it can't be used like "remove" (which is implemented via delaying removal until the animation is finished). 

In vue they changed the remove hook to make "remove" recursive (at least for components):

```javascript
function removeVnodes (parentElm, vnodes, startIdx, endIdx) {
    for (; startIdx <= endIdx; ++startIdx) {
      const ch = vnodes[startIdx]
      if (isDef(ch)) {
        if (isDef(ch.tag)) {
          removeAndInvokeRemoveHook(ch)
          invokeDestroyHook(ch)
        } else { // Text node
          removeNode(ch.elm)
        }
      }
    }
  }

  function removeAndInvokeRemoveHook (vnode, rm) {
    if (isDef(rm) || isDef(vnode.data)) {
      let i
      const listeners = cbs.remove.length + 1
      if (isDef(rm)) {
        // we have a recursively passed down rm callback
        // increase the listeners count
        rm.listeners += listeners
      } else {
        // directly removing
        rm = createRmCb(vnode.elm, listeners)
      }
      // recursively invoke hooks on child component root node
      if (isDef(i = vnode.componentInstance) && isDef(i = i._vnode) && isDef(i.data)) {
        removeAndInvokeRemoveHook(i, rm)
      }
      for (i = 0; i < cbs.remove.length; ++i) {
        cbs.remove[i](vnode, rm)
      }
      if (isDef(i = vnode.data.hook) && isDef(i = i.remove)) {
        i(vnode, rm)
      } else {
        rm()
      }
    } else {
      removeNode(vnode.elm)
    }
  }
```

**Comment by mightyiam** [comment]
Marked this as a question and closing because seems answered and not activity for more than a year.
