### ISSUE TITLE
Some nodes not delay-removed when `transition-property: all`

### ISSUE THREAD

**Issue by SkaterDad** [snabbdom/snabbdom#38]
While doing some tests, I noticed that DOM nodes don't get removed after transitioning when I define the transition-property as 'all' instead of the more specific properties (I know it's lower perf, but I like being lazy during testing).

Is it correct to assume that checking the specific property transitionend events is what allows the library to wait for all of them to complete before node removal?

**Comment by paldepind** [comment]
> Is it correct to assume that checking the specific property transitionend events is what allows the library to wait for all of them to complete before node removal?

Yes. That is correct. [It uses the `transition-property` value](https://github.com/paldepind/snabbdom/blob/master/modules/style.js#L49).

**Comment by mightyiam** [comment]
Supporting `all` would be more added code than seems reasonable for the benefit convenience of using `all`.
