### ISSUE TITLE
toVNode doesn't parse SVGs correctly

### ISSUE THREAD

**Issue by michael-england** [snabbdom/snabbdom#388]
`toVNode` doesn't account for namespace when parsing an SVG.  The resulting vnode is missing `data.ns` causing it not to get patched correctly, resulting with the SVG not rendering.

Here's a fiddle demonstrating this behavior: http://jsfiddle.net/michael_england/07pqtbfu/47/

Uncommenting the lines to manually add `data.ns` fixes this, but manually adding them shouldn't be required.  Seems like any fix should account for the SVG not being a root node.

**Comment by mreinstein** [comment]
I'm running into this problem when I attempt to inline svg into my app with snabbdom. manually updating the `vnode.data.ns = 'http://www.w3.org/2000/svg'` value in my code doesn't seem to solve the problem. Wondering if the code changed such that this workaround in the fiddle is no longer effective.

Help please? :(

**Comment by macarc** [comment]
This needs to be added to line 26 of `tovnode.ts`
```ts
const data = { attrs };
if (
    sel[0] === 's' && sel[1] === 'v' && sel[2] === 'g' &&
    (sel.length === 3 || sel[3] === '.' || sel[3] === '#')
  ) {
    addNS(data, children, sel)
  }
    return vnode(sel, data, children, undefined, node)
```

(Copied from the end of `h`)
I think that fixes it, but I can't check right now.

**Comment by macarc** [comment]
That does indeed fix it. @mightyiam OK for me to go ahead and submit a PR with this?

**Comment by toSayNothing** [comment]
@mightyiam hello, do you have a plan to fix it? or can I submit a PR with @macarc 's code?😅

> This needs to be added to line 26 of `tovnode.ts`
> 
> ```ts
> const data = { attrs };
> if (
>     sel[0] === 's' && sel[1] === 'v' && sel[2] === 'g' &&
>     (sel.length === 3 || sel[3] === '.' || sel[3] === '#')
>   ) {
>     addNS(data, children, sel)
>   }
>     return vnode(sel, data, children, undefined, node)
> ```
> 
> (Copied from the end of `h`) I think that fixes it, but I can't check right now.

**Comment by macarc** [comment]
Ha, I forgot about this entirely. I'll make a PR shortly.
