### ISSUE TITLE
Can't use example code with TS

### ISSUE THREAD

**Issue by jethrolarson** [snabbdom/snabbdom#391]
```typescript
import h from 'snabbdom/h';
const foo = (x: number) => x;
const x = h('a', {on:{ click: [foo, 1]}}, 'hi');
```

```
Argument of type '{ on: { click: (number | ((x: number) => number))[]; }; }' is not assignable to parameter of type 'VNodeData'.
  Types of property 'on' are incompatible.
    Type '{ click: (number | ((x: number) => number))[]; }' is not assignable to type 'On'.
      Type '{ click: (number | ((x: number) => number))[]; }' is not assignable to type '{ "abort"?: ((ev: UIEvent) => void) | undefined; "activate"?: ((ev: Event) => void) | undefined; "beforeactivate"?: ((ev: Event) => void) | undefined; "beforecopy"?: ((ev: Event) => void) | undefined; ... 106 more ...; "wheel"?: ((ev: WheelEvent) => void) | undefined; }'.
        Types of property '"click"' are incompatible.
          Type '(number | ((x: number) => number))[]' is not assignable to type '(ev: MouseEvent) => void'.
            Type '(number | ((x: number) => number))[]' provides no match for the signature '(ev: MouseEvent): void'.
```

Looks like the type of snabbdom/modules/eventlisteners `On` doesn't allow for the pair usage that's described in the documentation.

**Comment by kay999** [comment]
I can confirm that. The TS def in eventlisteners.d.ts is

```
export type On = {
  [N in keyof HTMLElementEventMap]?: (ev: HTMLElementEventMap[N]) => void
} & {
  [event: string]: EventListener
};
```
which is much to limiting.

A temporary fix is to change it into 

```
export type On = { 
    [event: string]: any[] | ((...args:any[]) => void);
}
```

which may be a little bit to broad but at least it works.

**Comment by jvanbruegge** [comment]
The overloaded eventlisteners were removed in an earlier version

**Comment by jethrolarson** [comment]
Unless I'm misunderstanding, it looks like the docs haven't been updated to match yet https://github.com/snabbdom/snabbdom#the-eventlisteners-module

**Comment by jethrolarson** [comment]
I'm also perplexed by that change since as it's said in the docs:
> Very often, however, you're not really interested in the event object itself. Often you have some data associated with the element that triggers an event and you want that data passed along instead.

I'm not seeing how the new api enables the value that the old one had of in-essence partially applying the event handlers while still allowing them to be shared.
