### ISSUE TITLE
Error: insertBefore when reusing vnodes

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#395]
Reproducable example:
```js
var sharedNode = h('div', {}, 'Selected');
var vnode1 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, ['Two']),
  h('div', {}, [sharedNode]),
]);
var vnode2 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, [sharedNode]),
  h('div', {}, ['Three']),
]);
patch(vnode0, vnode1);
patch(vnode1, vnode2);
```
This example crashes on the second `patch`.
The reason is that when the actual DOM node for `sharedNode` on position two is created, it assigns it as `vnode.elm`. The `vnode` is still that same `sharedNode`, that the third node still has a reference to (as it is not yet processed). When the third node gets created, it tries to do `insertBefore` with `vnode.elm` which is **not** the actual elm from the last patch (on position 3), but the new dom node of `sharedNode` created in **this** patch (position 2). Thus the `insertBefore` crashes as the element is not a child of the parent of the third node.

Note that this issue only happens in this direction (first insert, then remove) if you swap the two patches this does not happen, as first the node gets removed (and thus the reference) and then a new one gets inserted

This is the cause for https://github.com/cyclejs/cyclejs/issues/713

I am not sure what is the best way to solve this.

**Comment by jvanbruegge** [comment]
The only solution that I can think of is assigning the vnodes to a new property `_elm` and after all patching is done, traversing the tree again and assigning them to `elm`, but obviously this comes at a huge performance cost.

**Comment by jvanbruegge** [comment]
Another solution would be copying vnodes to get rid of equal references which is also expensive

**Comment by jvanbruegge** [comment]
If noone finds a better solution I would add a section to the README with something like
<hr>
## Common Errors
`insertBefore: node is not a child ...`
This is caused when vnodes have the same reference (aka are the exact same object) as vnodes in the last patch. Solution: do not reuse vnodes like here:
```js
var sharedNode = h('div', {}, 'Selected');
var vnode1 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, ['Two']),
  h('div', {}, [sharedNode]),
]);
var vnode2 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, [sharedNode]),
  h('div', {}, ['Three']),
]);
patch(vnode0, vnode1);
patch(vnode1, vnode2);
```

**Comment by paldepind** [comment]
Snabbdom does not allows reusing vnodes like that as it stores the DOM elements in the vnodes for performance reasons.

Adding a section like that to the readme is a great idea :+1:

**Comment by jethrolarson** [comment]
It's sad that referential transparency can't be maintained but I guess performance is king
