### ISSUE TITLE
Add CI with Browserstack

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#396]
@paldepind to have everything here
AFAIK @staltz was made owner of an organization in Browserstack, so he could sent me an invitation link. I then added a bot account (one-time-use-email + some password I saved) to not use my personal account in the CI. I would suggest you too add a Bot user and email me the credentials of it.

Then I changed the browser tests from testem to karma. This is not 100% needed, but karma makes debugging (with or without browserstack) easier.

Other than that you would have to add travis as github app. The rest I can do via PR

**Comment by paldepind** [comment]
@jvanbruegge I've sent you an invitation to the email in your GitHub profile 👍

**Comment by jvanbruegge** [comment]
@paldepind I accidently removed myself from the org, can you add me again?

**Comment by paldepind** [comment]
Sure, no problem :smile: I've sent another invite to the email address in your GitHub profile.

**Comment by jvanbruegge** [comment]
Thanks
