### ISSUE TITLE
htmldomapi.ts doesn't work under Node.js environment

### ISSUE THREAD

**Issue by minamorl** [snabbdom/snabbdom#404]
I'm writing a framework based on snabbdom and using testing framework under Node.js environment with JSDOM. The problem is occured inside of `patch` function here: https://github.com/minamorl/micox/blob/4c6b20a492de6e21071092689357a9b59edb813e/src/index.ts#L50
Then I debugged and figured out this is the issue of `htmldomapi.ts`.

```ts
function createElement(tagName: any): HTMLElement {
  return document.createElement(tagName);
}

function createElementNS(namespaceURI: string, qualifiedName: string): Element {
  return document.createElementNS(namespaceURI, qualifiedName);
}

function createTextNode(text: string): Text {
  return document.createTextNode(text);
}

function createComment(text: string): Comment {
  return document.createComment(text);
}
```

The code above is using `document` object directly, but Node.js doesn't have the object in `global` so these functions aren't working correctly. I wish there was a solution like dependency injection.
My current solution is to use `jsdom-global` but this is obviously not good solution.
Or is there any good solution for this?

**Comment by jvanbruegge** [comment]
yes, this should be done by creating your own `DOMAPI` with `init`
