### ISSUE TITLE
Q: wysiwyg editor or using third party libraries

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#411]
I would like to add a WYSIWYG editor to my snabbdom application. My google-fu failed me, so I am asking here.

Is there a how-to guide use third-party libraries inside a snabbdom?

Thanks in advance!

**Comment by amirouche** [comment]
My question is how to embed such a mutable compomnent inside a snabbdom app.

**Comment by mightyiam** [comment]
I don't know what a snabbdom app is... I use snabbdom in the context of Cycle.js, for example.
