### ISSUE TITLE
Props are not reseted properly

### ISSUE THREAD

**Issue by batiste** [snabbdom/snabbdom#415]
I would like to know if this is a bug or is it the intended behaviour:

https://codesandbox.io/s/ppn1y5okjq

Please enlighten me about how to use snabbdom. I use it for little toy language here https://github.com/batiste/blop-language and I am running into funny bugs

**Comment by mightyiam** [comment]
I don't use the `props.className`. I use the class module:
https://github.com/snabbdom/snabbdom#the-class-module

**Comment by batiste** [comment]
@mightyiam hummm oki but is there an explanation for this behaviour? Should I expect the same thing for other props? This is a scary and look like a bug no?

**Comment by mightyiam** [comment]
@batiste it seems that the props module does not remove props when they are not specified. This is probably expected behavior. To "remove" a prop, set it to the empty string or whatever is correct to do.

**Comment by batiste** [comment]
I thought it was the job of snabbdom diff algorithm to do that for me.

I cannot "remove a prop" by setting an empty string because I have no idea which node is what and frankly in my app they are completely different VNodes that have nothing in common with each other. But snabbdom seems to have decided to recycle those VNode because they are similar or have more or less the same position in the tree... But then it doesn't reset the props?

I am just very surprised I am the first to run into those issues as it seems such a basic need...

**Comment by batiste** [comment]
Also if I read this code right:

https://github.com/snabbdom/snabbdom/blob/master/src/modules/props.ts#L16-L20

It seems that the old props should be deleted from the element itself? But it doesn't quite work?

**Comment by blikblum** [comment]
This will work:
`h("div", { props: { className: "" } }, "expected black"),`

className is a special property, it cant be deleted

**Comment by batiste** [comment]
@blikblum oki but look at id for example here: https://codesandbox.io/s/2x7nrlk23j

This is the same thing. Id is not deleted.

**Comment by blikblum** [comment]
id is also special

**Comment by mightyiam** [comment]
Regarding recycling of VNodes, perhaps the `key` property could help.
https://github.com/snabbdom/snabbdom/blob/master/README.md#key--string--number

**Comment by batiste** [comment]
I mean the key does help but it is a ridiculous requirement. I will not add a Math.random() of each elements so the props are reseted...

I got the behaviour I wanted using the attributes module though. Props seems more about storing data onto the VNodes? I am not quite sure.

@blikblum what about href?
https://codesandbox.io/s/409513z0zx

Every-time I try a prop, the behaviour is the same. Is there really a prop that is properly reseted on the Native DOM? If it is the case I would be glad to know about it.

**Comment by blikblum** [comment]
These native dom properties probably are defined as accessors so could not be deleted

Maybe this should work:

```
for (key in oldProps) {
    if (!props[key]) {
      (elm as any)[key] = undefined
      delete (elm as any)[key];
    }
}
```
I suggest doing a PR with a test if it fix your problem

**Comment by batiste** [comment]
With something like `(elm as any)[key] = undefined` you end up with `<div id='undefined'>`. AFAIK the only proper way to remove an attribute from a DOM node is to use the `removeAttribute` method.

**Comment by blikblum** [comment]
So you should use attrs module not props

**Comment by batiste** [comment]
@blikblum I agree but then why is the prop module is advertised in the README? Who is using it and for what purpose?

**Comment by batiste** [comment]
Here is a PR https://github.com/snabbdom/snabbdom/pull/416

**Comment by mightyiam** [comment]
#624
