### ISSUE TITLE
Development workflow seems broken

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#428]
The expected workflow:
1. `git clone`
1. Select Node.js version that the project expects
1. `npm install --global npm`
1. `npm install`
1. `npm test`

Fails.

I would say that this issue depends on

- [x] #422
- [x] #424
- [x] #426
- [x] #322
- [x] #460
- [ ] #473

**Comment by kuraga** [comment]
@mightyiam , seems like all four issues are fixed ATM...

**Comment by mightyiam** [comment]
Thank you, @kuraga. Yes, but there is #460.
