### ISSUE TITLE
The typescript declaration for eventlisteners only supports function listeners

### ISSUE THREAD

**Issue by kay999** [snabbdom/snabbdom#431]
The TS def in eventlisteners.d.ts is

```
export type On = {
  [N in keyof HTMLElementEventMap]?: (ev: HTMLElementEventMap[N]) => void
} & {
  [event: string]: EventListener
};
```
which is much to limiting.

A temporary fix is to change it into 

```
export type On = { 
    [event: string]: any[] | ((...args:any[]) => void);
}
```

which may be a little bit to broad but at least it works.

_Originally posted by @kay999 in https://github.com/snabbdom/snabbdom/issues/391#issuecomment-478296040_

**Comment by nojvek** [comment]
Do you have concrete examples on why you need the broad listener?

**Comment by kay999** [comment]
I often use the extended features of eventlisteners like arrays of functions etc. For example

```
{ on:{ [[stop], [select, index]] }}
```

which first calls 'stop' (which simply calls ev.preventDefault()) and then if calls select(index) with the current selected element.

**Comment by mightyiam** [comment]
This seems to be a bug where the interface does not fully represent the feature-set.

**Comment by mightyiam** [comment]
Thank you for filing this, @kay999. I've broken it down to these 3 type deficiencies and closing in favor of them:

- #794 
- #795 
- #796
