### ISSUE TITLE
Thunk-like approach by default for diffing

### ISSUE THREAD

**Issue by whitecolor** [snabbdom/snabbdom#434]
`Thunk`  works that way it allows to avoid unnecessary diffs by explicitly telling it that vnode actually didn't change.

What would be if VDOM library just behaved that way by default, meaning that if VNode object actually is the same with the previous one (`===`) it would not do the diff. 

What would be the problem with such an approach? Wouldn't it just speed up things?

@paldepind

**Comment by staltz** [comment]
@whitecolor I think that's already the case: https://github.com/snabbdom/snabbdom/blob/ff594946493cf84eff52ae28b6d6e9ff22017c19/src/snabbdom.ts#L261

**Comment by whitecolor** [comment]
@staltz hm, ok, so then `thunk` is not so useful thing as it may seem )
