### ISSUE TITLE
open to a PR that updates all README examples to es modules?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#437]
using commonjs is a pattern that the community is trying to move away from. Given snabbdom already supports es modules, would you be open to a PR that stops referencing `require` in the `README.md` in favor of esm? Would look something like this for the inline example:

```javascript
import { h, init } from 'snabbdom';
import classModule from 'snabbdom/modules/class';
import propsModule from 'snabbdom/modules/props';
import styleModule from 'snabbdom/modules/style';
import eventModule from 'snabbdom/modules/eventlisteners';


// Init patch function with chosen modules
const patch = init([
	classModule,  // makes it easy to toggle classes
	propsModule,  // for setting properties on DOM elements
	styleModule,  // handles styling on elements with support for animations
	eventModule   // attaches event listeners
]);
```

Happy to send a PR if this is a welcome addition!

**Comment by kuraga** [comment]
Seems like it's better to [wait for a decision](https://github.com/snabbdom/snabbdom/pull/247) first... :(
