### ISSUE TITLE
How about not tracking `dist` in VCS?

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#481]
I feel against tracking build artifacts in VCS.

**Comment by mreinstein** [comment]
`prepublishOnly` npm event is probably the right place to generate the dist directory

**Comment by kuraga** [comment]
IMHO `type:bug` -> `type:enhancement` should be relabeled...

**Comment by mreinstein** [comment]
depends on how you define an enhancement. This particular task is probably not much more work than would be required to adjust the labeling of it. :) Might be time better spent to just complete it.
