### ISSUE TITLE
Discussion: Roadmap

### ISSUE THREAD

**Issue by nojvek** [snabbdom/snabbdom#486]
This PR has 92 open issues and 24 open pull requests. 

I see @mightyiam also has a bunch of PRs for chores. 

Should we discuss a rough game plan. How we want to manage issues / PRs. Close things we probably wouldn't act on e.t.c

Perhaps even a statement of what snabbdom is and isn't and what kinds of things we'll accept and won't. 

Rough response SLA e.t.c

**Comment by mightyiam** [comment]
Thank you for the suggestion, @nojvek. Here are some points to touch:

- Quote the project description: "A virtual DOM library with focus on simplicity, modularity, powerful features and performance."
- Explain what simplicity means in terms of the API. That we're not looking for more API surface or magic defaults. Suggest publishing additional functionality as third party modules.
- Ask for features to be suggested before providing pull requests.
- Regarding bugs, that they should be discussed individually on their respective issues in the tracker.

Regarding existing issues and pull requests, I'm personally going to work my way through them and do what I feel is right. That feels to me like more value than being too careful and not accomplishing much.

**Comment by nojvek** [comment]
Gonna close this then.

Seems we're pretty aligned.

**Comment by mightyiam** [comment]
@nojvek not the most well formed perhaps but maybe better than nothing: #488
