### ISSUE TITLE
can we npm publish a new version?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#495]
I noticed that the git commits from the last year-ish aren't available in npm yet. Is this intentional (as in waiting for some particular commits to land) or are people just swamped with other tasks?

**Comment by mightyiam** [comment]
Published v0.7.4.

**Comment by paldepind** [comment]
Thank you @mightyiam.

**Comment by mreinstein** [comment]
Thank you @mightyiam !  Are there release notes for 0.7.4? The last one i saw with release notes is 0.7.2

**Comment by mightyiam** [comment]
@mreinstein we don't yet have release notes. #500 .
