### ISSUE TITLE
Whether to remove JSX support (which, BTW, is not yet documented)

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#497]
@nojvek @paldepind following up from https://github.com/snabbdom/snabbdom/pull/494#issuecomment-564396758.

Personal context: I don't use JSX.

I don't have much either way. Perhaps slightly towards it being an individual package. Especially if the author of this module feels this way.

**Comment by kuraga** [comment]
But what to remove?
1. `null` support in `h`?
2. `jsx` function + tests + docs?
3. JSX example (i.e. to transform `jsx` -> `h`)?

**Comment by mightyiam** [comment]
As @nojvek suggested, all but the `null` child in `h` support. That's what I would suggest.

**Comment by kuraga** [comment]
Well then vote :-1: to this decision.

There are a lot of modules in Snabbdom. This is just a next one. "Compile time" module. Important: it's lightweight. That's about my p.2.

About p.3: I think it's not a difference: `h` vs `jsx`, it's just an example.

P.S. But if we want to move Snabbdom's modules out of the main package... Then yes: we should move this, too.

**Comment by nojvek** [comment]
1) is null attr support (not null child)
2 & 3 go together. You don’t want to have code undocumented. 


I’m 👍 for 1 (keeping it) and 👎 for 2&3 (remove it).

**Comment by paldepind** [comment]
> There are a lot of modules in Snabbdom. This is just a next one. "Compile time" module. Important: it's lightweight. That's about my p.2.

I agree with this. To me the `h` function and the `jsx` function are almost equal. They're both an optional way to create virtual DOM. Supporting JSX directly doesn't seem like a huge task to me and I'm fine with having it in the main repo.

**Comment by nojvek** [comment]
Sounds good. I’ll do the remaining tasks for #494 then.

**Comment by kuraga** [comment]
> To me the `h` function and the `jsx` function are almost equal. They're both an optional way to create virtual DOM.

Strictly saying I disagree. `document.createElement`/etc. is a low-level way, `h` is a high-level (main of Snabbdom) way. But `jsx` is just a wrapper.

So as I said, it's a "module"/"plug-in". But we have such "modules" (they are [Snabbdom's modules](https://github.com/snabbdom/snabbdom#modules-documentation)) so that's ok IMHO.

**Comment by mreinstein** [comment]
I don't know if this helps, if this is noise feel free to ignore, but I've recently picked up maintenance responsibilities for snabby, which is a very light wrapper for snabbdom and hyperx: https://github.com/mreinstein/snabby

I bring this up to say whatever extent the built-in jsx snabbdom overlaps this functionality, happy to make changes and open for suggestions on collab.
