### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#500]

**Comment by mreinstein** [comment]
Could you clarify the purpose of this issue? Is it release notes for a specific version, or is this just saying "in general we should have release notes" ?

**Comment by kuraga** [comment]
My opinion: we have to release a stable version and then - in general we should have release notes (equal to changelog).

**Comment by mightyiam** [comment]
I intend to use https://github.com/conventional-changelog/standard-version to generate and update a changelog. That's what I meant. Not release notes...

**Comment by mreinstein** [comment]
I see there is now a changelog.md. I suppose we can close this now :)

**Comment by mightyiam** [comment]
Yes. Thank you!
