### ISSUE TITLE
Remove the hero module

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#517]
Out of all of the [modules](https://github.com/snabbdom/snabbdom/tree/v0.7.4/src/modules) to me stands out the hero module as being too specific. I feel it shouldn't be in this project.

**Comment by mreinstein** [comment]
maybe we could move this to the `examples/hero/` directory. I think it's a reasonable module, I just suspect that it's not something people are actually using in their own code. Probably shouldn't be a built-in module.

**Comment by mightyiam** [comment]
Yes. Move to examples. Good idea.
