### ISSUE TITLE
Export a ready-to-use `patch` function which includes a default set of modules

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#518]
Following up from https://github.com/snabbdom/snabbdom/issues/194#issue-190062119.

I'm :-1: this suggestion.

**Comment by mreinstein** [comment]
I agree with @mightyiam  on this, I think the better solution is to export everything from the main 'snabbdom' module as discussed in #913 

I think snabbdom was always intended as a very low level module that other people could build their own stuff on top of, and it makes sense to keep it that way.
