### ISSUE TITLE
Rename class module to classList

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#521]
Suggested in https://github.com/snabbdom/snabbdom/issues/194#issue-190062119.

**Comment by mreinstein** [comment]
I guess I don't understand why do this. If I'm reading that ticket right, this is purely for aesthetics? If so, can we avoid breaking the existing api for better looks? Having to update all of the code in production that already works for a better looking name is not super desirable.

**Comment by jvanbruegge** [comment]
I also don't think this is very useful, `class` is only a keyword as beginning of a statement, so it does not clash
