### ISSUE TITLE
@zymfe thank you for the pull request. It seems that some tests a failing. Perhaps `before` is sometimes not `null`?

### ISSUE THREAD

**Issue by zymfe** [snabbdom/snabbdom#545]
@zymfe thank you for the pull request. It seems that some tests a failing. Perhaps `before` is sometimes not `null`?

_Originally posted by @mightyiam in https://github.com/snabbdom/snabbdom/pull/544#issuecomment-574549625_

yes, you are right.

**Comment by paldepind** [comment]
It seems that this should have been a comment in #544 and not a separate issue.

I'm closing.
