### ISSUE TITLE
Github issues: add some labels, please

### ISSUE THREAD

**Issue by kuraga** [snabbdom/snabbdom#551]
@paldepind , @mightyiam , @nojvek let's add `type:rfc`/`type:architecture` label for github issues, please. To highlight issues about architecture of Snabbdom. Thanks!

P.S. And `documentation`, `tests`, `packaging`, `development process` (i.e. _this_ issue), maybe...

**Comment by kuraga** [comment]
P.S. And `documentation`, `tests`, `packaging`, `development process` (i.e. _this_ issue), maybe...

**Comment by mightyiam** [comment]
Thank you for the suggestions, @kuraga. I personally don't like the overhead that adhering to this would impose. I feel it doesn't justify itself. And recently I have been the only issue-maintenance contributor, so I feel like I should just say no to this. I hope it's OK with you. Unless... you would like to step through the existing issues and apply these labels yourself, you'll forgive me if I close this at this point.
