### ISSUE TITLE
support array of elements without needing a wrapper div

### ISSUE THREAD

**Issue by jimfranke** [snabbdom/snabbdom#560]
Does Snabbdom has support for JSX fragments to return an array of elements? If not, is this on the roadmap, or what does it take to implement it? Thanks.

**Comment by mightyiam** [comment]
@jimfranke thank you for your interest. Could you please describe an API for this?

**Comment by jimfranke** [comment]
Basicly it comes down to a component being able to return an array of elements which are then flattened into the parent component, without the need for a wrapping div. The diff algorithm needs to support array based diffs for this. See https://reactjs.org/docs/fragments.html for an example.

**Comment by Leland-Kwong** [comment]
This would be nice. I recently setup my own implementation by doing a patch on the fragment's parent vnode and replacing the old children with the new ones. Its not the most ideal, but it works reasonably well.

**Comment by jimfranke** [comment]
@Leland-Kwong Can you share your implementation and does it have any downsides patching the parent?

**Comment by Leland-Kwong** [comment]
@jimfranke Turns out theres a much simpler solution. The way I've done it is to auto-flatten the children in my vnode factory function. As an example:

```js
const vnodeFactory = (selector, props, children) => {
  return {
    sel: selector,
    children: children.flat(Infinity)
  }
}

const vtree = vnodeFactory('div', [1, [1,2,3]]);
```

The only caveat is this doesn't work for the root vnode. I'd imagine you can also have it work for the root vnode by creating based off of the initial dom node that you're patching to.

**Comment by nojvek** [comment]
If you use https://github.com/nojvek/snabbdom-jsx-lite

Fragment support comes out of the box. I really would have loved to not create a new npm module but land snabbdom jsx support here but @paldepind has been AWOL for so long, it was better to create a new module.

https://github.com/nojvek/snabbdom-jsx-lite#jsx-fragments

**Comment by mreinstein** [comment]
@jimfranke I renamed the issue in an attempt to make it more accurate in terms of what is being asked for.

If I've got this wrong I'm happy to change it back though. Definitely not looking to re-write history here.

**Comment by ryota-ka** [comment]
Hi @jimfranke, I've submitted #974 that introduces a support for JSX fragments.
Hope it'll be merged and meet your needs.
Feedback welcomed!
