### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#567]
@paldepind and community, with some funding, I would be able to dedicate much more time to snabbdom development.

If @paldepind and I create an Open Collective for snabbdom, would anyone chip in? For an example that some of us may relate to, here is the [Cycle.js Open Collective](https://opencollective.com/cyclejs). Take a look at how they are [spending their collected funds with transparency](https://opencollective.com/cyclejs/expenses). I feel we could do the same.

**Comment by Leland-Kwong** [comment]
I'd be interested in chipping in.

**Comment by mightyiam** [comment]
@Leland-Kwong and anyone who is willing to back development is welcome to do so via [our open collective](https://opencollective.com/snabbdom#section-contribute).
