### ISSUE TITLE
ES module does not export types, ie VNode

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#568]
Prompted by https://github.com/cyclejs/cyclejs/issues/925 I wanted to switch to ES module only, but AFAICT it is not possible to import the types, ie `VNode` from the es module.

**Comment by kuraga** [comment]
@jvanbruegge , #225?

**Comment by jvanbruegge** [comment]
not really because it is just plain missing

**Comment by kuraga** [comment]
@jvanbruegge , similar to #319?

**Comment by mightyiam** [comment]
@jvanbruegge is this what you're looking for?

https://unpkg.com/browse/snabbdom@0.7.4/es/vnode.d.ts

```ts
import { VNode } from 'snabbdom/es/vnode.js'
```

Please confirm whether this works for you.

**Comment by mightyiam** [comment]
It is now

```js
import { VNode } from 'snabbdom/vnode'
```

If there are any more issues, please let me know.
