### ISSUE TITLE
perf/index.html requires build.js

### ISSUE THREAD

**Issue by garth** [snabbdom/snabbdom#58]
There is no script in the package.json to generate build.js an no obvious way to create it.

**Comment by garth** [comment]
Tried running perf/benchmarks.js through webpack, but there are all kinds of warnings and missing dependencies. By looking at the output I would guess that there is a vendor dir missing from the repo.

**Comment by paldepind** [comment]
The `build.js` file can be created by running `browserify.js -o build.js`. To do that there must be a file named `oldsnabbdom.js` in the root. Running the benchmark should then indicate which of the two versions are the fastest.

I admit that this is not really documented.
