### ISSUE TITLE
How is `build.js` under the `example/hero/*` folder generated?

### ISSUE THREAD

**Issue by zgj233** [snabbdom/snabbdom#621]
Excuse me. Where is this configuration file for webpack?

**Comment by mightyiam** [comment]
Thank you for your interest, @zgj233. There is no such configuration file. This is a known issue #263. It has a proposed solution in #601. Running the examples in that branch is as trivial is running `npx serve`.

I will close this issue, but if you have any other questions, please feel free to ask.
