### ISSUE TITLE
what is mean '?.'

### ISSUE THREAD

**Issue by wbbhacker** [snabbdom/snabbdom#622]
const key = children[i]?.key;

What is the use '?.'

**Comment by mightyiam** [comment]
Hi, @wbbhacker. Thank you for your interest in snabbdom.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

I'll close this issue, but if you have any other questions, please feel free to ask.

**Comment by wbbhacker** [comment]
thx
