### ISSUE TITLE
Is there any place where we catalog snabbdom-compatible UI components?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#640]
I'm starting to build up a catalog of pure snabbdom based UI elements, and I'm wondering if:

a) we have any place where we collect/share these
b) anyone else out there building snabbdom elements that are shareable

to give an example, here is one I've been working on very recently, exposing a chrome devtools inspired, re-usable timeline component:

https://github.com/mreinstein/snabbdom-timeline

If we don't have one, maybe something like https://bit.dev/ could be used to curate a collection of high quality ui components?  Thoughts?

**Comment by mreinstein** [comment]
some more modules:

https://github.com/mreinstein/snabbdom-drawer

https://github.com/mreinstein/snabbdom-property

**Comment by mreinstein** [comment]
https://github.com/mreinstein/snabbdom-tabs

**Comment by mreinstein** [comment]
https://github.com/mreinstein/snabbdom-valve

**Comment by paldepind** [comment]
Those can be added to the readme in [this section](https://github.com/snabbdom/snabbdom#structuring-applications). It would probably be a good idea to re-structure that section with a few sub-sections etc.

**Comment by mightyiam** [comment]
How about in a wiki here in the repo?

**Comment by mreinstein** [comment]
The github wikis don't get much traffic and they often end up being neglected. It might be better to just put them in a markdown file in the project root.

**Comment by mreinstein** [comment]
https://github.com/mreinstein/snabbdom-knob
