### ISSUE TITLE
Event listening improvements

### ISSUE THREAD

**Issue by katyo** [snabbdom/snabbdom#69]
I offer some improvements for event handling:
1. Virtual events which eliminates different behavior between user-agents.
2. Listening events only on root node to reduce number of DOM API calls.

Are there any ideas about it?
Of course I haven't implemented this at current time, but I can help to do this, if it's really necessary.

**Comment by AlexGalays** [comment]
I dislike both ideas. virtual events are not useful for remotely modern browsers. The performance improvement of listening on the root node only is actually a poor optimization that increase bloat since you have to create hooks for elements instead of native event handlers.

**Comment by paldepind** [comment]
These features are not important for me (which is why they are not in Snabbdom already). But I understand that they are useful in certain use cases.

The Snabbdom core does not handle events at all. I _think_ that these features could be implemented as new Snabbdom event module. And doing that would be very interesting.

**Comment by katyo** [comment]
In case of huge number of nodes, each of which requires own listener, we inevitably will have a drawdown of performance. And the reason of this behavior is a nature of a DOM API, not a browser implementation.

**Comment by leeoniya** [comment]
Hey guys, fly on the wall here :)

First, @paldepind snabbdom is an awesome vdom lib...i've evaluated many others and most have awkward ergonomics or are slow. I'm very impressed with how much it can do performance for its size.

Second, @katyo, @AlexGalays you guys may consider evaluating domvm [1]. It's not a pure vdom lib but sits somewhere between Mithril and and domchanger/snabbdom. It addresses many issues/use-cases I've been seeing crop up repeatedly in the vdom landscape, including this event delegation one. @paldepind, feel free to steal any good ideas from domvm if you find any which fit snabbdom, though I think architecturally they're pretty different but template ergonomics are similar.

cheers!

[1] https://github.com/leeoniya/domvm

**Comment by AlexGalays** [comment]
@katyo  Did you benchmark it? "Huge number of nodes" is probably a bad sign in the first place; this is usually seen in big lists where windowing/occlusion culling/infinite scrolling should be implemented in the first place. I just can't see this ever being a bottleneck; Modern browsers manage to set a simple reference to a event handler function on every node just fine; the overhead is minuscule. Not to mention event delegation brings its lot of problems with it like akward event stopPropagation behavior.

**Comment by leeoniya** [comment]
@AlexGalays 

> "Huge number of nodes" is probably a bad sign in the first place; 

except of course when you *need* a huge number of nodes...like a 10k cell spreadsheet grid [1].

[1] http://leeoniya.github.io/domvm/test/bench/patch/

**Comment by AlexGalays** [comment]
You never need a huge number of nodes. It's always a very bad idea. You would have to pay the cost of building a monster vdom every repaint, the browser wouldn't like it very much either (layout and GC)
On google spreadsheet with a MacBookPro 15' I can only see 14*25 = 350 cells; No need to render many more than that. Your 10k cell spreadsheet is fine as a benchmark, not as an example of a real life scenario that demands event delegation.

**Comment by leeoniya** [comment]
Fair point, but a couple notes.

In the bench there is no full vtree rebuild, that would be ridiculous. This bench specifically shows the individual vnode patching functionality which just runs the diff on the explicit cell you ask it to.

The complexity and payload difference between being able to just render a huge table and implementing multi-axis culling code for tabular data is enormous. If you can have performance and simplicity, then why not?

**Comment by AlexGalays** [comment]
Fair point too :)
