### ISSUE TITLE
Usage with Rollup for >= 1.0.0

### ISSUE THREAD

**Issue by doesdev** [snabbdom/snabbdom#703]
I'm sure I was overlooking something stupid, but then again #601 seems to imply this may have been a known choice in the design. All the same, I couldn't get it working with Rollup so I made [this terrible hack](https://github.com/doesdev/rollup-plugin-resolve-snabbdom). Just curious if there is a more proper method I've missed.

**Comment by mightyiam** [comment]
I've never used rollup. Could you please provide me with some error message from rollup?

Also, take a look at the available exports, here:

https://github.com/snabbdom/snabbdom/blob/46a33fa5ecf6abdef06deecd682e1c9d7f375c8f/package.json#L6-L25

**Comment by kedashoe** [comment]
I was trying to understand this as well.

It looks like rollup does not support the `exports` field yet, see the last paragraph of this comment: https://github.com/rollup/plugins/issues/362#issuecomment-643668662

Seems to still work if you provide the "full path", eg `import { init } from 'snabbdom/build/package/init`, but of course that is not so nice. Mabye this is what your plugin helps with? I'm not sure there is anything snabbdom needs to do or should do though?

**Comment by doesdev** [comment]
Yes, that does seem to be the root problem. Not sure if it's a problem at the Rollup level or @rollup/plugin-node-resolve. Either way, as you said @kedashoe, the problem isn't with Snabbdom. I'll close this one

**Comment by mightyiam** [comment]
I recommend using

1. aliases in the bundler that imitate the `exports` field
1. official snabbdom import paths

And when the bundler supports the exports field ([webpack will soon](https://github.com/webpack/webpack.js.org/issues/3785)), remove the aliases and use the exports field feature.
