### ISSUE TITLE
Is there any place to import snabbdom from directly on the web?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#718]
I want to do something like this in my code:

```javascript
import { h } from 'https://cdn.jsdelivr.net/npm/snabbdom/h.js'
```

Any chance we could have a pure esm build that gets put somewhere? This would enable me to start using snabbdom without npm.

**Comment by mightyiam** [comment]
https://unpkg.com/snabbdom@1.0.1/build/package/h.js

But that URL is private. The public path, as specified in the `exports` field is, for example, `/h`:
https://unpkg.com/snabbdom@1.0.1/h

There seems to be no support for that field.

https://cdnjs.com/libraries/snabbdom

Most recent version is not listed.

https://cdn.jsdelivr.net/npm/snabbdom@1.0.1/build/package/h.js

Same problem -- no support for the `exports` field.

**Comment by mightyiam** [comment]
https://github.com/mjackson/unpkg/issues/265
https://github.com/jsdelivr/jsdelivr/issues/18215

I guess I could close this here.
