### ISSUE TITLE
Package 1.0.x content questions

### ISSUE THREAD

**Issue by whitecolor** [snabbdom/snabbdom#726]
Some notices/questions about the current package version.

1) Strange imports:

```ts
import { h } from `snabbdom/build/package/h`
```

I believe it is really not very convenient. What is the reason? BTW Readme not actual.

2) TS sources (src folder) are included in the published package. I'm not sure why people do this sometimes. But they (sources) should not be there.

3) In [package.json `files`](https://github.com/snabbdom/snabbdom/blob/master/package.json#L133) you keep the whole list of names. Why?

@mightyiam @staltz

**Comment by arashmilani** [comment]
This type of importing path makes breaking changes to the libraries depending on the snabbdom. Is it a missed bug that has been published unintentionally?

**Comment by whitecolor** [comment]
Yes, there seems no reason to change the exiting module access API.

**Comment by mightyiam** [comment]
Thank you, @whitecolor.

1. The import paths in the readme are the official ones. They rely on [the exports field](https://nodejs.org/api/esm.html#esm_package_entry_points).
2. The source maps refer to them. They are necessary for debugging with source maps.
3. Specifying every package file explicitly clarifies what it intended to be included in the package. It also prevents any other files from finding their way into the package. And while it is a long list, it is simple.

**Comment by mightyiam** [comment]
Regardless, there have been some breaking changes regarding import paths. Please see the change log for references, pull requests, discussions, etc.
https://github.com/snabbdom/snabbdom/blob/master/CHANGELOG.md

**Comment by whitecolor** [comment]
@mightyiam ok, that clarifies things, thanks. So waiting for TS to support package `exports`.

**Comment by mightyiam** [comment]
Thank you for the link, @whitecolor. I haven't looked into [TypeScript path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). Perhaps that feature could allow using Snabbdom's public import paths?

**Comment by whitecolor** [comment]
Yes, I believe adding this to `compilerOptions` 
```json
    "baseUrl": ".",
    "paths": {
      "snabbdom/*": ["node_modules/snabbdom/build/package/*"]
    }
```

would do the job. So it could be placed in docs.
