### ISSUE TITLE
Snabbdom 1.0 require breaks webpack build

### ISSUE THREAD

**Issue by mekane** [snabbdom/snabbdom#743]
I was using Snabbdom v0.7 in a project with webpack and not having any issues. I started a new project and when I did npm install I got version 1. I'm using the same webpack config (other than the project name) and it now fails with these errors:

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 1:17-36
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/modules/attributes' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 4:4-42
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/modules/class' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 5:4-37
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/modules/eventlisteners' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 8:4-46
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/modules/props' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 6:4-37
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/modules/style' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 7:4-37
 @ ./src/inBrowserApp.js

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/tovnode' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 2:16-43
 @ ./src/inBrowserApp.js

**Comment by mekane** [comment]
Okay, I saw that v1 introduced breaking changes, cool. So I grabbed the new imports from the README but I'm still getting these for every import from webpack:

> ERROR in ./src/view/browserView/index.js
Module not found: Error: Can't resolve 'snabbdom/init' in 'C:\Users\Me\Projects\my-app\src\view\browserView'
 @ ./src/view/browserView/index.js 1:13-37
 @ ./src/inBrowserApp.js

**Comment by mightyiam** [comment]
Thank you, @mekane for using snabbdom. Please see https://github.com/snabbdom/snabbdom/issues/723#issuecomment-653721314.
