### ISSUE TITLE
Sandbox module demand

### ISSUE THREAD

**Issue by grimalschi** [snabbdom/snabbdom#751]
Hello!

For my large project (website builder) I made a sandbox module.

It catches both Virtual DOM exceptions and Real DOM exceptions from executing code and instead of attaching virtual tree shows and error instead.

Using this I can give my users possibility to write they own code and to attach it in real time no matter what is inside code.

I want to publish it but not sure there is a demand. So just checking.

**Comment by mightyiam** [comment]
Thank you for sharing your work, @grimalschi. I'm not sure whether there's shareable value in this. What's the API?

**Comment by grimalschi** [comment]
Something like this

<img width="621" alt="Screenshot 2020-07-27 at 18 40 22" src="https://user-images.githubusercontent.com/9027592/88561888-ac8eb100-d038-11ea-9831-944c89c7617f.png">

**Comment by grimalschi** [comment]
By "untrusted" I don't mean just that code can throw any kind of exception. Not secure isolation.

**Comment by mightyiam** [comment]
What kinds of errors are we expecting?

**Comment by grimalschi** [comment]
Well, there is two areas of errors. First is virtual dom and second is a real.

First area error:
```
h('div, {}) // Stupid mistype, but can ruin app if goes production
```

Second area error:
```
patch(document.createElement('div'), h('div', {
  attrs: {
    "\"": "test"
  }
}))
```
Here virtual dom is correct, but patching it to real causes DOMException: Failed to execute 'setAttribute' on 'Element': '"' is not a valid attribute name.

**Comment by grimalschi** [comment]
You can successfully wrap with try-catch first type of errors and catch all errors before patch.

But second area (real dom exceptions) are hard to catch because they are coming **in the middle of patching**. So whole patching process becomes broken after this.

**Comment by mightyiam** [comment]
Why is the choice of handling these errors inside a snabbdom module?

**Comment by grimalschi** [comment]
Because this is part of virtual dom. Wrong approach?

**Comment by mightyiam** [comment]
Way too early for me to determine. What is the API that you provide your users?

**Comment by grimalschi** [comment]
There is no API for users. My users know nothing about snabbdom - they just edit HTML and CSS and whatever they are writing it will not go out sandbox.

![2020-07-29 18 16 27](https://user-images.githubusercontent.com/9027592/88818746-b8f54400-d1c7-11ea-90fa-b81fa18c8673.gif)

My app uses [snabbdom-virtualize](https://github.com/appcues/snabbdom-virtualize) also, but especially sandbox is just a module without dependencies.

**Comment by grimalschi** [comment]
What module does - is when on GIF I write "whatever" and code become broken, module shows an error div instead of dom, but when I am fixing this it shows dom again.

This is just an example of applying.

**Comment by mightyiam** [comment]
If your users provide HTML, then why don't you use `Element.innerHTML`? Why use snabbdom at all?

**Comment by grimalschi** [comment]
Because this HTML is full of settings and on a GIF you can see them - when I drag slider. So changes like this should work fast and also this HTML can contains another DOM trees which I can not erase by innerHTML. InnerHTML is slow and removes all old elements.

**Comment by mightyiam** [comment]
Thank you for the explanations. I understand to some degree. A sandbox is kind of a user feature. The difference between this library and a user feature in terms of where they are on the stack is too great. Thus a sandbox module doesn't sit well with me. Perhaps an error handling module. And that's pretty much what the example API describes. Regarding the question of whether this repository is the right place for it — I don't feel that it would be. The API surface determines the amount of work it takes to maintain a project. And adding more surface here doesn't feel right.

**Comment by grimalschi** [comment]
Ok, probably I should make it as an external repo

**Comment by patomation** [comment]
What about making it a plugin?

**Comment by mightyiam** [comment]
@patomation in Snabbdom the concept of a plugin is "module".
