### ISSUE TITLE
Suggestion: Ability to use arrays of child-nodes everywhere a single node can be used.

### ISSUE THREAD

**Issue by kay999** [snabbdom/snabbdom#76]
One suggestion: It would be helpful if vnodes could insert arrays of vnodes instead of only a single one.  This would make it much more flexible and would eliminate the need for "useless" in-between container-tags (which genrally works fine, but is problematic for certain use-cases for example when using a nth-child-selector in css).

To circumvent this, in the moment I use a simple 'h'-wrapper which flattens it's arguments before inserting:

```javascript
function flatten(data) {
	var res = [];
	function flat(data) {
		_.each(data, function(v) {
			if (v === null || v === undefined || v === false) {}
			else if (_.isArray(v)) flat(v);
			else res.push(v);
		})
	}
	flat(data);
	return res;
}
exports.h = function(tag, opts, args) {
	return h(tag, opts || {}, flatten(Array.prototype.slice.call(arguments, 2)))
};
```

This makes building node-trees much easier (but requires a {} if there are any child nodes).

Problem with my solution: It won't work for thunks, because data.vnode only supports a child-node. So if there is a new thunk-implementation comming, maybe it's possible to address this problem, too.

**Comment by kay999** [comment]
BTW: data.vnode isn't part of the public documented interface, yet. Maybe it should?

**Comment by AlexGalays** [comment]
That would lower the performances for sure; in a significant way? Not sure ^^

**Comment by xmo-odoo** [comment]
A rope-style `children` collection would indeed be really convenient when mixing a bunch of "static" child nodes with a dynamic sequence thereof, though it'd probably make reconciliation somewhat more complex.

**Comment by TylorS** [comment]
@kay999 `vnode` is now part of the documentation.

**Comment by paldepind** [comment]
Many utility libraries, both Ramda and Lodash, have a `flatten` function. I.e. one can just do `h('div', flatten([...]))`. This seems like a reasonable solution to me so I'll close this. Feel free to reopen if you disagree :smile:
