### ISSUE TITLE
Missing typescript types

### ISSUE THREAD

**Issue by jgonte** [snabbdom/snabbdom#765]
I am trying to develop a web component library using snabbdom for JSX

I execute yarn install snabbdom

Cannot find module 'snabbdom' or its corresponding type declarations.ts(2307)

It seems it is missing the *.d.ts files

**Comment by jgonte** [comment]
I mean yarn add snabbdom

**Comment by mightyiam** [comment]
Thank you for using Snabbdom, @jgonte. There is no default exported module. So the path `snabbdom` does not exist. See the readme for the various import paths. One of them is `snabbdom/init`. Also see the pinned issue.
