### ISSUE TITLE
Type 'number' is not assignable to type 'string'.ts(2322)

### ISSUE THREAD

**Issue by patomation** [snabbdom/snabbdom#772]
When using inline styles and a property such as top or left.
Using a number such as 0 is not assignable. I would have to use '0'. 
It would be nice If I could use numbers too.
Is this expected? 
```javascript
const modal = () => h('div', {
  style: {
    background: 'red',
    position: 'absolute',
    top: 0,
    left: 0,
    padding: 0
  }
}, 'some content')
```

**Comment by patomation** [comment]
I was taking a look at ```src/package/modules/style.ts
```typescript
export type VNodeStyle = Record<string, string> & {
  delayed?: Record<string, string>
  remove?: Record<string, string>
}
```
How would one add something like:
```
padding?: number | string
```

**Comment by mightyiam** [comment]
Thank you for the suggestion, @patomation. First, I'd like to share my view that improvements can be made to the typing of the style module. For example, a larger #339.

This specific change may seem desirable but it is also contrary to the types of the various browser APIs provided by TypeScript itself. For example, see [this issue comment](https://github.com/microsoft/TypeScript/issues/15368#issuecomment-297041814). For this reason, I hope you don't mind, I will close this issue.
