### ISSUE TITLE
Ambiguity in eventlisteners API

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#802]
```js
const vnode = h('div', { on: { click: [
  function a () {},
  function b () {},
] } })
```

According to the documentation, it seems that `a` and `b` could be one of
1. two different event listeners
2. one loaded / carrier event listener, which would be called as `a.call(vnode, b, event, vnode)`

**Comment by mightyiam** [comment]
I would say that the loaded listener feature (2) is not necessary. Also, it is not supported by the TypeScript types (#795). I suggest removing it. That seems to be an acceptable breaking change that feels like an improvement in this module. This particular feature was introduced in c2b6e7c3253214dfa8f04cfe80c32e4f6d13e31b and documentation for it was introduced in d1867d568f4dcad5f4c9ee49880814eb9d04efe4.

It's quite straightforward to replace usage of this feature. Two possible patterns immediately come to mind. The first is using `Function.prototype.bind`
```js
const vnode = h('div', { on: { click: handler.bind(context, argA, argB) } })
```

The second is using scope:
```js
const buttons = [1, 2, 3]
  .map((id) => h('button', { on: { click: () => { handler(id) } })
})
```

Another alternative would involve either the data module or the attributes module to add a data-* attribute to the element and read that in the event listener.

**Comment by kuraga** [comment]
:+1:

> would involve either the data module or the attributes module to add a data-* attribute

Can we do it using current functionality, can't we?

**Comment by mightyiam** [comment]
> > would involve either the data module or the attributes module to add a data-* attribute
> 
> Can we do it using current functionality, can't we?

Yes, I have experience with this.

**Comment by paldepind** [comment]
Btw, the reason for the original design was performance and a slightly more concise syntax. `() => { handler(id) }` creates a new function whereas `[handler, id]` only creates an array. The later may be more efficient.
