### ISSUE TITLE
Unused '@ts-expect-error' directive in Event Listener module

### ISSUE THREAD

**Issue by TechQuery** [snabbdom/snabbdom#844]
## What happened?

[My project](https://web-cell.dev/) imports TypeScript source codes of SnabbDOM:

https://github.com/EasyWebApp/WebCell/blob/20c8fff2e8f788537c68bb6507d5af784b561e52/source/renderer.ts#L7

When I run `tsc`, I got an error:

> node_modules/snabbdom/src/package/modules/eventlisteners.ts:17:5 - error TS2578: Unused '@ts-expect-error' directive.

https://github.com/snabbdom/snabbdom/blob/349c663b795adcc9b1b3fd28e3630e2098228c9d/src/package/modules/eventlisteners.ts#L14-L25

## My Environment

|  software  | version |
| :--------: | :-----: |
|    Node    | 12.18.2 |
|    NPM     | 6.14.8  |
| TypeScript |  4.0.2  |
|  SnabbDOM  |  2.0.0  |

**Comment by mightyiam** [comment]
Importing TypeScript source code is not supported. The TypeScript source code of this project is provided in the package not for the purpose of being compiled by the consumer, but because it is necessary for debugging with source maps.

Use the JavaScript, instead. If you have an issue using the JavaScript, please look through the issues and if you don't find your issue, file one.

**Comment by kuraga** [comment]
@mightyiam him, haven't known. Is it common practice? Is it difficult to provide TypeScripf?

**Comment by mightyiam** [comment]
I've never heard about packages providing TypeScript. Packages provide JavaScript plus type information in `.d.ts` files. And that's what we do. I don't want to support something for no good reason.

**Comment by TechQuery** [comment]
It won't bundle *duplicate helper functions* while **importing TypeScript source directly**.

**Comment by mightyiam** [comment]
> It won't bundle _duplicate helper functions_ while **importing TypeScript source directly**.

What is "It", please?

**Comment by TechQuery** [comment]
@mightyiam Bundlers

**Comment by TechQuery** [comment]
Answer to myself:

1. replace all `snabbdom/src` with `snabbdom/build`
2. reconfigure Jest: `"preset": "ts-jest"` to `"preset": "ts-jest/presets/js-with-ts"`
3. add `"allowJs": true` to `tsconfig.json`

Thanks: https://kulshekhar.github.io/ts-jest/user/config/#the-3-presets

**Comment by mightyiam** [comment]
@TechQuery could you please share why you insist on importing the TypeScript?
