### ISSUE TITLE
Move global type augmentation to `.d.ts` file

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#846]
https://github.com/snabbdom/snabbdom/blob/fb0af959295f90dff6b1dd2c9f8b7cb26fec1827/src/test/benchmark/core.ts#L19-L26

https://github.com/typescript-eslint/typescript-eslint/issues/2519#issuecomment-688633630

**Comment by patomation** [comment]
Will moving this into a .d.ts file remove the need to have `eslint-disable @typescript-eslint/no-unused-vars`?

**Comment by mightyiam** [comment]
@patomation yes, but it might not be necessary. See [this comment](https://github.com/typescript-eslint/typescript-eslint/issues/2519#issuecomment-691594167).

**Comment by jvanbruegge** [comment]
This is already fixed by now
