### ISSUE TITLE
Isomorphic snabbdom

### ISSUE THREAD

**Issue by designeng** [snabbdom/snabbdom#86]
It's rather a question. Is it possible to use snabbdom.js in isomorphic apps?
UPD: I found [motorcycle-isomorphic-boilerplate](https://github.com/TylorS/motorcycle-isomorphic-boilerplate/blob/master/src/server/web/index.js), motorcycle.js uses snabbdom in DOM Driver. But what about CSR after SSR - obviously there is no built-in way for components to understand that they were rendered on the server (as React.js does by data-react-checksum attribute)?

**Comment by avesus** [comment]
`npm install --save snabbdom-to-html`



-- 
Best Regards,
Ivan Borisenko

**Comment by minimok** [comment]
Anyone know whether there's an actual example out there of SSR with snabbdom? I'm guessing it'll need the use of snabbdom-virtualize (or similar) on the client?

**Comment by andyrj** [comment]
I have put together a little starter kit that does SSR with snabbdom-to-html, https://github.com/andyrj/snabbdom-redux-starter ...  It also has custom routing, and integration with Redux.  I think the part that you are interested in is fairly straight forward to pull from src/server.js for the SSR code and src/index.js for the client side rendering of the same components.

It's just a rough extraction of some logic from another project of mine, so it's not "CSS" pretty or well documented at the moment but it works well for my purpose as a basic starter kit.

**Comment by minimok** [comment]
Oh cool! Will take a look...I'm having fun with snabbdom and Mobx at the mo' - nice combination...but SSR will be the icing on the cake!

**Comment by staltz** [comment]
Yes snabbdom-to-html is pretty good and we use that in Cycle.js, example: https://github.com/cyclejs/cyclejs/tree/master/examples/isomorphic

I think this issue can be closed, since it's a question.
