### ISSUE TITLE
thunk doesn't seem to work with svg child elements

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#867]
My render functions looks like this:

```javascript

function renderSvg (lines) {
    return h(
        'svg',
        {
            style: {
                height: '200px',
                width: '200px',
                'background-color': 'white'
            },
            attrs: {
                xmlns: 'http://www.w3.org/2000/svg',
                viewBox: '0 0 200 200'
            }
        },
        renderLineGroup(lines)
    )
}


function renderLineGroup (lines) {
    const strokeWidth = 1
    const dashArray = '4 2'

    return h(
        'g',
        {},
        lines.map((l, idx) => thunk('line', `line_${idx}`, renderLine, [ l.x1, l.x2, l.y1, l.y2, strokeWidth, dashArray ]))
        //lines.map((l, idx) => renderLine(l.x1, l.x2, l.y1, l.y2, strokeWidth, dashArray))
    )
}


function renderLine (x1, x2, y1, y2, strokeWidth, dashArray) {
    return h('line', {
        style: {
            'stroke-width': strokeWidth,
            stroke: 'red'
        },
        attrs: { x1, x2, y1, y2, 'stroke-dasharray': dashArray }
    })
}

```

This constructs the svg tag as expected, but it doesn't actually draw. So strange! Here's what it looks like when rendering via `thunk`:
<img width="1233" alt="thunk" src="https://user-images.githubusercontent.com/718067/94173632-106f0380-fe49-11ea-86eb-73586f5954b3.png">

when I comment out the `lines.map` line and uncomment the one that doesn't use thunk, I see what I'd expect:

<img width="1250" alt="non-thunk" src="https://user-images.githubusercontent.com/718067/94173686-2381d380-fe49-11ea-8dc2-713adaac7d35.png">

**Comment by mreinstein** [comment]
this could potentially be a side effect of #388

**Comment by macarc** [comment]
The issue is that the virtual node returned from `thunk` doesn't have any children, it does everything through `prepatch`
thunk.ts line 58:
```ts
return h(sel, {
    key: key,
    hook: { init, prepatch },
    fn: fn,
    args: args
  })
```

Which means `addNS` skips it, since it just checks for children.

However, `addNS` will add a `data.ns` to the thunk vnode, so if `prepatch` was changed so that it calls `addNS` on its children when it creates them, that might fix it. I think that would require adding something like:
```ts
if (thunk.data.ns) addNS(thunk.data, thunk.children, thunk.sel);
```
or similar to `copyToThunk` (also importing `addNS`).

I will check it but I can't right now.

That's also a bit hacky, it might be a bit nicer to add an `isSVG` attribute to `VNode`, though that might be undesirable.

`addNS` doesn't seem particularly efficient either - it traverses the whole vnode tree (though only once each patch per `svg` element). Though it probably doesn't have that much of an effect.

**Comment by macarc** [comment]
Ok this diff fixes it:
```diff
diff --git a/src/package/h.ts b/src/package/h.ts
index b53a85a..0d9c7de 100644
--- a/src/package/h.ts
+++ b/src/package/h.ts
@@ -6,7 +6,7 @@ export type VNodeChildElement = VNode | string | number | undefined | null
 export type ArrayOrElement<T> = T | T[]
 export type VNodeChildren = ArrayOrElement<VNodeChildElement>

-function addNS (data: any, children: VNodes | undefined, sel: string | undefined): void {
+export function addNS (data: any, children: VNodes | undefined, sel: string | undefined): void {
   data.ns = 'http://www.w3.org/2000/svg'
   if (sel !== 'foreignObject' && children !== undefined) {
     for (let i = 0; i < children.length; ++i) {
diff --git a/src/package/thunk.ts b/src/package/thunk.ts
index c632eeb..c09e17b 100644
--- a/src/package/thunk.ts
+++ b/src/package/thunk.ts
@@ -1,5 +1,5 @@
 import { VNode, VNodeData } from './vnode'
-import { h } from './h'
+import { h, addNS } from './h'

 export interface ThunkData extends VNodeData {
   fn: () => VNode
@@ -16,10 +16,12 @@ export interface ThunkFn {
 }

 function copyToThunk (vnode: VNode, thunk: VNode): void {
+  const ns = thunk.data ? thunk.data.ns : null;
   (vnode.data as VNodeData).fn = (thunk.data as VNodeData).fn;
   (vnode.data as VNodeData).args = (thunk.data as VNodeData).args
   thunk.data = vnode.data
   thunk.children = vnode.children
+  if (ns) addNS(thunk.data, thunk.children as VNode[], thunk.sel);
   thunk.text = vnode.text
   thunk.elm = vnode.elm
 }
```

I'm just trying to figure out how to make a pull request (I never have done before).

**Comment by mreinstein** [comment]
@macarc I could jam these changes into a PR if that is helpful. @mightyiam any thoughts on the acceptability of this change?

**Comment by macarc** [comment]
Thanks, I got it working, I'm just working on #388 now (since they're both based around the same problem I think) and then I'll submit if that's all right with @mightyiam
