### ISSUE TITLE
File 'tsconfigs/browser-module' does not exist

### ISSUE THREAD

**Issue by Elve520** [snabbdom/snabbdom#874]
I use tsc command to generate js file but there is an error in tsconfig.json

:File 'tsconfigs/browser-module' does not exist

**Comment by patomation** [comment]
Let me take a look at it. Just to be sure, did you run `npm install` first?

**Comment by patomation** [comment]
I tryed on my clone of the repo doing the following
1. `git pull`
2. `npm install`
3. `npx tsc --project src/package/tsconfig.json`

Seems to compile just fine. Could you give us more information?
