### ISSUE TITLE
patch new node will lose my focus on input

### ISSUE THREAD

**Issue by xialvjun** [snabbdom/snabbdom#89]
Maybe you should use setAttribute to update html element rather than createElement and replace old element......
By the way, isn't it that DOM operation is very very slow? So less dom operation is better..Is it?

**Comment by paldepind** [comment]
Hello. I am not sure what you mean. What particular situation are you describing?

**Comment by AlexGalays** [comment]
xialvjun, you jumped to a conclusion. It will only use createElement if the vnode changed in a significant way (different selector or key)
