### ISSUE TITLE
Add compare fn to `thunk`

### ISSUE THREAD

**Issue by wclr** [snabbdom/snabbdom#902]
What do you think about adding additional param which will allow providing compare fn for state arguments (instead of default `===`)? So 

```js
thunk(selector, key, renderFn, [stateArguments], compareFn)
````

For example use ramda's `equals` for comparison:

```js
thunk('div', viewFn, [state], R.equals)
```

@paldepind

**Comment by kuraga** [comment]
Duplicate of #143.

**Comment by whitecolor** [comment]
Made PR for this. https://github.com/snabbdom/snabbdom/pull/904

Hope @paldepind wakes up someday. -)

**Comment by paldepind** [comment]
Closing this in favor of #143.
