### ISSUE TITLE
Listening for global / window events

### ISSUE THREAD

**Issue by JBetz** [snabbdom/snabbdom#910]
What is the right way to attach global / window event listeners to a vnode? For example, when you have a keyboard shortcut that you want to apply to multiple selected elements.

I've tried various combinations of event listeners with no success, namely because it requires tracking the previously registered event listeners so that they can be removed when the vnode is destroyed. It also requires a separate listener for every node rather than one global listener that dispatches to each of them, which seems nonideal.

```javascript
h('div', { 
  hook: { 
    insert: function(vnode) { 
      window.addEventListener('keyup', function(event) { 
        console.log(event);
      });
    },
    destroy: ???
  }
})
```

**Comment by JBetz** [comment]
Thanks @mreinstein, that pointed me in the right direction. 

One requirement I forgot to mention was that I need to be able to redefine the handler function at each render. To deal with that, I ended up using a single window event listener the iterates over a list of event handlers. Then my DOM builder function just clears and then reconstructs the subscription map during each render.

Biggest problem is that the set of possible window events the app can listen to is hardcoded, so not a great solution, but works well enough for my case.

**Comment by mreinstein** [comment]
Glad it helped!

> One requirement I forgot to mention was that I need to be able to redefine the handler function at each render

I _think_ you might be able to do that with the update hook:

```javascript
h('div', { 
    hook: { 
        update: function(/*vnode*/) { 
            // if there's any key handler registered in a previous update, remove it
            window.removeEventListener('keyup', _keyHandler);

            window.addEventListener('keyup', _keyHandler);
      },
      destroy: function () {
          window.removeEventListener('keyup', _keyHandler);
      }
  }
})
```

But you may want to consider refactoring your design so that you don't need to re-bind an event handler on each draw. addinng/removing an event handler each draw is likely going to be a bit expensive.
