### ISSUE TITLE
RFC: Export everything from the main 'snabbdom' module

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#913]
When updating dependencies, I (as have many others) stumbled across the issue of #723, in my case with typescript itself.
Is there any reason other than historical to split the package into multiple files that need to be imported seperately?
Why not simply:
```ts
import { VNode, init } from 'snabbdom';
```
IMO, this would be the cleaner API and it would resolve the issues with bundlers/typscript not supporting the `export` field

**Comment by jvanbruegge** [comment]
Wow, even better, TypeScript does not support `export`, so I have to use `build/package/h`, but mocha does so it complains that `build/package/h` is not in the exports field, making it impossible to import in a test

**Comment by kuraga** [comment]
Issues listed in https://github.com/snabbdom/snabbdom/issues/516#issue-541125637 are related.

**Comment by wclr** [comment]
It's time to fork snabbdom ;)

**Comment by jvanbruegge** [comment]
Incidentally, I am just starting with the new Cycle.js Neo DOM driver :thinking:

**Comment by mreinstein** [comment]
I ran into this too. the first thing I tried doing was `import snabbdom from 'https://cdn.skypack.dev/snabbdom'` and that failed with a big scary error message. It would be _really_ nice if the default thing that everyone will try to import actually worked out of the box.  It sounds like all we need to do is add a `".":` as the first entry in the `exports` section of `package.json`.

https://github.com/skypackjs/skypack-cdn/issues/125

**Comment by mreinstein** [comment]
see the first line of the `"exports": {` block from the node docs: https://nodejs.org/api/packages.html#packages_package_entry_points

**Comment by mreinstein** [comment]
This is not a disruptive change but it does technically break the API, so it makes sense to do this in the 3.0.0 release.

**Comment by mightyiam** [comment]
There decision to go with the `exports` field is solid. TypeScript can be made to behave, by defining some `paths`:
https://www.typescriptlang.org/tsconfig#paths

It covers for the lack of `exports` field support.

Please try that, @jvanbruegge, and let me know. I'll assume this answers your problem and close this.

**Comment by mreinstein** [comment]
@mightyiam come on man, you can't just disappear, drop the project, and then come back and start making unilateral decisions.

**Comment by mightyiam** [comment]
There's one problem here, and it is the lack of support for the `exports` field in TypeScript. A reasonable solution could be to document the `paths` workaround in the readme. That should take care of the issue. @mreinstein would you like to do that?

**Comment by jvanbruegge** [comment]
My main point is, why bother with this at all? A way cleaner api is not to expose some internal package structure anyways

**Comment by mightyiam** [comment]
@jvanbruegge the `exports` field is the way forward in the ecosystem. We're not officially exposing the internal package structure. We're presenting it as a workaround.

**Comment by niklasf** [comment]
Another workaround would be to use `./` as the target directory instead of `./build` During development it might be a minor inconvenience to have many files in the root directory, but it wouldn't require consumers to set anything special like `paths`. As soon as exports is properly supported, the directory could be changed to `./build` again, without that being a breaking change.

**Comment by jvanbruegge** [comment]
I still don't see the benefit of using `exports`.
As I see it by just removing that:
- The user does not have to remember/check which module exports what
- The user does not need any workarounds to import snabbdom
- We can offer commonjs modules as well as es6 seamlessly
- We can change the inner project structure without changing the api

Benefits of keeping `exports`:
- None?

**Comment by niklasf** [comment]
I suppose:

* Importing only the required modules. Depending on the capabilities of the bundler/minifier this might or might not save a few bytes.

**Comment by mightyiam** [comment]
The greatest benefit of the `exports` field is decoupling of export paths and package file structure. That, of course, depends on the importing mechanism having support for `exports` field. The last major player to lack such support may be TypeScript.

I chose to have only ES modules, to ease maintenance work. Users are able to use it. I support this decision. It helps shift the ecosystem toward ES modules. And it takes away 1 decision from the user.

**Comment by paldepind** [comment]
One of the reason why there are separate imports is that many users of Snabbdom doesn't need everything. For instance, many things build on top of Snabbdom make their own `h` function, don't use all the modules, etc.

Maybe tree-shaking is sufficient these days, but I think its important to preserve the possibility for clients to not import everything always. Perhaps we could use the [cherry-pick](https://github.com/Andarist/cherry-pick) tool? Maybe that will solve the problems in #723.

**Comment by jvanbruegge** [comment]
Tree shaking should be enough. And those people that really want to import only a single file can still do `import { h } from 'snabbdom/build/h'.

**Comment by paldepind** [comment]
As tree-shaking is a standard feature in build systems these days relying on it is fine with me.
