### ISSUE TITLE
come up with a plan for v3, roadmap?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#917]
There are some things that could be really nice in a next version. Just ideas off the top of my head, from things I've encountered while shipping snabbdom based products to production:

* shadow dom support
* custom element support
* consider dropping any special accommodations for internet explorer
* consider dropping the automated dependency update bot (it's a neat idea, but it's just creating noise in the PRs and we don't seem to pay any attention to it.)

I'm sure there are other things/ideas, this is just meant as a conversation starter.

**Comment by paldepind** [comment]
> consider dropping the automated dependency update bot (it's a neat idea, but it's just creating noise in the PRs and we don't seem to pay any attention to it.)

Yeah, I agree. It's a nice idea but it creates a lot of noise. It would be much nicer if it could be configured to only create one PR per month where it updated everything.

**Comment by jvanbruegge** [comment]
As I was annoyed by this too (had to configure github to not notify on PRs) and checked, but renovate only has an option for limiting it to X per hour, not per day, week or month

**Comment by jvanbruegge** [comment]
But it might be possible to run the renovate CLI with a scheduled github action to achieve this

**Comment by mreinstein** [comment]
Or we could drop all this nonsense complexity and a developer could run `npm update` once every 2 months. ;)

**Comment by kuraga** [comment]
I support all points :)

You know my position - fix bugs (expansively, considering the possibility of similar problems nearby) first (i.e., also, in parallel).

@mreinstein , thanks for your come back!

Could help but my internals' knowledge isn't excellent. But could try to fix annoying bugs. Since project will grow :)

**Comment by mreinstein** [comment]
I didn't see the announcement back in september that mightyiam has stepped down, because it was done via a github issue that was open for less than a day.

Is anyone else picking up maintainership of this project?   Is anyone at the helm?

**Comment by mreinstein** [comment]
@paldepind

**Comment by paldepind** [comment]
@mreinstein 

> custom element support

Have you seen #829? That PR looks good to me.

**Comment by mreinstein** [comment]
I've created a new milestone called `v3` for this. I think it would be a good idea to group all of the changes we intend for the next one into this milestone. Especially the breaking change related ones.

**Comment by mreinstein** [comment]
related to https://github.com/snabbdom/snabbdom/issues/359

**Comment by jvanbruegge** [comment]
I've opened #953, which is the last open issue on the v3 milestone. I'd say after merging that we should cut the release for v3 and close this issue

**Comment by mreinstein** [comment]
I'll jut close it now, because the issue is really about having a plan for v3, which we have.

It probably makes sense to deal with #359  since that's for v2, we've already shipped v2, but there are items listed in that ticket that _could_ be candidates for v4
