### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by hsi-odoo** [snabbdom/snabbdom#922]
[This package](https://www.jsdelivr.com/package/npm/snabbdom) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by jvanbruegge** [comment]
This would be solved by #913

**Comment by mreinstein** [comment]
closing in favor of #913
