### ISSUE TITLE
Disable Renovate

### ISSUE THREAD

**Issue by paldepind** [snabbdom/snabbdom#929]
As discussed in #917 the Renovate plugin is a nice idea, but it creates a lot of noise. And all of Snabbdoms dependencies are for development only, so always keeping them up to date is not super important.

It appears that @jvanbruegge [volunteered to do this](
https://github.com/snabbdom/snabbdom/issues/868#issuecomment-778303146). I need to give him the necessary privileges.

**Comment by mreinstein** [comment]
I just closed all the open renovate bot PRs. It doesn't shut off the generation of new ones but it cleaned some stuff out for now. I think it's just a matter of getting rid of the `renovate.json` file, and unregistering the github app.

**Comment by jvanbruegge** [comment]
I will take care of that in the following days

**Comment by mightyiam** [comment]
I like renovate's role. It keeps maintenance from piling up. If its followed through. It's difficult to let go and see changes that I don't like being made.

**Comment by mreinstein** [comment]
> I like renovate's role.

I like the _idea_ of it. The idea that computer keeps all the checkboxes checked is compelling, because I don't want to have to do that forever. ;)

> It keeps maintenance from piling up. 

It depends on how one defines maintenance. I agree with Simon that these are dev dependencies, and it's not clear that keeping them up to the absolute latest 100% of the time is that important. Especially compared to all of the other real known bugs a given project might have.

**Comment by mightyiam** [comment]
Was renovate disabled?

**Comment by mreinstein** [comment]
I don't think Jan has gotten to it yet. Feel free to disable it if you're around and have access though.

**Comment by mightyiam** [comment]
Please keep it running.

**Comment by jvanbruegge** [comment]
The problem is that it is impossible to set it to run only once a week or once every two weeks. It drowns out "real" PRs with unneccesary noise. As snabbdom has no dependencies, updating dev dependencies really only matters before a new release. So I hardly see the need for the bot

**Comment by mightyiam** [comment]
@jvanbruegge I get it. It's not a necessity for me, either. Only a preference. I hope it doesn't bother anyone, as long as I properly review them as they come along. Is there a way to control notifications in a way that filters them out?

**Comment by jvanbruegge** [comment]
Sadly no, I can either disable notifications completely for PRs or get them all

**Comment by mightyiam** [comment]
I wouldn't want that at all.
