### ISSUE TITLE
concerns about contributing

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#944]
I think it would be constructive to have a little dialog on what one can expect from snabbdom moving forward in terms of contributors. This project's health is troubling me.

My concerns:
* the issues and PRs have been piling up for a while without any triage or discussion
* maintainer quit 5 months ago, via a github issue that was open for less than a day. Because of this I only discovered it in the last few days, and completely by accident
* now that we're talking about getting fresh eyes, the previous maintainer is saying they'll come back. In what capacity? Is it only to block ideas that are disagreed with? What happens next time someone gets burned out?

I must add that I'm not looking to pick on anyone here or demand my issues get resolved.  But I do think there must be 
some way at the very least of knowing who if anyone is going to be maintaining this thing.

I tend to favor less process and ceremony, so I'm definitely not advocating for adding lots of beauracracy here. But surely we can do _something_ to solve these problems going forward. I depend heavily on snabbdom and if we can't maintain it then I need to start looking at other options, whether its a fork or an alternative lightweight vdom.

**Comment by mightyiam** [comment]
Some reviews take hours. Some contributions and suggestions are made without complete understanding of all of the details involved. Work requires time. Yesterday I spent around 5 hours on maintenance and that's not even making progress on any major issues. Make sure you're aware of this context.

**Comment by mreinstein** [comment]
I'm not asking for you to contribute harder. No one is suggesting you are not working hard.

The issue is the continuity of maintainership and having some plan.

**Comment by mightyiam** [comment]
The only thing that can move a project forward is the time and effort of at least one person. Everything else will fall into place according to that person's capability. Your concern is valid. Even considerable and probably valid contributions don't get reviewed due to lack of work from a person in charge. It's simple. Currently, I can comment and do some minor chores and reviews. Personally, I am studying Rust and am more interested in that ecosystem. I feel it's the future of both systems programming and the web. So I'm not inclined to invest a lot in snabbdom.

**Comment by mreinstein** [comment]
> Even considerable and probably valid contributions don't get reviewed due to lack of work from a person in charge. It's simple.

Yes, agreed.


> So I'm not inclined to invest a lot in snabbdom.

that's totally fair. I think you should go explore stuff that you actually _do_ want to invest time in, and let the community pick up snabbdom. I agree rust is super exciting. My reality is the day job for the foreseeable future is filled with snabbdom.

**Comment by mightyiam** [comment]
@mreinstein I probably should. And yet I will be available for at least clarifications in this project.

**Comment by mreinstein** [comment]
I definitely would prefer _not_ to lose the expertise of someone that has been maintaining this project for a while. :)
