### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by nilslindemann** [snabbdom/snabbdom#960]
I am not fluid in these Node.js things, how would I build this?

**Comment by nilslindemann** [comment]
I figured out how to get the examples running.

1. In case you have not done so, install Node.js, then install Typescript globally (`npm install -g typescript`).
2. run `tsc` in the repo directory (where the tsconfig.json is located). This creates the javascript files in the 'build' directory.
3. Fix the imports and exports in those files by adding the missing file extension. E.g. replace `export { init } from "./init"` with `export { init } from "./init.js"`. Node.js automatically adds these extensions when they are missing, [but browsers do not, for performance reasons](https://stackoverflow.com/a/54485528/1658543).
4. [Start a web server](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/reviews) with the root set to the repo directory.
5. Navigate to the examples, e.g. http://127.0.0.1:8887/examples/hero/ .

**Comment by nilslindemann** [comment]
Leaving this open, so that others can find it.

**Comment by nilslindemann** [comment]
@heng1025 I tried your method, I installed the dependencies - 1007 packages sized 250 MB - and guess what, afterwards it did not work. Now lets clean up my system.

**Comment by heng1025** [comment]
> @heng1025 I tried your method, I installed the dependencies - 1007 packages sized 250 MB - and guess what, afterwards it did not work. Now lets clean up my system.

This way just generates es module real time,then you can use source code to debug.

**Comment by nilslindemann** [comment]
Sorry, @heng1025, not my day today. Thanks for your input.

**Comment by mreinstein** [comment]
You shouldn't need to add any rollup config or any of that stuff. This should work:

1. make sure you have node and `tsc` installed
2. clone this repo
3. `npm install`
4. `npm run build`
5. (optional) validate your build succeeded and all tests pass by running `npm test`

That should be it.

**Comment by nilslindemann** [comment]
@mreinstein thanks for the `npm run build` hint. Still, one has to manually append `.js` to the imports in those generated files, in order to make the examples work in the browser.

Also, `npm install` (which downloads 250 mbs of dependencies) was not needed in my tests. `npm run build` works without this step.

**Comment by nilslindemann** [comment]
Ok, in order to succeed `npm test`, `npm install` has to be run first.

**Comment by mreinstein** [comment]
> Still, one has to manually append .js to the imports in those generated files, in order to make the examples work in the browser.

Hmm, that is indeed odd. @jvanbruegge  when I try to run the `examples/` files in my browser, they are broken.
e.g.,
```bash
serve snabbdom/
open http://localhost:5000/examples/reorder-animation/
```

When the browser window opens I see a bunch of errors:

<img width="885" alt="Screen Shot 2021-06-16 at 4 14 55 PM" src="https://user-images.githubusercontent.com/718067/122306870-136dc080-cebe-11eb-90e5-0f3bdd4bd0c7.png">

Why is `build/index.js` missing `.js` suffix? These aren't real es modules currently.

**Comment by nilslindemann** [comment]
Yep, that is what I see too.

**Comment by shfshanyue** [comment]
Try to rewrite`build/*` to `build/*.js` using `serve`. It might be able to help you.

**serve.json**

``` js
{
  "rewrites": [
    { "source": "build/:file", "destination": "build/:file.js" },
    { "source": "build/helpers/:file", "destination": "build/helpers/:file.js" },
    { "source": "build/modules/:file", "destination": "build/modules/:file.js" }
  ]
}
```

Run examples

``` bash
$ serve .
```

Navigate to the examples: <http://127.0.0.1:5000/examples/hero/>. It works well 

![image](https://user-images.githubusercontent.com/13389461/130379160-60f83746-ae23-4977-af53-acc31956c495.png)

I will submit a PR for this if needed.

**Comment by mreinstein** [comment]
I'm not opposed to updating the README with more details, but this module (like most other javascript modules) assume a baseline level of setup before usage.  Git and node are part of this core pre-req that's just expected.

> Install Typescript globally

Don't do that; `typescript` is included as a dev dependency in this repo.  It's better to avoid globally installing tools if you don't have to, that way each module can directly declare what it needs, including vesions

>  I got the following message printed a few times.

I don't know but it looks like a misconfigured local dev environment.  The message seems to indicate you're running an older version of chrome/chromium? Try updating that?

**Comment by nilslindemann** [comment]
I created PR #1088, which suggests adding this to the README. Let's continue there.
