### ISSUE TITLE
publishing snabbdom@3.0.2 didn't actually get the latest code?

### ISSUE THREAD

**Issue by mreinstein** [snabbdom/snabbdom#969]
I just did `npm install snabbdom` in my project, looked in the `node_modules` folder, and it seems that the fix that got merged in before v3.0.2 was published isn't included. 

Did we forget to build?

**Comment by jvanbruegge** [comment]
Yes indeed you are correct, it did not build. I've now added building and testing to the release script and pushed a new version with the fix
