### ISSUE TITLE
Can't patch document fragment created from a text node

### ISSUE THREAD

**Issue by cjohansen** [snabbdom/snabbdom#971]
I'm trying to patch in a text node, using a document fragment:

```js
var patch = snabbdom.init([
  snabbdom.propsModule
]);

var el = document.createElement('div');
document.body.appendChild(el);

var fragment = document.createDocumentFragment();
fragment.appendChild(document.createTextNode("Text"));

var vdom = patch(el, snabbdom.toVNode(fragment));
```

This throws an exception when snabbdom tries to `createElement` and the vnode `sel` is an empty string. The changelog mentioned document fragments being supported, but perhaps some other way? Am I doing it wrong?

**Comment by jvanbruegge** [comment]
Document fragments should work, but sadly I can't have a deeper look at this at the moment as I am busy the next two weeks

**Comment by cjohansen** [comment]
After looking into this some more I realize that the initial report is a little inaccurate. The problem is that calling `toVNode` with a document fragment created from only a text node creates a vnode that snabbdom can't render.
