### ISSUE TITLE
Question: Highlighting changes

### ISSUE THREAD

**Issue by ababushkin** [snabbdom/snabbdom#984]
I'm looking at visually highlighting changes that have occurred between two pages (Page A and Page B) - specifically things that were "added" or "removed" and prototyping it with `snabbdom` based on a VDOM diff. Before I dig this rabbit hole any deeper, how viable do you think this is?

It's part of a visual detection tool and standard techniques that I'm already using (e.g. image diffing, basic text diffing) are OKAY but not GREAT.

**Comment by jvanbruegge** [comment]
Should be quite easy to do with a snabbdom module that has `create` and `destroy` hooks.
