### ISSUE TITLE
EventListener doesn't support argument passing

### ISSUE THREAD

**Issue by tobymao** [snabbdom/snabbdom#988]
The documentation claims to support eventHandlers with argument passing

```
function clickHandler(number) {

  console.log("button " + number + " was clicked!");

}

h("div", [

  h("a", { on: { click: [clickHandler, 1] } }),

]);
```

But trying this in my app and looking at the code, it doesn't work. InvokeHandler doesn't have a special case to ever call the handler with the 2nd argument of a list and there are no unit tests for this so I'm wondering if the documentation is out of date or if this is a bug?

**Comment by jvanbruegge** [comment]
A PR to fix the documentation would be very welcome :)
