### ISSUE TITLE
Publish UMD bundles for public CDNs

### ISSUE THREAD

**Issue by geotrev** [snabbdom/snabbdom#999]
Hello!

I'm working on a project and noticed I'm unable to use a Snabbdom UMD bundle via one of the several free CDNs available, such as unpkg or jsdelivr. It seems that today [UMD bundles aren't published](https://www.jsdelivr.com/package/npm/snabbdom). [In the past](https://github.com/snabbdom/snabbdom/blob/a5b93a7137cf18b51696c385525672e09a3db22b/dist/snabbdom.js) a `dist` folder provided this but it's since been removed.

I found some [comments](https://github.com/snabbdom/snabbdom/issues/516#issuecomment-621962068) in 2020 that indicating removing UMD bundles was beneficial to keep the build clean, but I don't think that's necessarily the case. UMD bundles are relatively straightforward and you can easily specify which methods (perhaps not all) are added to the global `snabbdom` namespace with a separate entry file.

If this seems reasonable I'm happy to take a stab at a rollup config (have done this in [a](https://github.com/geotrev/core-flux/blob/main/rollup.config.js) [few](https://github.com/geotrev/omdomdom/blob/main/config/rollup.build.config.js) [projects](https://github.com/geotrev/rotom/blob/main/config/rollup.build.config.js) already, myself) and tie it to the version/publish process (probably a `preversion` or `prepublishOnly` npm script to build them automatically so it doesn't go out of date like [mightyiam has indicated](https://github.com/snabbdom/snabbdom/pull/515) was a problem previously).

Thanks for considering :)

**Comment by geotrev** [comment]
As a quick exercise, the change could be as simple as this:

https://github.com/geotrev/snabbdom/commit/ff2f0b42857b1df148a4c0fa20dc8cbab0e639d5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R25-R84

**Comment by jvanbruegge** [comment]
I would be open to a PR that adds the relevant config to rollup and the build, but I will not have the `dist` folder pollute the git repo. If the UMD modules need to be commited to the repo then I'd say no

**Comment by geotrev** [comment]
Sure. It could be ignored from git and published to npm only. Thanks

**Comment by mreinstein** [comment]
It's time to embrace esm fully

**Comment by mreinstein** [comment]
This works today, as-is without any wonky build steps or legacy module wrapping formats:

```javascript
import html from 'https://cdn.skypack.dev/snabbdom'
```

**Comment by geotrev** [comment]
Thanks @mreinstein! My use-case is pretty small and a straight import will actually work much better than what I was trying to do anyway. 😁 

Cheers

**Comment by mreinstein** [comment]
glad it worked out!
